// Bundles src/ modules + styles.css into a single self-contained Life-OS.html
// that works from file:// (browsers block ES module imports there).
// Zero dependencies. Supported syntax: `import { a, b as c } from './x.js'`,
// `export function|const|let|class name`.
//
//   node life-os/build.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const entry = resolve(root, 'src/app.js');
const modules = new Map(); // abs path -> { code, deps, exports }
const order = [];

function load(file, stack = []) {
  if (modules.has(file)) return;
  if (stack.includes(file)) throw new Error('Circular import: ' + [...stack, file].map((f) => relative(root, f)).join(' -> '));
  const src = readFileSync(file, 'utf8');
  const deps = [];
  const exportsList = [];
  let code = src.replace(/^import\s*\{([^}]*)\}\s*from\s*['"](.+?)['"];?\s*$/gm, (_, names, spec) => {
    const dep = resolve(dirname(file), spec);
    deps.push(dep);
    const binds = names.split(',').map((s) => s.trim()).filter(Boolean).map((s) => s.replace(/\s+as\s+/, ': '));
    return `const { ${binds.join(', ')} } = __m[${JSON.stringify(key(dep))}];`;
  });
  code = code.replace(/^import\s*\*\s*as\s+(\w+)\s+from\s*['"](.+?)['"];?\s*$/gm, (_, ns, spec) => {
    const dep = resolve(dirname(file), spec);
    deps.push(dep);
    return `const ${ns} = __m[${JSON.stringify(key(dep))}];`;
  });
  code = code.replace(/^export\s+(async\s+function|function|const|let|class)\s+(\w+)/gm, (_, kw, name) => {
    exportsList.push(name);
    return `${kw} ${name}`;
  });
  if (/^\s*export\s/m.test(code) || /^\s*import\s/m.test(code)) throw new Error('Unsupported import/export form in ' + relative(root, file));
  for (const d of deps) load(d, [...stack, file]);
  modules.set(file, { code, exportsList });
  order.push(file);
}
function key(file) {
  return relative(root, file).replace(/\\/g, '/');
}

load(entry);
const bundle = order.map((f) => {
  const { code, exportsList } = modules.get(f);
  return `// ---- ${key(f)}\n__m[${JSON.stringify(key(f))}] = (() => {\n${code}\nreturn { ${exportsList.join(', ')} };\n})();`;
}).join('\n\n');

const css = readFileSync(join(root, 'styles.css'), 'utf8');
let html = readFileSync(join(root, 'index.html'), 'utf8');
html = html.replace('<link rel="stylesheet" href="styles.css">', () => `<style>\n${css}\n</style>`);
html = html.replace('<script type="module" src="src/app.js"></script>', () => `<script>\n"use strict";\nconst __m = {};\n${bundle.replace(/<\/script/gi, '<\\/script')}\n</script>`);
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by life-os/build.mjs from life-os/src. Edit the sources, then rebuild. -->');
const out = join(root, 'Life-OS.html');
writeFileSync(out, html);
console.log(`Built ${relative(process.cwd(), out)} · ${order.length} modules · ${(html.length / 1024).toFixed(0)} KB`);
