// Copy for the plan-themed pricing page, membership cards and the themed
// QR checkout (learner walkthrough, VIP concierge). Payment-flow copy that
// both themes share stays in lib/qrPay.js (QR_COPY).

export const PLAN_COPY = {
  uz: {
    member: "A‘ZO",
    plan_word: "REJA",
    since: "BOSHLANGAN",
    status: "HOLAT",
    active: "Faol",
    always: "Doimiy",
    founding: "FOUNDING",
    your_name: "SIZNING ISMINGIZ",
    free_title: "Free",
    free_kicker: "Boshlash uchun",
    free_price: "Bepul",
    free_note: "Karta kerak emas",
    free_cta: "Bepul davom etish",
    learner_kicker: "Jiddiy o‘rganuvchilar uchun",
    vip_kicker: "To‘liq tajriba",
    card_short: "Visa / Mastercard",
    included: "Ichida nimalar bor",
    legend: "Rejangizni rangidan taniysiz",
    current: "Hozirgi rejangiz",
    trial: "Sinov",
    // learner walkthrough
    l_step_amount: "Summa",
    l_step_scan: "Skanerlash",
    l_step_receipt: "Chek",
    l_of: "{n}-QADAM · 3 DAN",
    l1_title: "Learner a‘zoligingiz tayyor",
    l1_sub: "Uch oddiy qadam. Har birida yoningizdamiz.",
    l1_hint: "Bu kod to‘lovingizni sizning hisobingizga bog‘laydi. To‘lovda izohga yozing.",
    l_next: "Davom etish",
    l2_title: "Bank ilovangizda skanerlang",
    l2_sub: "Shoshilmang — har bir qadamda yoningizdamiz.",
    l2_a: "Ilovangizda QR tugmasini bosing",
    l2_b: "Kodni skanerlang va aynan {amount} so‘m yozing",
    l2_c: "Izohga {code} ni qo‘ying va to‘lang",
    l2_tip: "Shu telefonda to‘layapsizmi? QR rasmini saqlang va ilovada “galereyadan” tanlang.",
    l2_paid: "To‘ladim — chekni yuklash",
    l_back: "Orqaga",
    bank_app: "bank ilovasi",
    l3_title: "Chekni yuklang",
    l3_sub: "Bank ilovasidagi to‘lov chekining skrinshoti yetarli.",
    l3_send: "Tekshirishga yuborish",
    // vip
    v_eyebrow: "VIP · SHAXSIY CHECKOUT",
    v_title: "Eksklyuziv a‘zolik",
    v_sub: "Bir necha daqiqa — va VIP imkoniyatlarining hammasi sizniki.",
    v_step1: "Bank ilovangizda QR kodni skanerlang",
    v_step2: "Aynan {amount} so‘m to‘lang, izohga {code} yozing",
    v_step3: "Chek skrinshotini yuklang — qolganini biz qilamiz",
    v_send: "Tasdiqlash uchun yuborish",
    v_concierge: "Shaxsiy yordamchingiz:",
    v_pending_title: "So‘rovingiz VIP navbatda",
    v_pending_sub: "To‘lovingizni birinchi navbatda tekshiramiz.",
    v_welcome_eyebrow: "A‘ZOLIK FAOLLASHDI",
    v_welcome_title: "Endi siz VIP siz",
    v_welcome_sub: "To‘lovingiz tasdiqlandi. VIP imkoniyatlarining hammasi hozirdan ochiq.",
    v_welcome_cta: "VIP tajribani boshlash",
    l_welcome_eyebrow: "LEARNER FAOLLASHDI",
    l_welcome_title: "Xush kelibsiz, a‘zo!",
    l_welcome_sub: "To‘lov tasdiqlandi. Endi butun yo‘l ochiq — har kuni bir qadam.",
    l_welcome_cta: "O‘rganishni boshlash",
    save_qr_png: "QR rasmini saqlash",
  },
  ru: {
    member: "УЧАСТНИК",
    plan_word: "ТАРИФ",
    since: "С",
    status: "СТАТУС",
    active: "Активен",
    always: "Всегда",
    founding: "FOUNDING",
    your_name: "ВАШЕ ИМЯ",
    free_title: "Free",
    free_kicker: "Для старта",
    free_price: "Бесплатно",
    free_note: "Карта не нужна",
    free_cta: "Продолжить бесплатно",
    learner_kicker: "Для серьёзной учёбы",
    vip_kicker: "Полный опыт",
    card_short: "Visa / Mastercard",
    included: "Что входит",
    legend: "Ваш тариф узнаётся по цвету",
    current: "Ваш текущий тариф",
    trial: "Пробный",
    l_step_amount: "Сумма",
    l_step_scan: "Скан",
    l_step_receipt: "Чек",
    l_of: "ШАГ {n} ИЗ 3",
    l1_title: "Ваше членство Learner готово",
    l1_sub: "Три простых шага. Мы рядом на каждом.",
    l1_hint: "Этот код связывает оплату с вашим аккаунтом. Укажите его в комментарии.",
    l_next: "Далее",
    l2_title: "Отсканируйте в приложении банка",
    l2_sub: "Не спешите — мы рядом на каждом шаге.",
    l2_a: "Нажмите кнопку QR в приложении",
    l2_b: "Отсканируйте код и введите ровно {amount} сум",
    l2_c: "В комментарии укажите {code} и оплатите",
    l2_tip: "Платите с этого же телефона? Сохраните QR и выберите его «из галереи».",
    l2_paid: "Я оплатил — загрузить чек",
    l_back: "Назад",
    bank_app: "приложение банка",
    l3_title: "Загрузите чек",
    l3_sub: "Достаточно скриншота чека из приложения банка.",
    l3_send: "Отправить на проверку",
    v_eyebrow: "VIP · ПЕРСОНАЛЬНАЯ ОПЛАТА",
    v_title: "Эксклюзивное членство",
    v_sub: "Несколько минут — и все возможности VIP ваши.",
    v_step1: "Отсканируйте QR в приложении банка",
    v_step2: "Оплатите ровно {amount} сум, в комментарии — {code}",
    v_step3: "Загрузите скриншот чека — остальное сделаем мы",
    v_send: "Отправить на подтверждение",
    v_concierge: "Ваш персональный помощник:",
    v_pending_title: "Заявка в VIP-очереди",
    v_pending_sub: "Мы проверим вашу оплату в первую очередь.",
    v_welcome_eyebrow: "ЧЛЕНСТВО АКТИВНО",
    v_welcome_title: "Теперь вы VIP",
    v_welcome_sub: "Оплата подтверждена. Все возможности VIP открыты.",
    v_welcome_cta: "Начать VIP",
    l_welcome_eyebrow: "LEARNER АКТИВЕН",
    l_welcome_title: "Добро пожаловать!",
    l_welcome_sub: "Оплата подтверждена. Весь путь открыт — шаг за шагом каждый день.",
    l_welcome_cta: "Начать учиться",
    save_qr_png: "Сохранить QR",
  },
  en: {
    member: "MEMBER",
    plan_word: "PLAN",
    since: "SINCE",
    status: "STATUS",
    active: "Active",
    always: "Always",
    founding: "FOUNDING",
    your_name: "YOUR NAME",
    free_title: "Free",
    free_kicker: "To get started",
    free_price: "Free",
    free_note: "No card needed",
    free_cta: "Continue for free",
    learner_kicker: "For serious learners",
    vip_kicker: "The complete experience",
    card_short: "Visa / Mastercard",
    included: "What’s included",
    legend: "Know your plan by its colour",
    current: "Your current plan",
    trial: "Trial",
    l_step_amount: "Amount",
    l_step_scan: "Scan",
    l_step_receipt: "Receipt",
    l_of: "STEP {n} OF 3",
    l1_title: "Your Learner membership is ready",
    l1_sub: "Three simple steps. We’re with you on each one.",
    l1_hint: "This code links the payment to your account. Write it in the payment comment.",
    l_next: "Continue",
    l2_title: "Scan it in your bank app",
    l2_sub: "No rush — we’re with you at every step.",
    l2_a: "Tap the QR button in your app",
    l2_b: "Scan the code and enter exactly {amount} so‘m",
    l2_c: "Put {code} in the comment and pay",
    l2_tip: "Paying on this same phone? Save the QR image and pick it “from gallery” in the app.",
    l2_paid: "I’ve paid — upload receipt",
    l_back: "Back",
    bank_app: "bank app",
    l3_title: "Upload your receipt",
    l3_sub: "A screenshot of the receipt in your bank app is enough.",
    l3_send: "Send for checking",
    v_eyebrow: "VIP · PRIVATE CHECKOUT",
    v_title: "Exclusive membership",
    v_sub: "A few minutes — and every VIP feature is yours.",
    v_step1: "Scan the QR code in your bank app",
    v_step2: "Pay exactly {amount} so‘m, comment: {code}",
    v_step3: "Upload the receipt screenshot — we handle the rest",
    v_send: "Send for confirmation",
    v_concierge: "Your personal concierge:",
    v_pending_title: "You’re in the VIP queue",
    v_pending_sub: "Your payment is checked first.",
    v_welcome_eyebrow: "MEMBERSHIP ACTIVE",
    v_welcome_title: "You’re VIP now",
    v_welcome_sub: "Payment confirmed. Every VIP feature is open from now on.",
    v_welcome_cta: "Start the VIP experience",
    l_welcome_eyebrow: "LEARNER ACTIVE",
    l_welcome_title: "Welcome, member!",
    l_welcome_sub: "Payment confirmed. The whole path is open — one step a day.",
    l_welcome_cta: "Start learning",
    save_qr_png: "Save QR image",
  },
};

export function pT(lang, key, vars) {
  const dict = PLAN_COPY[lang] || PLAN_COPY.uz;
  let s = dict[key] ?? PLAN_COPY.uz[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
  return s;
}
