// Humo / Uzcard QR payments — shared copy, styles and helpers for
// Pricing.jsx, pages/QrPayment.jsx and pages/AdminQrPayments.jsx.
// Server side: base44/functions/qrPayApi/entry.ts.

// Metallic button finishes from the approved design (2026-10-02 sketch):
// gold for the QR option, violet for card. Inline styles so the gradient,
// the top-edge highlight and the inner shading stay exactly as signed off.
export const METAL_GOLD = {
  background: "linear-gradient(180deg, #EBD6A2 0%, #C9A45E 46%, #A6803D 54%, #CDAE70 100%)",
  color: "#1F1606",
  border: "1px solid rgba(255,236,190,0.55)",
  boxShadow: "inset 0 1px 0 rgba(255,255,255,0.55), inset 0 -2px 6px rgba(0,0,0,0.22), 0 10px 22px rgba(60,40,10,0.35)",
};
export const METAL_VIOLET = {
  background: "linear-gradient(180deg, #8C66D4 0%, #6A40B6 46%, #53309A 54%, #6B44B6 100%)",
  color: "#F7F2FF",
  border: "1px solid rgba(205,185,255,0.35)",
  boxShadow: "inset 0 1px 0 rgba(255,255,255,0.32), inset 0 -2px 6px rgba(0,0,0,0.28)",
};
export const GOLD_TEXT = "#DCC08A";

export function formatUzs(n) {
  const v = Math.round(Number(n) || 0);
  if (!v) return "";
  return v.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}

export const QR_COPY = {
  uz: {
    banner_title: "Humo va Uzcard qabul qilinadi",
    banner_sub: "QR kod orqali, so‘mda to‘lang. Xorijiy karta shart emas.",
    or_uzs: "yoki {amount} so‘m",
    per_month: "/ oy",
    per_year: "/ yil",
    qr_btn: "Humo / Uzcard — QR orqali to‘lash",
    card_btn: "Visa / Mastercard bilan to‘lash",
    footer: "Humo / Uzcard: QR orqali, so‘mda · Visa / Mastercard, Apple Pay, Google Pay: karta orqali",
    back: "Narxlarga qaytish",
    eyebrow: "HUMO · UZCARD · SO‘MDA",
    title: "QR orqali to‘lash",
    sub: "Bank ilovangiz bilan QR kodni skanerlang va aniq summani to‘lang.",
    plan: "Reja",
    amount: "To‘lanadigan summa",
    code_label: "To‘lov kodi (izohga yozing)",
    copy: "Nusxa",
    copied: "Nusxalandi",
    recipient: "Qabul qiluvchi",
    save_qr: "QR rasmini saqlash",
    step1: "Bank ilovangizni oching va QR skanerlash bo‘limidan kodni skanerlang. Shu telefonda bo‘lsangiz, QR rasmini saqlab, ilovaga yuklang.",
    step2: "Aynan {amount} so‘m to‘lang. Izohga to‘lov kodini yozing: {code}",
    step3: "Chek skrinshotini yuklang va “To‘ladim” tugmasini bosing.",
    receipt: "To‘lov cheki (skrinshot)",
    pick: "Rasm tanlash",
    change: "Boshqa rasm",
    paid_btn: "To‘ladim",
    sending: "Yuborilmoqda...",
    need_receipt: "Avval chek skrinshotini yuklang.",
    hours: "Obuna to‘lov tekshirilgach faollashadi — odatda {hours} soat ichida.",
    hours_generic: "Obuna to‘lov tekshirilgach faollashadi.",
    help: "Muammo bo‘lsa:",
    help_tg: "Telegram orqali yozing",
    done_title: "So‘rovingiz qabul qilindi",
    done_sub: "To‘lovingizni tekshiramiz va obunangizni faollashtiramiz.",
    st_sent: "Chek yuborildi",
    st_check: "Tekshirilmoqda",
    st_active: "Obuna faollashtirildi",
    sum: "Summa",
    code: "To‘lov kodi",
    continue: "Mashq qilishda davom etish",
    approved_title: "Obunangiz faol!",
    approved_sub: "To‘lov tasdiqlandi. Yaxshi o‘qishlar!",
    rejected_title: "To‘lov topilmadi",
    rejected_sub: "Bu to‘lovni tasdiqlay olmadik. Savol bo‘lsa, bizga yozing.",
    try_again: "Qaytadan urinish",
    not_ready_title: "QR to‘lov tez orada ishga tushadi",
    not_ready_sub: "Hozircha Humo / Uzcard bilan to‘lash uchun bizga Telegram orqali yozing yoki karta bilan to‘lang.",
    err_generic: "Xatolik yuz berdi. Qaytadan urinib ko‘ring.",
    err_too_many: "Sizda tugallanmagan to‘lovlar ko‘p. Avvalgisini yakunlang yoki bizga yozing.",
    learner: "Learner", vip: "VIP", monthly: "Oylik", yearly: "Yillik",
  },
  ru: {
    banner_title: "Принимаем Humo и Uzcard",
    banner_sub: "Оплата по QR-коду в сумах. Иностранная карта не нужна.",
    or_uzs: "или {amount} сум",
    per_month: "/ мес",
    per_year: "/ год",
    qr_btn: "Humo / Uzcard — оплата по QR",
    card_btn: "Оплатить Visa / Mastercard",
    footer: "Humo / Uzcard: по QR, в сумах · Visa / Mastercard, Apple Pay, Google Pay: картой",
    back: "Назад к тарифам",
    eyebrow: "HUMO · UZCARD · В СУМАХ",
    title: "Оплата по QR",
    sub: "Отсканируйте QR-код в приложении банка и оплатите точную сумму.",
    plan: "Тариф",
    amount: "Сумма к оплате",
    code_label: "Код платежа (укажите в комментарии)",
    copy: "Копировать",
    copied: "Скопировано",
    recipient: "Получатель",
    save_qr: "Сохранить QR",
    step1: "Откройте приложение банка и отсканируйте код в разделе QR. Если вы на этом же телефоне, сохраните QR и загрузите его в приложение.",
    step2: "Оплатите ровно {amount} сум. В комментарии укажите код: {code}",
    step3: "Загрузите скриншот чека и нажмите «Я оплатил».",
    receipt: "Чек об оплате (скриншот)",
    pick: "Выбрать фото",
    change: "Другое фото",
    paid_btn: "Я оплатил",
    sending: "Отправляем...",
    need_receipt: "Сначала загрузите скриншот чека.",
    hours: "Подписка активируется после проверки — обычно в течение {hours} ч.",
    hours_generic: "Подписка активируется после проверки оплаты.",
    help: "Если возникла проблема:",
    help_tg: "напишите в Telegram",
    done_title: "Заявка принята",
    done_sub: "Мы проверим оплату и активируем подписку.",
    st_sent: "Чек отправлен",
    st_check: "Проверяется",
    st_active: "Подписка активна",
    sum: "Сумма",
    code: "Код платежа",
    continue: "Продолжить занятия",
    approved_title: "Подписка активна!",
    approved_sub: "Оплата подтверждена. Удачной учёбы!",
    rejected_title: "Платёж не найден",
    rejected_sub: "Мы не смогли подтвердить этот платёж. Если есть вопросы, напишите нам.",
    try_again: "Попробовать снова",
    not_ready_title: "Оплата по QR скоро заработает",
    not_ready_sub: "Пока что для оплаты Humo / Uzcard напишите нам в Telegram или оплатите картой.",
    err_generic: "Произошла ошибка. Попробуйте ещё раз.",
    err_too_many: "У вас слишком много незавершённых платежей. Завершите предыдущий или напишите нам.",
    learner: "Learner", vip: "VIP", monthly: "Ежемесячно", yearly: "Ежегодно",
  },
  en: {
    banner_title: "Humo and Uzcard accepted",
    banner_sub: "Pay in so‘m by QR code. No foreign card needed.",
    or_uzs: "or {amount} so‘m",
    per_month: "/ mo",
    per_year: "/ yr",
    qr_btn: "Humo / Uzcard — pay by QR",
    card_btn: "Pay with Visa / Mastercard",
    footer: "Humo / Uzcard: by QR, in so‘m · Visa / Mastercard, Apple Pay, Google Pay: by card",
    back: "Back to pricing",
    eyebrow: "HUMO · UZCARD · IN SO‘M",
    title: "Pay by QR",
    sub: "Scan the QR code in your bank app and pay the exact amount.",
    plan: "Plan",
    amount: "Amount to pay",
    code_label: "Payment code (write it in the comment)",
    copy: "Copy",
    copied: "Copied",
    recipient: "Recipient",
    save_qr: "Save QR image",
    step1: "Open your bank app and scan the code from its QR section. On this same phone? Save the QR image and load it into the app.",
    step2: "Pay exactly {amount} so‘m. Write the payment code in the comment: {code}",
    step3: "Upload a screenshot of the receipt and tap “I’ve paid”.",
    receipt: "Payment receipt (screenshot)",
    pick: "Choose image",
    change: "Choose another",
    paid_btn: "I’ve paid",
    sending: "Sending...",
    need_receipt: "Upload the receipt screenshot first.",
    hours: "Your plan is activated once the payment is checked — usually within {hours} h.",
    hours_generic: "Your plan is activated once the payment is checked.",
    help: "Having trouble?",
    help_tg: "Message us on Telegram",
    done_title: "Request received",
    done_sub: "We’ll check your payment and activate your plan.",
    st_sent: "Receipt sent",
    st_check: "Being checked",
    st_active: "Plan activated",
    sum: "Amount",
    code: "Payment code",
    continue: "Continue practising",
    approved_title: "Your plan is active!",
    approved_sub: "Payment confirmed. Happy learning!",
    rejected_title: "Payment not found",
    rejected_sub: "We couldn’t confirm this payment. If you have questions, message us.",
    try_again: "Try again",
    not_ready_title: "QR payments are coming soon",
    not_ready_sub: "For now, to pay with Humo / Uzcard, message us on Telegram, or pay by card.",
    err_generic: "Something went wrong. Please try again.",
    err_too_many: "You have too many unfinished payments. Finish the previous one or message us.",
    learner: "Learner", vip: "VIP", monthly: "Monthly", yearly: "Yearly",
  },
};

export function qrT(lang, key, vars) {
  const dict = QR_COPY[lang] || QR_COPY.uz;
  let s = dict[key] ?? QR_COPY.uz[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
  return s;
}
