// Reader-relative SYNONYM tiers — the clue ladder Context Guess runs on.
//
// Exact mirror of definitionTiers.js's idea, with synonyms instead of
// definitions: for one word, the clue shown is a different word depending on
// who is looking at it. Tee's canonical example, `rotten` in "The apple was
// rotten":
//     A2 "bad" → B1 "awful" → B2 "spoiled" → C1 "putrid"
// Same escalation of precision/register at each step, and deliberately no
// syn_a1 — an A1 student reads the support-language translation and that is
// the whole story at that level, exactly as definitionTiers.js has no def_a1.
//
// CONTENT PATH (2026-09-07): pilot set, not a full enrichment batch. The
// definition batch had a head start — english_definition was already on all
// 2,282 rows, so def_a2..def_c1 were a rewrite of existing text. Synonyms
// start from zero, and a four-tier ladder is much less mechanical than a
// definition rewrite: "the most precise uncommon synonym" is a real editorial
// judgement per word, and a wrong rung (a near-synonym that doesn't actually
// fit the sentence) makes the game teach something false. So the ladders below
// are hand-authored, offline, against words verified to exist in the live pool,
// and the game filters its pool to words that have a ladder — the same
// "not enough words for this game yet" degradation Picture Match uses for
// words with no emoji. Full-corpus coverage is a followup batch.
//
// FORWARD-COMPATIBLE: resolution reads VocabularyWord.syn_a2..syn_c1 FIRST and
// only falls back to this module. When the enrichment batch lands, the rows it
// fills start winning automatically with no engine change; a ladder can be
// deleted from here once its rows are covered.
//
// Never generated at play time — no InvokeLLM anywhere in this path.

export const SYN_FIELD = { A2: "syn_a2", B1: "syn_b1", B2: "syn_b2", C1: "syn_c1" };

// word → [A2, B1, B2, C1], authored as a rising precision ladder.
// Tuples rather than objects purely to keep 170 ladders readable.
const LADDER = {
  // ---- states & qualities ----
  rotten: ["bad", "awful", "spoiled", "putrid"],
  old: ["not new", "aged", "elderly", "venerable"],
  big: ["large", "huge", "enormous", "colossal"],
  small: ["little", "tiny", "minute", "diminutive"],
  happy: ["glad", "pleased", "delighted", "elated"],
  sad: ["unhappy", "miserable", "sorrowful", "despondent"],
  angry: ["mad", "furious", "enraged", "livid"],
  afraid: ["scared", "frightened", "terrified", "petrified"],
  tired: ["sleepy", "exhausted", "weary", "fatigued"],
  hungry: ["empty", "starving", "famished", "ravenous"],
  cold: ["cool", "chilly", "freezing", "frigid"],
  hot: ["warm", "boiling", "scorching", "sweltering"],
  wet: ["damp", "soaked", "drenched", "saturated"],
  dry: ["not wet", "dried", "parched", "arid"],
  clean: ["tidy", "spotless", "immaculate", "pristine"],
  dirty: ["messy", "filthy", "grimy", "squalid"],
  loud: ["noisy", "booming", "deafening", "thunderous"],
  quiet: ["silent", "hushed", "faint", "inaudible"],
  fast: ["quick", "rapid", "swift", "expeditious"],
  slow: ["not fast", "sluggish", "unhurried", "languid"],
  strong: ["powerful", "sturdy", "robust", "formidable"],
  weak: ["not strong", "feeble", "frail", "infirm"],
  easy: ["simple", "effortless", "straightforward", "elementary"],
  hard: ["difficult", "tough", "demanding", "arduous"],
  rich: ["wealthy", "well-off", "affluent", "opulent"],
  poor: ["not rich", "broke", "impoverished", "destitute"],
  beautiful: ["pretty", "lovely", "gorgeous", "exquisite"],
  ugly: ["not pretty", "unattractive", "hideous", "grotesque"],
  funny: ["amusing", "comical", "hilarious", "droll"],
  strange: ["odd", "weird", "peculiar", "bizarre"],
  important: ["big", "serious", "significant", "paramount"],
  famous: ["well-known", "celebrated", "renowned", "illustrious"],
  brave: ["bold", "fearless", "courageous", "intrepid"],
  clever: ["smart", "bright", "intelligent", "astute"],
  stupid: ["silly", "foolish", "unwise", "inane"],
  kind: ["nice", "caring", "compassionate", "benevolent"],
  rude: ["not polite", "impolite", "discourteous", "insolent"],
  polite: ["nice", "well-mannered", "courteous", "civil"],
  honest: ["truthful", "sincere", "candid", "forthright"],
  lazy: ["not active", "idle", "inactive", "indolent"],
  busy: ["full", "occupied", "hectic", "frenetic"],
  calm: ["quiet", "relaxed", "composed", "serene"],
  nervous: ["worried", "anxious", "uneasy", "apprehensive"],
  lonely: ["alone", "lonesome", "isolated", "forlorn"],
  proud: ["pleased", "satisfied", "gratified", "exultant"],
  jealous: ["upset", "envious", "resentful", "covetous"],
  shy: ["quiet", "timid", "reserved", "diffident"],
  rare: ["not common", "uncommon", "scarce", "sporadic"],
  common: ["normal", "usual", "widespread", "ubiquitous"],
  new: ["not old", "recent", "modern", "novel"],
  cheap: ["low-priced", "inexpensive", "affordable", "economical"],
  expensive: ["dear", "costly", "pricey", "exorbitant"],
  empty: ["with nothing", "bare", "vacant", "void"],
  full: ["filled", "packed", "crammed", "replete"],
  heavy: ["not light", "weighty", "hefty", "ponderous"],
  light: ["not heavy", "featherlight", "weightless", "gossamer"],
  narrow: ["thin", "tight", "slender", "constricted"],
  wide: ["broad", "spacious", "expansive", "capacious"],
  deep: ["far down", "profound", "bottomless", "abyssal"],
  sharp: ["pointed", "keen", "acute", "incisive"],
  smooth: ["even", "sleek", "glossy", "silken"],
  rough: ["not smooth", "coarse", "jagged", "abrasive"],
  soft: ["not hard", "tender", "supple", "yielding"],
  bright: ["light", "shining", "radiant", "luminous"],
  dark: ["not light", "dim", "gloomy", "murky"],
  safe: ["not dangerous", "secure", "protected", "inviolable"],
  dangerous: ["not safe", "risky", "hazardous", "perilous"],
  sick: ["ill", "unwell", "ailing", "indisposed"],
  healthy: ["well", "fit", "robust", "hale"],
  fresh: ["new", "crisp", "unspoiled", "newly-made"],
  ancient: ["very old", "age-old", "antique", "primordial"],
  huge: ["very big", "massive", "immense", "gargantuan"],
  tiny: ["very small", "minute", "microscopic", "infinitesimal"],
  serious: ["big", "grave", "severe", "weighty"],
  urgent: ["quick", "pressing", "immediate", "exigent"],
  simple: ["easy", "plain", "uncomplicated", "unadorned"],
  complex: ["not simple", "complicated", "intricate", "labyrinthine"],
  perfect: ["very good", "flawless", "faultless", "impeccable"],
  terrible: ["very bad", "awful", "dreadful", "appalling"],
  wonderful: ["very good", "great", "marvellous", "sublime"],
  boring: ["not fun", "dull", "tedious", "soporific"],
  exciting: ["fun", "thrilling", "exhilarating", "electrifying"],
  tasty: ["good", "delicious", "flavourful", "delectable"],
  // ---- actions ----
  begin: ["start", "commence", "initiate", "inaugurate"],
  finish: ["end", "complete", "conclude", "finalize"],
  build: ["make", "construct", "erect", "fabricate"],
  break: ["damage", "smash", "shatter", "fracture"],
  buy: ["get", "purchase", "acquire", "procure"],
  sell: ["trade", "vend", "market", "peddle"],
  keep: ["hold", "retain", "preserve", "conserve"],
  throw: ["toss", "hurl", "fling", "propel"],
  catch: ["grab", "seize", "capture", "apprehend"],
  hide: ["cover", "conceal", "obscure", "camouflage"],
  find: ["see", "discover", "locate", "unearth"],
  lose: ["not find", "misplace", "forfeit", "squander"],
  ask: ["question", "enquire", "request", "solicit"],
  answer: ["reply", "respond", "retort", "rejoin"],
  say: ["tell", "state", "declare", "assert"],
  shout: ["yell", "cry", "bellow", "vociferate"],
  whisper: ["say quietly", "murmur", "mutter", "susurrate"],
  talk: ["speak", "chat", "converse", "discourse"],
  explain: ["tell", "describe", "clarify", "elucidate"],
  argue: ["fight", "dispute", "quarrel", "remonstrate"],
  agree: ["say yes", "accept", "consent", "concur"],
  refuse: ["say no", "reject", "decline", "rebuff"],
  allow: ["let", "permit", "authorize", "sanction"],
  forbid: ["not allow", "ban", "prohibit", "proscribe"],
  help: ["aid", "assist", "support", "succour"],
  save: ["keep", "rescue", "salvage", "redeem"],
  hurt: ["harm", "injure", "wound", "afflict"],
  kill: ["end life", "slay", "murder", "assassinate"],
  fix: ["mend", "repair", "restore", "rectify"],
  destroy: ["ruin", "wreck", "demolish", "obliterate"],
  change: ["make different", "alter", "modify", "transform"],
  grow: ["get bigger", "increase", "expand", "burgeon"],
  shrink: ["get smaller", "decrease", "contract", "diminish"],
  jump: ["hop", "leap", "bound", "vault"],
  run: ["go fast", "race", "sprint", "hurtle"],
  walk: ["go", "stroll", "stride", "amble"],
  climb: ["go up", "ascend", "scale", "clamber"],
  fall: ["drop", "tumble", "plunge", "plummet"],
  push: ["move", "shove", "thrust", "propel"],
  pull: ["move", "drag", "haul", "tow"],
  carry: ["take", "bear", "transport", "convey"],
  hold: ["keep", "grip", "grasp", "clutch"],
  hit: ["strike", "knock", "smack", "pummel"],
  cut: ["slice", "sever", "slit", "incise"],
  choose: ["pick", "select", "opt for", "designate"],
  decide: ["choose", "settle", "determine", "resolve"],
  try: ["attempt", "strive", "endeavour", "essay"],
  need: ["want", "require", "necessitate", "warrant"],
  hope: ["want", "wish", "expect", "aspire"],
  worry: ["think", "fret", "agonize", "brood"],
  enjoy: ["like", "love", "relish", "savour"],
  hate: ["dislike", "detest", "loathe", "abhor"],
  laugh: ["smile", "giggle", "chuckle", "guffaw"],
  cry: ["weep", "sob", "wail", "lament"],
  sleep: ["rest", "doze", "slumber", "repose"],
  wake: ["get up", "rouse", "awaken", "stir"],
  eat: ["have", "consume", "devour", "ingest"],
  drink: ["have", "sip", "swallow", "imbibe"],
  cook: ["make", "prepare", "roast", "sauté"],
  wash: ["clean", "rinse", "scrub", "cleanse"],
  wear: ["have on", "dress in", "don", "sport"],
  show: ["let see", "display", "reveal", "exhibit"],
  hidden: ["not seen", "covered", "concealed", "clandestine"],
  watch: ["look at", "observe", "view", "scrutinize"],
  look: ["see", "glance", "gaze", "peruse"],
  listen: ["hear", "attend", "heed", "hearken"],
  learn: ["study", "master", "grasp", "assimilate"],
  teach: ["show", "train", "instruct", "edify"],
  remember: ["not forget", "recall", "recollect", "reminisce"],
  forget: ["not remember", "overlook", "neglect", "disremember"],
  think: ["believe", "consider", "reflect", "ruminate"],
  understand: ["get", "grasp", "comprehend", "fathom"],
  guess: ["think", "suppose", "estimate", "surmise"],
  believe: ["think", "trust", "accept", "credit"],
  doubt: ["not believe", "question", "mistrust", "disbelieve"],
  promise: ["say", "pledge", "vow", "covenant"],
  warn: ["tell", "alert", "caution", "admonish"],
  praise: ["say good things", "compliment", "commend", "extol"],
  blame: ["fault", "accuse", "reproach", "censure"],
  travel: ["go", "journey", "voyage", "traverse"],
  arrive: ["get there", "reach", "land", "alight"],
  leave: ["go", "depart", "exit", "vacate"],
  stay: ["remain", "wait", "linger", "abide"],
  meet: ["see", "encounter", "greet", "rendezvous"],
  join: ["put together", "connect", "unite", "amalgamate"],
  separate: ["split", "divide", "detach", "sever"],
  share: ["give", "divide", "distribute", "apportion"],
  give: ["hand", "offer", "present", "bestow"],
  take: ["get", "grab", "seize", "appropriate"],
  steal: ["take", "rob", "thieve", "pilfer"],
  pay: ["give money", "settle", "remit", "recompense"],
  earn: ["get", "make", "gain", "accrue"],
  spend: ["use", "pay out", "expend", "disburse"],
  waste: ["lose", "misuse", "squander", "dissipate"],
  count: ["add up", "tally", "calculate", "enumerate"],
  measure: ["check", "gauge", "quantify", "calibrate"],
  // ---- things & ideas ----
  job: ["work", "post", "occupation", "vocation"],
  house: ["home", "building", "residence", "dwelling"],
  road: ["street", "route", "highway", "thoroughfare"],
  shop: ["store", "outlet", "retailer", "emporium"],
  doctor: ["medic", "physician", "practitioner", "clinician"],
  child: ["kid", "youngster", "youth", "juvenile"],
  friend: ["mate", "buddy", "companion", "confidant"],
  enemy: ["rival", "opponent", "adversary", "nemesis"],
  problem: ["trouble", "issue", "difficulty", "predicament"],
  idea: ["thought", "plan", "concept", "notion"],
  plan: ["idea", "scheme", "strategy", "blueprint"],
  reason: ["why", "cause", "motive", "rationale"],
  result: ["end", "outcome", "consequence", "upshot"],
  chance: ["luck", "opportunity", "possibility", "contingency"],
  danger: ["risk", "threat", "hazard", "peril"],
  mistake: ["error", "slip", "blunder", "oversight"],
  story: ["tale", "account", "narrative", "chronicle"],
  noise: ["sound", "racket", "din", "cacophony"],
  smell: ["scent", "odour", "aroma", "fragrance"],
  pain: ["hurt", "ache", "agony", "anguish"],
  fear: ["worry", "fright", "dread", "trepidation"],
  anger: ["upset", "rage", "fury", "wrath"],
  joy: ["happiness", "delight", "elation", "jubilation"],
  money: ["cash", "funds", "capital", "assets"],
  price: ["cost", "charge", "fee", "valuation"],
  gift: ["present", "donation", "offering", "bequest"],
  rule: ["law", "regulation", "principle", "statute"],
  fight: ["battle", "conflict", "clash", "altercation"],
  speech: ["talk", "address", "lecture", "oration"],
  trip: ["travel", "journey", "voyage", "expedition"],
  home: ["house", "residence", "abode", "domicile"],
  food: ["meal", "diet", "nourishment", "sustenance"],
  garbage: ["rubbish", "waste", "refuse", "detritus"],

  // ---- verified against the live pool (2026-09-07) ----
  // Everything above was authored from general B1 vocabulary and only ~55 of
  // those keys turned out to exist in the live VocabularyWord table; they are
  // kept because an unused key costs nothing and the corpus grows. Everything
  // below was authored against the actual A2 / B1 / B2 / C1 word lists read out
  // of the table, which is where this pilot's real coverage comes from.
  able: ["can do it", "capable", "competent", "adept"],
  abroad: ["in another country", "overseas", "far afield", "extraterritorial"],
  amazing: ["very good", "incredible", "astonishing", "stupefying"],
  ashamed: ["sorry", "embarrassed", "guilty", "mortified"],
  attractive: ["pretty", "good-looking", "appealing", "alluring"],
  brilliant: ["very good", "excellent", "outstanding", "dazzling"],
  careful: ["slow", "cautious", "attentive", "meticulous"],
  cheerful: ["happy", "upbeat", "jolly", "buoyant"],
  clear: ["easy to see", "plain", "obvious", "unambiguous"],
  comfortable: ["nice", "cosy", "relaxing", "commodious"],
  confuse: ["mix up", "muddle", "bewilder", "disorient"],
  continue: ["go on", "carry on", "persist", "perpetuate"],
  convenient: ["easy", "handy", "practical", "expedient"],
  correct: ["right", "accurate", "precise", "unerring"],
  crowded: ["full", "packed", "congested", "teeming"],
  disgusting: ["very bad", "horrible", "revolting", "repugnant"],
  dishonest: ["not honest", "untruthful", "deceitful", "duplicitous"],
  distant: ["far", "faraway", "remote", "outlying"],
  entire: ["all", "whole", "complete", "unabridged"],
  fail: ["not pass", "lose", "flop", "founder"],
  fake: ["not real", "false", "counterfeit", "spurious"],
  freezing: ["very cold", "icy", "frozen", "glacial"],
  frightened: ["scared", "afraid", "terrified", "aghast"],
  glad: ["happy", "pleased", "delighted", "gratified"],
  grateful: ["happy", "thankful", "appreciative", "indebted"],
  happiness: ["good feeling", "joy", "contentment", "felicity"],
  horrible: ["very bad", "awful", "dreadful", "ghastly"],
  ill: ["sick", "unwell", "ailing", "indisposed"],
  impolite: ["rude", "bad-mannered", "discourteous", "uncouth"],
  incorrect: ["wrong", "false", "inaccurate", "erroneous"],
  intelligent: ["clever", "smart", "bright", "sagacious"],
  loose: ["not tight", "slack", "baggy", "unsecured"],
  loss: ["losing", "defeat", "deficit", "forfeiture"],
  luck: ["chance", "fortune", "good fortune", "serendipity"],
  lucky: ["happy", "fortunate", "favoured", "auspicious"],
  melt: ["turn to water", "thaw", "liquefy", "dissolve"],
  merry: ["happy", "cheerful", "jolly", "mirthful"],
  naughty: ["bad", "badly behaved", "mischievous", "impish"],
  noisy: ["loud", "rowdy", "clamorous", "raucous"],
  notice: ["see", "spot", "observe", "discern"],
  peace: ["quiet", "calm", "harmony", "tranquillity"],
  pleasure: ["good feeling", "enjoyment", "delight", "gratification"],
  popular: ["liked", "well-liked", "in demand", "sought-after"],
  positive: ["good", "hopeful", "optimistic", "affirmative"],
  prefer: ["like more", "choose", "favour", "incline toward"],
  punishment: ["what you get for bad behaviour", "penalty", "discipline", "retribution"],
  reduce: ["make smaller", "cut", "decrease", "curtail"],
  relax: ["rest", "unwind", "calm down", "decompress"],
  rob: ["take", "steal from", "hold up", "plunder"],
  salty: ["like salt", "briny", "saline", "brackish"],
  scare: ["frighten", "alarm", "terrify", "unnerve"],
  secret: ["hidden", "private", "confidential", "clandestine"],
  silent: ["quiet", "soundless", "hushed", "noiseless"],
  slim: ["thin", "slender", "lean", "svelte"],
  slippery: ["not safe to walk on", "slick", "greasy", "glassy"],
  sore: ["hurting", "painful", "tender", "inflamed"],
  sour: ["not sweet", "sharp", "tart", "acidic"],
  spicy: ["hot", "peppery", "pungent", "piquant"],
  spoil: ["ruin", "damage", "wreck", "vitiate"],
  stranger: ["someone you don't know", "unknown person", "outsider", "unfamiliar figure"],
  tidy: ["clean", "neat", "orderly", "immaculate"],
  tight: ["not loose", "close-fitting", "snug", "constricting"],
  useful: ["good to have", "helpful", "practical", "invaluable"],
  wild: ["not tame", "untamed", "feral", "unbridled"],
  // B1
  abandon: ["leave", "give up", "desert", "forsake"],
  abnormal: ["not normal", "unusual", "irregular", "aberrant"],
  accurate: ["right", "exact", "precise", "unerring"],
  ache: ["hurt", "pain", "throb", "smart"],
  afford: ["have money for", "manage", "meet the cost of", "bear the expense of"],
  alert: ["awake", "watchful", "attentive", "vigilant"],
  alter: ["change", "adjust", "modify", "transmute"],
  amusing: ["funny", "entertaining", "comical", "diverting"],
  annoy: ["upset", "bother", "irritate", "vex"],
  awkward: ["strange", "uncomfortable", "clumsy", "gauche"],
  bitter: ["not sweet", "sharp", "acrid", "astringent"],
  boast: ["talk big", "brag", "show off", "crow"],
  careless: ["not careful", "sloppy", "negligent", "slapdash"],
  cause: ["make happen", "produce", "bring about", "engender"],
  cheat: ["not play fair", "trick", "deceive", "defraud"],
  chew: ["bite", "munch", "grind", "masticate"],
  complicated: ["not easy", "complex", "intricate", "convoluted"],
  confess: ["tell", "admit", "own up", "avow"],
  conquer: ["win", "beat", "defeat", "subjugate"],
  consider: ["think about", "weigh up", "contemplate", "deliberate on"],
  crack: ["break", "split", "fracture", "fissure"],
  crash: ["hit", "collide", "smash", "careen into"],
  cure: ["make better", "heal", "remedy", "restore to health"],
  curse: ["swear", "damn", "condemn", "imprecate"],
  damp: ["a bit wet", "moist", "clammy", "dank"],
  decay: ["go bad", "rot", "decompose", "moulder"],
  deceive: ["trick", "mislead", "delude", "dupe"],
  decent: ["good enough", "respectable", "proper", "creditable"],
  decrease: ["get smaller", "drop", "diminish", "abate"],
  defeat: ["beat", "overcome", "vanquish", "rout"],
  delay: ["make late", "hold up", "postpone", "protract"],
  deliver: ["bring", "hand over", "convey", "consign"],
  descend: ["go down", "come down", "drop", "plummet"],
  dim: ["not bright", "faint", "murky", "crepuscular"],
  dizzy: ["not steady", "light-headed", "giddy", "vertiginous"],
  drag: ["pull", "haul", "tug", "lug"],
  exact: ["right", "precise", "specific", "unequivocal"],
  fade: ["get lighter", "dim", "wane", "etiolate"],
  faint: ["weak", "slight", "feeble", "imperceptible"],
  flexible: ["easy to bend", "bendy", "pliable", "malleable"],
  flood: ["too much water", "overflow", "deluge", "inundation"],
  fond: ["liking", "keen", "affectionate", "enamoured"],
  generous: ["giving", "kind", "unselfish", "munificent"],
  glance: ["quick look", "peek", "glimpse", "cursory look"],
  hatred: ["strong dislike", "hate", "loathing", "enmity"],
  hesitate: ["wait", "pause", "waver", "vacillate"],
  humble: ["not proud", "modest", "unassuming", "self-effacing"],
  illegal: ["not allowed", "against the law", "unlawful", "illicit"],
  imitate: ["copy", "mimic", "impersonate", "emulate"],
  impatient: ["not patient", "restless", "eager", "fretful"],
  injure: ["hurt", "wound", "harm", "maim"],
  insult: ["say something rude", "offend", "abuse", "affront"],
  interrupt: ["stop", "cut in", "break in on", "disrupt"],
  invade: ["attack", "enter by force", "occupy", "encroach on"],
  invent: ["make", "create", "devise", "originate"],
  irritate: ["annoy", "bother", "aggravate", "nettle"],
  kidnap: ["take away", "snatch", "abduct", "spirit away"],
  kneel: ["go down on your knees", "crouch", "genuflect", "kowtow"],
  lack: ["not have", "miss", "be short of", "want for"],
  leak: ["let water out", "drip", "seep", "exude"],
  lean: ["bend", "tilt", "incline", "cant"],
  liar: ["someone who lies", "fibber", "deceiver", "perjurer"],
  lively: ["full of energy", "active", "spirited", "vivacious"],
  loyal: ["true", "faithful", "devoted", "steadfast"],
  luxury: ["something expensive", "comfort", "extravagance", "opulence"],
  massive: ["very big", "huge", "immense", "prodigious"],
  mild: ["not strong", "gentle", "moderate", "temperate"],
  miserable: ["very sad", "unhappy", "wretched", "disconsolate"],
  modest: ["not proud", "humble", "unpretentious", "demure"],
  nod: ["move your head", "bob", "incline the head", "acquiesce"],
  offend: ["upset", "insult", "hurt", "affront"],
  ordinary: ["normal", "usual", "unremarkable", "prosaic"],
  painful: ["hurting", "sore", "agonizing", "excruciating"],
  panic: ["get scared", "lose control", "be terrified", "be seized by terror"],
  patience: ["waiting calmly", "calm", "tolerance", "forbearance"],
  precious: ["very special", "valuable", "treasured", "priceless"],
  pretend: ["act", "make believe", "feign", "dissemble"],
  punish: ["give trouble to", "penalize", "discipline", "castigate"],
  pursue: ["follow", "chase", "go after", "hound"],
  recover: ["get better", "heal", "recuperate", "convalesce"],
  ridiculous: ["very silly", "absurd", "laughable", "preposterous"],
  ripe: ["ready to eat", "mature", "mellow", "fully developed"],
  rot: ["go bad", "decay", "spoil", "putrefy"],
  ruin: ["destroy", "wreck", "spoil", "lay waste to"],
  scatter: ["throw around", "spread", "disperse", "strew"],
  scratch: ["mark", "scrape", "graze", "abrade"],
  shallow: ["not deep", "low", "superficial", "skin-deep"],
  silence: ["no sound", "quiet", "stillness", "hush"],
  sudden: ["quick", "abrupt", "unexpected", "precipitate"],
  suspicious: ["not trusting", "doubtful", "wary", "dubious"],
  swear: ["say bad words", "curse", "blaspheme", "imprecate"],
  swift: ["fast", "quick", "rapid", "fleet"],
  tempt: ["make someone want", "attract", "entice", "beguile"],
  theft: ["stealing", "robbery", "larceny", "pilfering"],
  thrill: ["excitement", "rush", "exhilaration", "frisson"],
  trim: ["cut", "clip", "prune", "pare"],
  upset: ["sad", "unhappy", "distressed", "perturbed"],
  useless: ["no good", "pointless", "worthless", "futile"],
  vanish: ["go away", "disappear", "fade out", "evanesce"],
  vary: ["change", "differ", "fluctuate", "diverge"],
  wander: ["walk around", "roam", "stroll", "meander"],
  weird: ["strange", "odd", "bizarre", "outlandish"],
  wonder: ["ask yourself", "think", "speculate", "muse"],
  wrinkle: ["line", "crease", "fold", "furrow"],
  // B2
  accuse: ["blame", "charge", "denounce", "indict"],
  achieve: ["do", "reach", "accomplish", "attain"],
  acknowledge: ["accept", "admit", "recognize", "concede"],
  acquire: ["get", "obtain", "gain", "procure"],
  admire: ["like a lot", "respect", "look up to", "revere"],
  admit: ["say it's true", "confess", "acknowledge", "avow"],
  ambitious: ["wanting a lot", "driven", "aspiring", "enterprising"],
  anticipate: ["expect", "foresee", "predict", "presage"],
  artificial: ["not real", "man-made", "synthetic", "simulated"],
  assemble: ["put together", "gather", "construct", "convene"],
  assist: ["help", "aid", "support", "abet"],
  assume: ["think", "suppose", "presume", "postulate"],
  bald: ["with no hair", "hairless", "shaven", "glabrous"],
  bargain: ["good price", "deal", "discount", "steal"],
  betray: ["let down", "double-cross", "be disloyal to", "sell out"],
  brag: ["talk big", "boast", "show off", "crow"],
  burst: ["break open", "pop", "explode", "rupture"],
  cautious: ["careful", "wary", "guarded", "circumspect"],
  choke: ["can't breathe", "gag", "suffocate", "asphyxiate"],
  claim: ["say", "state", "assert", "contend"],
  commit: ["do", "carry out", "perpetrate", "perform"],
  compensate: ["pay back", "make up for", "reimburse", "indemnify"],
  compliment: ["say something nice", "praise", "commend", "flatter"],
  conflict: ["fight", "clash", "dispute", "discord"],
  confusion: ["not understanding", "mix-up", "disorder", "bewilderment"],
  convince: ["make someone believe", "persuade", "win over", "prevail upon"],
  courage: ["being brave", "bravery", "nerve", "valour"],
  crucial: ["very important", "vital", "essential", "pivotal"],
  decline: ["go down", "drop", "decrease", "dwindle"],
  defend: ["protect", "guard", "shield", "safeguard"],
  define: ["explain", "describe", "specify", "delineate"],
  deliberate: ["on purpose", "intended", "intentional", "premeditated"],
  delicate: ["easy to break", "fragile", "fine", "frangible"],
  demand: ["ask strongly", "insist on", "require", "exact"],
  deny: ["say no", "refuse", "reject", "repudiate"],
  depart: ["leave", "go", "set off", "take one's leave"],
  deserve: ["should get", "earn", "merit", "warrant"],
  desperate: ["very worried", "hopeless", "frantic", "despairing"],
  diligent: ["hard-working", "careful", "conscientious", "assiduous"],
  discourage: ["make someone stop", "put off", "dishearten", "dissuade"],
  disgrace: ["shame", "dishonour", "embarrassment", "ignominy"],
  disguise: ["cover", "hide", "mask", "camouflage"],
  dismiss: ["send away", "let go", "reject", "repudiate"],
  dispute: ["argue", "disagree", "contest", "contend"],
  dissolve: ["mix into liquid", "melt", "break down", "liquefy"],
  distribute: ["give out", "hand out", "share out", "disseminate"],
  drift: ["move slowly", "float", "wander", "meander"],
  drown: ["die in water", "sink", "go under", "be submerged"],
  efficient: ["quick and good", "effective", "productive", "streamlined"],
  elegant: ["beautiful", "stylish", "graceful", "refined"],
  embrace: ["hug", "hold", "clasp", "enfold"],
  emerge: ["come out", "appear", "surface", "materialize"],
  encourage: ["help someone try", "support", "motivate", "galvanize"],
  enforce: ["make people follow", "apply", "impose", "administer"],
  enhance: ["make better", "improve", "boost", "augment"],
  era: ["time", "period", "age", "epoch"],
  establish: ["start", "set up", "found", "institute"],
  estimate: ["guess", "work out", "calculate", "approximate"],
  evaluate: ["judge", "assess", "appraise", "gauge"],
  evolve: ["change slowly", "develop", "progress", "metamorphose"],
  exaggerate: ["say too much", "overstate", "embellish", "hyperbolize"],
  exceed: ["go over", "pass", "surpass", "outstrip"],
  exotic: ["from far away", "unusual", "foreign", "outlandish"],
  expand: ["get bigger", "grow", "increase", "dilate"],
  fame: ["being famous", "success", "renown", "celebrity"],
  fascinating: ["very interesting", "gripping", "captivating", "riveting"],
  fatal: ["killing", "deadly", "lethal", "mortal"],
  fierce: ["very angry", "wild", "aggressive", "ferocious"],
  flee: ["run away", "escape", "take off", "abscond"],
  glow: ["shine", "gleam", "radiate", "luminesce"],
  gossip: ["talk about others", "rumour", "chatter", "hearsay"],
  grasp: ["hold", "grip", "clutch", "apprehend"],
  greed: ["wanting too much", "hunger", "avarice", "rapacity"],
  grief: ["deep sadness", "sorrow", "mourning", "desolation"],
  grind: ["crush", "mill", "pulverize", "comminute"],
  grip: ["hold", "grasp", "clutch", "clench"],
  halt: ["stop", "end", "cease", "arrest"],
  harsh: ["hard", "severe", "cruel", "draconian"],
  hollow: ["empty inside", "unfilled", "cavernous", "vacuous"],
  humid: ["wet in the air", "damp", "muggy", "sultry"],
  ideal: ["best", "perfect", "optimal", "quintessential"],
  identical: ["exactly the same", "matching", "indistinguishable", "selfsame"],
  ignore: ["not look at", "overlook", "disregard", "spurn"],
  immense: ["very big", "huge", "vast", "prodigious"],
  impact: ["effect", "result", "influence", "repercussion"],
  impress: ["make someone like it", "amaze", "inspire", "dazzle"],
  insist: ["say again strongly", "demand", "maintain", "importune"],
  instruct: ["tell", "teach", "direct", "enjoin"],
  investigate: ["look into", "examine", "inquire into", "scrutinize"],
  isolate: ["keep apart", "separate", "cut off", "sequester"],
  jealousy: ["bad feeling about others", "envy", "resentment", "covetousness"],
  leap: ["jump", "spring", "bound", "vault"],
  liberty: ["freedom", "independence", "free will", "autonomy"],
  locate: ["find", "spot", "pinpoint", "ascertain"],
  magnificent: ["very beautiful", "splendid", "majestic", "resplendent"],
  maintain: ["keep", "look after", "preserve", "sustain"],
  mature: ["grown up", "adult", "developed", "seasoned"],
  memorize: ["learn", "remember", "commit to memory", "learn by rote"],
  mercy: ["kindness", "pity", "forgiveness", "clemency"],
  mighty: ["very strong", "powerful", "formidable", "puissant"],
  migrate: ["move", "travel", "relocate", "transmigrate"],
  mock: ["laugh at", "tease", "ridicule", "deride"],
  modify: ["change", "adjust", "alter", "amend"],
  neglect: ["not look after", "ignore", "overlook", "forsake"],
  noble: ["very good", "honourable", "high-minded", "magnanimous"],
  numerous: ["many", "lots of", "plentiful", "myriad"],
  obstacle: ["problem", "barrier", "hurdle", "impediment"],
  operate: ["work", "run", "manage", "administer"],
  overlook: ["not see", "miss", "disregard", "fail to note"],
  persist: ["keep going", "continue", "persevere", "endure"],
  persuade: ["make someone agree", "convince", "win over", "prevail upon"],
  pity: ["feeling sorry", "sympathy", "compassion", "commiseration"],
  playful: ["fun", "lively", "cheeky", "impish"],
  portray: ["show", "describe", "depict", "render"],
  postpone: ["do it later", "delay", "put off", "defer"],
  preserve: ["keep", "save", "protect", "conserve"],
  previous: ["before", "earlier", "prior", "antecedent"],
  promote: ["push", "support", "advance", "champion"],
  prosper: ["do well", "succeed", "thrive", "flourish"],
  protest: ["complain", "object", "demonstrate", "remonstrate"],
  purchase: ["buy", "get", "acquire", "procure"],
  random: ["with no plan", "chance", "arbitrary", "haphazard"],
  rapid: ["fast", "quick", "swift", "expeditious"],
  rebel: ["fight back", "resist", "revolt", "mutiny"],
  recognize: ["know", "identify", "place", "discern"],
  refer: ["talk about", "mention", "allude", "advert"],
  regret: ["feel sorry", "wish otherwise", "rue", "lament"],
  require: ["need", "want", "demand", "necessitate"],
  resign: ["leave a job", "quit", "step down", "relinquish office"],
  resolve: ["fix", "settle", "sort out", "reconcile"],
  retire: ["stop working", "step down", "leave work", "withdraw from service"],
  retreat: ["go back", "pull back", "withdraw", "fall back"],
  rotate: ["turn", "spin", "revolve", "gyrate"],
  scold: ["tell off", "shout at", "reprimand", "berate"],
  scrape: ["rub", "scratch", "graze", "abrade"],
  seldom: ["not often", "rarely", "infrequently", "hardly ever"],
  select: ["choose", "pick", "opt for", "single out"],
  shame: ["bad feeling", "guilt", "embarrassment", "mortification"],
  shatter: ["break", "smash", "splinter", "pulverize"],
  sigh: ["breathe out", "gasp", "exhale", "heave a breath"],
  simplify: ["make easier", "clarify", "streamline", "distil"],
  slam: ["shut hard", "bang", "crash shut", "slam to"],
  slap: ["hit", "smack", "strike", "cuff"],
  slight: ["small", "little", "minor", "negligible"],
  smash: ["break", "shatter", "crush", "demolish"],
  snap: ["break", "crack", "split", "sever"],
  snatch: ["take fast", "grab", "seize", "wrest"],
  sneak: ["go quietly", "slip", "creep", "steal"],
  soak: ["make very wet", "wet through", "drench", "saturate"],
  sole: ["only", "single", "exclusive", "unaccompanied"],
  spark: ["small light", "flash", "flicker", "scintilla"],
  sparkle: ["shine", "glitter", "twinkle", "coruscate"],
  stale: ["not fresh", "old", "dried out", "musty"],
  startle: ["surprise", "shock", "alarm", "discompose"],
  starve: ["have no food", "go hungry", "be famished", "waste away"],
  steer: ["drive", "guide", "direct", "navigate"],
  stiff: ["hard to bend", "rigid", "inflexible", "unyielding"],
  strain: ["push too hard", "stress", "overwork", "overtax"],
  stubborn: ["not changing", "difficult", "obstinate", "intransigent"],
  stumble: ["nearly fall", "trip", "falter", "lurch"],
  // C1
  absolute: ["complete", "total", "utter", "unqualified"],
  cease: ["stop", "end", "halt", "desist"],
  chaos: ["big mess", "disorder", "confusion", "pandemonium"],
  cherish: ["love", "treasure", "hold dear", "venerate"],
  conceal: ["hide", "cover up", "keep secret", "camouflage"],
  concede: ["accept", "admit", "acknowledge", "grant"],
  condemn: ["say it's wrong", "criticize", "denounce", "censure"],
  confine: ["keep in", "limit", "restrict", "immure"],
  confront: ["face", "meet", "challenge", "accost"],
  consent: ["say yes", "agree", "permit", "acquiesce"],
  crumble: ["break apart", "fall apart", "disintegrate", "moulder"],
  cultivate: ["grow", "farm", "develop", "foster"],
  cunning: ["clever", "sly", "crafty", "wily"],
  defy: ["not obey", "resist", "disobey", "flout"],
  destiny: ["future", "fate", "fortune", "predestination"],
  devastate: ["destroy", "ruin", "wreck", "lay waste to"],
  diverse: ["different", "varied", "wide-ranging", "heterogeneous"],
  dominant: ["strongest", "leading", "controlling", "preeminent"],
  dread: ["fear", "worry about", "be afraid of", "anticipate with horror"],
  endure: ["put up with", "bear", "withstand", "abide"],
  evident: ["easy to see", "clear", "obvious", "manifest"],
  extinguish: ["put out", "stop", "quench", "snuff out"],
  famine: ["no food", "hunger", "starvation", "dearth"],
  feeble: ["weak", "frail", "faint", "infirm"],
  foresee: ["know before", "expect", "predict", "prognosticate"],
  gaze: ["look", "stare", "watch closely", "contemplate"],
  glimpse: ["quick look", "peek", "brief sight", "fleeting view"],
  gratitude: ["thanks", "thankfulness", "appreciation", "indebtedness"],
  hinder: ["stop", "slow down", "obstruct", "impede"],
  idle: ["not working", "doing nothing", "inactive", "indolent"],
  ignorant: ["not knowing", "unaware", "uninformed", "unenlightened"],
  illusion: ["not real", "trick", "false idea", "mirage"],
  immoral: ["wrong", "bad", "unethical", "iniquitous"],
  inquire: ["ask", "question", "enquire", "make inquiries"],
  linger: ["stay", "wait", "remain", "tarry"],
  lure: ["pull in", "attract", "entice", "beguile"],
  majestic: ["very beautiful", "grand", "magnificent", "regal"],
  merit: ["worth", "value", "quality", "excellence"],
  misery: ["being very sad", "unhappiness", "suffering", "wretchedness"],
  mutual: ["shared", "joint", "reciprocal", "requited"],
  nurture: ["look after", "raise", "care for", "cultivate"],
  oblige: ["make someone do", "force", "require", "compel"],
  obtain: ["get", "receive", "acquire", "procure"],
  perish: ["die", "be lost", "pass away", "expire"],
  plead: ["ask", "beg", "appeal", "entreat"],
  ponder: ["think about", "consider", "reflect on", "ruminate on"],
  poverty: ["being poor", "hardship", "need", "destitution"],
  presume: ["think", "suppose", "assume", "postulate"],
  profound: ["very deep", "serious", "far-reaching", "abstruse"],
  quarrel: ["argue", "fight", "dispute", "altercate"],
  rage: ["anger", "fury", "temper", "wrath"],
  reluctant: ["not wanting to", "unwilling", "hesitant", "disinclined"],
  retain: ["keep", "hold", "hold on to", "conserve"],
  retrieve: ["get back", "fetch", "recover", "reclaim"],
  revenge: ["getting back", "payback", "retaliation", "vengeance"],
  ridicule: ["laugh at", "mock", "make fun of", "deride"],
  sacrifice: ["give up", "surrender", "forgo", "relinquish"],
  seize: ["take", "grab", "capture", "commandeer"],
  sheer: ["complete", "total", "pure", "unmitigated"],
  sly: ["clever", "sneaky", "crafty", "furtive"],
  soar: ["go up", "fly high", "climb", "ascend steeply"],
  sorrow: ["sadness", "unhappiness", "grief", "melancholy"],
  stagger: ["walk badly", "stumble", "sway", "totter"],
  stern: ["serious", "strict", "severe", "austere"],
  subtle: ["hard to notice", "slight", "understated", "nuanced"],
  summon: ["call", "send for", "call in", "convoke"],
  sympathy: ["understanding", "kindness", "compassion", "commiseration"],
  tender: ["soft", "gentle", "loving", "solicitous"],
  timid: ["shy", "nervous", "fearful", "diffident"],
  torment: ["hurt", "trouble", "torture", "afflict"],
  tremendous: ["very big", "huge", "enormous", "stupendous"],
  trivial: ["not important", "small", "minor", "inconsequential"],
  vain: ["proud", "self-loving", "conceited", "narcissistic"],
  vivid: ["very clear", "bright", "striking", "graphic"],
  wicked: ["very bad", "evil", "immoral", "nefarious"],
  withdraw: ["take out", "pull out", "remove", "retract"],
  yield: ["give", "produce", "give way", "capitulate"],
};

const clean = (v) => (typeof v === "string" && v.trim() ? v.trim() : "");

const TIER_INDEX = { A2: 0, B1: 1, B2: 2, C1: 3 };

function ladderFor(word) {
  const key = String(word || "").trim().toLowerCase();
  const l = LADDER[key];
  if (!l || !clean(l[0])) return null;
  return l;
}

// Starter and A1 read the support-language translation, never a synonym —
// the same rule definitionTiers.js encodes by having no def_a1.
export function usesTranslationClue(level) {
  return level === "Starter" || level === "A1";
}

// The English synonym clue for a student at `studentLevel`. Entity field wins,
// pilot ladder is the fallback, and a tier with neither resolves DOWN the
// ladder (a C1 student on a word with only an A2 rung still gets a usable
// clue) rather than returning nothing.
export function synonymForLevel(word, studentLevel) {
  const order = ["C1", "B2", "B1", "A2"];
  const start = Math.max(0, order.indexOf(studentLevel in TIER_INDEX ? studentLevel : "A2"));
  const chain = order.slice(start);
  for (const tier of chain) {
    const fromEntity = clean(word?.[SYN_FIELD[tier]]);
    if (fromEntity) return fromEntity;
  }
  const l = ladderFor(word?.english);
  if (!l) return "";
  for (const tier of chain) {
    const v = clean(l[TIER_INDEX[tier]]);
    if (v) return v;
  }
  return "";
}

// The support-language translation shown at Starter/A1 (and as the optional
// help reveal higher up). Starter/A1 always get the support language even when
// the interface is English — an English-only beginner card would have no
// anchor at all.
export function translationClue(word, lang) {
  if (lang === "ru") return clean(word?.russian) || clean(word?.uzbek);
  if (lang === "uz") return clean(word?.uzbek) || clean(word?.russian);
  return clean(word?.uzbek) || clean(word?.russian);
}

// The clue a given student sees for a given word — "" when this word cannot be
// played at this level, which is what the pool filter keys off.
export function clueForLevel(word, studentLevel, lang) {
  return usesTranslationClue(studentLevel)
    ? translationClue(word, lang)
    : synonymForLevel(word, studentLevel);
}

// Words playable at this level: a usable sentence AND a clue. The sentence has
// to actually contain the word, otherwise "read the word in context" has no
// context — 2,242 of 2,282 rows qualify.
export function playableWords(words = [], studentLevel, lang) {
  return words.filter((w) => {
    const en = clean(w?.english);
    const sentence = clean(w?.example_en);
    if (!en || !sentence) return false;
    if (!sentence.toLowerCase().includes(en.toLowerCase().split(" ")[0])) return false;
    return !!clueForLevel(w, studentLevel, lang);
  });
}

// ---------------------------------------------------------------------------
// Synonym Sprint's resolution (2026-09-07). Same ladder, one rule different:
// Tee's spec pairs A1 with A2 at the simplest, "less nuanced" tier, so
// Starter/A1 fall THROUGH to the A2 rung instead of reading a translation the
// way Context Guess has them do. Kept here rather than in the game file so
// tier resolution stays single-sourced.
export function sprintSynonymForLevel(word, studentLevel) {
  return synonymForLevel(word, usesTranslationClue(studentLevel) ? "A2" : studentLevel);
}

// Words playable in a word-only synonym round: a headword plus a synonym at
// (or below) the student's tier. Deliberately NO sentence requirement — the
// word is shown on its own, unlike playableWords() above.
export function synonymPlayableWords(words = [], studentLevel) {
  return words.filter((w) => clean(w?.english) && !!sprintSynonymForLevel(w, studentLevel));
}

// Diagnostics only — how many rows of a pool have pilot synonym coverage.
export function synonymCoverage(words = []) {
  return words.filter((w) => !!synonymForLevel(w, "A2")).length;
}