import { useCallback } from "react";
import { useAppLang } from "@/hooks/useAppLang";

// Learner Skill Map strings. Taxonomy (locked 2026-09-30): the ONLY percentage
// is Correctness (current accuracy on server-checked answers). Progress is
// cells (○◐●◆, not shown until criteria exist), Mastery is never shown as a %,
// and rounds played are activity telemetry, shown as plain text only.
// Node labels fall back to the taxonomy's English label when missing.
const UI = {
  en: { coreTitle: "Your English", coreSub: "Skill map", systems: "Language systems", use: "Language use", tapArea: "Tap an area to open its skills", tapSkill: "Tap a skill to see its details", soon: "Coming soon", notExplored: "Not explored yet", st_verified: "Answers checked", st_activity: "Practised · not checked yet", correctness: "Correctness", basedOn: "from {n} checked rounds", basedOn_one: "from 1 checked round", checkedToday: "last checked today", checkedDaysAgo: "last checked {n} days ago", unverified: "{n} rounds played · not checked yet", unverifiedHint: "These answers were not checked by VIRORA, so they don't count toward correctness.", explainPct: "Correctness = the share of your checked answers that are right, right now. It is not progress and not mastery.", earlier: "Earlier activity: {n} rounds", conf_low: "low confidence", conf_medium: "medium confidence", conf_high: "high confidence", back: "All areas" },
  uz: { coreTitle: "Ingliz tilingiz", coreSub: "Ko'nikmalar xaritasi", systems: "Til tizimlari", use: "Tildan foydalanish", tapArea: "Ko'nikmalarni ochish uchun sohani bosing", tapSkill: "Batafsil ko'rish uchun ko'nikmani bosing", soon: "Tez orada", notExplored: "Hali o'rganilmagan", st_verified: "Javoblar tekshirilgan", st_activity: "Mashq qilingan · hali tekshirilmagan", correctness: "To'g'rilik", basedOn: "{n} ta tekshirilgan raund asosida", basedOn_one: "1 ta tekshirilgan raund asosida", checkedToday: "oxirgi marta bugun tekshirilgan", checkedDaysAgo: "oxirgi marta {n} kun oldin tekshirilgan", unverified: "{n} raund o'ynaldi · hali tekshirilmagan", unverifiedHint: "Bu javoblar VIRORA tomonidan tekshirilmagan, shuning uchun to'g'rilikka hisoblanmaydi.", explainPct: "To'g'rilik — tekshirilgan javoblaringizning hozirgi to'g'ri ulushi. Bu rivojlanish ham, mukammallik ham emas.", earlier: "Avvalgi faollik: {n} raund", conf_low: "past ishonch", conf_medium: "o'rtacha ishonch", conf_high: "yuqori ishonch", back: "Barcha sohalar" },
  ru: { coreTitle: "Ваш английский", coreSub: "Карта навыков", systems: "Системы языка", use: "Использование языка", tapArea: "Нажмите на область, чтобы открыть навыки", tapSkill: "Нажмите на навык, чтобы увидеть детали", soon: "Скоро", notExplored: "Ещё не изучено", st_verified: "Ответы проверены", st_activity: "Практика · ещё не проверено", correctness: "Правильность", basedOn: "по {n} проверенным раундам", basedOn_one: "по 1 проверенному раунду", checkedToday: "последняя проверка сегодня", checkedDaysAgo: "последняя проверка {n} дн. назад", unverified: "Сыграно раундов: {n} · ещё не проверено", unverifiedHint: "Эти ответы не проверялись VIRORA, поэтому не входят в правильность.", explainPct: "Правильность — доля верных ответов среди проверенных на сегодня. Это не прогресс и не уровень владения.", earlier: "Ранняя активность: {n} раундов", conf_low: "низкая уверенность", conf_medium: "средняя уверенность", conf_high: "высокая уверенность", back: "Все области" },
};

const NODES = {
  uz: { systems: "Til tizimlari", use: "Tildan foydalanish", vocabulary: "Lug'at", grammar: "Grammatika", orthography: "Imlo", pronunciation: "Talaffuz", comprehension: "Tushunish", production: "Ishlab chiqarish", "vocabulary.form_and_meaning": "Shakl va ma'no", "vocabulary.meaning_in_context": "Kontekstdagi ma'no", "vocabulary.sense_relations": "Ma'no aloqalari", "vocabulary.collocations_chunks": "Kollokatsiyalar", "vocabulary.word_formation": "So'z yasalishi", "vocabulary.register_connotation": "Uslub va ma'no ottenkasi", "orthography.spelling": "Imlo yozuvi", "orthography.punctuation": "Tinish belgilari", "orthography.capitalization": "Bosh harflar", "comprehension.reading": "O'qish", "comprehension.listening": "Tinglash", "production.writing_sentence": "Yozish: gap", "production.writing_text": "Yozish: matn", "production.speaking": "Gapirish", "grammar.tenses": "Zamonlar", "grammar.nouns-articles": "Otlar va artikllar", "grammar.pronouns": "Olmoshlar", "grammar.verb-patterns": "Fe'l qoliplari", "grammar.adj-adv": "Sifat va ravish", "grammar.comparison": "Taqqoslash", "grammar.questions-negation": "Savol va inkor", "grammar.modals": "Modal fe'llar", "grammar.prep-phrasal": "Predloglar va frazali fe'llar", "grammar.sentence-structure": "Gap tuzilishi", "grammar.conditionals-wishes": "Shart gaplar va istaklar", "grammar.passive-causative": "Majhul nisbat", "grammar.reported-speech": "O'zlashtirma gap" },
  ru: { systems: "Системы языка", use: "Использование языка", vocabulary: "Лексика", grammar: "Грамматика", orthography: "Орфография", pronunciation: "Произношение", comprehension: "Понимание", production: "Речь и письмо", "vocabulary.form_and_meaning": "Форма и значение", "vocabulary.meaning_in_context": "Значение в контексте", "vocabulary.sense_relations": "Смысловые связи", "vocabulary.collocations_chunks": "Сочетания и фразы", "vocabulary.word_formation": "Словообразование", "vocabulary.register_connotation": "Регистр и оттенки", "orthography.spelling": "Правописание", "orthography.punctuation": "Пунктуация", "orthography.capitalization": "Заглавные буквы", "comprehension.reading": "Чтение", "comprehension.listening": "Аудирование", "production.writing_sentence": "Письмо: предложение", "production.writing_text": "Письмо: текст", "production.speaking": "Говорение", "grammar.tenses": "Времена", "grammar.nouns-articles": "Существительные и артикли", "grammar.pronouns": "Местоимения", "grammar.verb-patterns": "Глагольные модели", "grammar.adj-adv": "Прилагательные и наречия", "grammar.comparison": "Сравнение", "grammar.questions-negation": "Вопросы и отрицание", "grammar.modals": "Модальные глаголы", "grammar.prep-phrasal": "Предлоги и фразовые глаголы", "grammar.sentence-structure": "Структура предложения", "grammar.conditionals-wishes": "Условные и пожелания", "grammar.passive-causative": "Пассив и каузатив", "grammar.reported-speech": "Косвенная речь" },
};

export const AREA_COLOR = { vocabulary: "#7C6BE8", grammar: "#3E9E92", orthography: "#B08D57", production: "#B678C9", comprehension: "#CE6A86", pronunciation: "#8B8071" };

export function useSkillMapCopy() {
  const { lang } = useAppLang();
  const s = useCallback((key, vars = {}) => {
    const str = (UI[lang] || UI.en)[key] ?? UI.en[key] ?? key;
    return Object.entries(vars).reduce((a, [k, v]) => a.replace(`{${k}}`, v), str);
  }, [lang]);
  const label = useCallback((node) => NODES[lang]?.[node.id] || node.label, [lang]);
  return { s, label };
}