import { useCallback } from "react";
import { useAppLang } from "@/hooks/useAppLang";

// Learner Skill Map strings. Taxonomy (locked 2026-09-30): the ONLY percentage
// is Correctness (current accuracy on server-checked answers). Progress is
// cells (○◐●◆, not shown until criteria exist), Mastery is never shown as a %,
// and rounds played are activity telemetry, shown as plain text only.
// Node labels fall back to the taxonomy's English label when missing.
const UI = {
  en: { coreTitle: "Your English", coreSub: "Skill map", systems: "Language systems", use: "Language use", tapArea: "Tap an area to open its skills", tapSkill: "Tap a skill to see its details", soon: "Coming soon", notExplored: "Not explored yet", st_verified: "Answers checked", st_activity: "Practised · not checked yet", correctness: "Correctness", basedOn: "based on {n} checked answers", basedOn_one: "based on 1 checked answer", checkedToday: "last checked today", checkedDaysAgo: "last checked {n} days ago", unverified: "{n} rounds played · not checked yet", unverifiedHint: "These answers were not checked by VIRORA, so they don't count toward correctness.", explainPct: "Correctness = the share of your checked answers that are right, right now. It is not progress and not mastery.", earlier: "Earlier activity: {n} rounds", conf_low: "low confidence", conf_medium: "medium confidence", conf_high: "high confidence", back: "All areas" },
  uz: { coreTitle: "Ingliz tilingiz", coreSub: "Ko‘nikmalar xaritasi", systems: "Til tizimlari", use: "Tildan foydalanish", tapArea: "Ko‘nikmalarni ko‘rish uchun yo‘nalishni bosing", tapSkill: "Batafsil ma’lumot uchun ko‘nikmani bosing", soon: "Tez orada", notExplored: "Hali o‘rganilmagan", st_verified: "Tekshirilgan javoblar", st_activity: "Mashq bajarilgan · hali tekshirilmagan", correctness: "To‘g‘ri javoblar ulushi", basedOn: "{n} ta tekshirilgan javob asosida", basedOn_one: "1 ta tekshirilgan javob asosida", checkedToday: "Bugun oxirgi marta tekshirilgan", checkedDaysAgo: "Oxirgi marta {n} kun oldin tekshirilgan", unverified: "{n} ta raund bajarilgan · hali tekshirilmagan", unverifiedHint: "Bu javoblar VIRORA tomonidan tekshirilmagan, shuning uchun ular to‘g‘ri javoblar ulushiga kiritilmaydi.", explainPct: "To‘g‘ri javoblar ulushi — hozirgacha tekshirilgan javoblaringiz ichidagi to‘g‘ri javoblar foizi. Bu progress ham, mahorat ham emas.", earlier: "Avvalgi faollik: {n} ta raund", conf_low: "past ishonch darajasi", conf_medium: "o‘rtacha ishonch darajasi", conf_high: "yuqori ishonch darajasi", back: "Barcha yo‘nalishlar" },
  ru: { coreTitle: "Ваш английский", coreSub: "Карта навыков", systems: "Системы языка", use: "Использование языка", tapArea: "Нажмите на раздел, чтобы открыть навыки", tapSkill: "Нажмите на навык, чтобы посмотреть подробности", soon: "Скоро", notExplored: "Ещё не изучено", st_verified: "Проверенные ответы", st_activity: "Есть практика · пока не проверено", correctness: "Доля правильных ответов", basedOn: "На основе {n} проверенных ответов", basedOn_one: "На основе 1 проверенного ответа", checkedToday: "Последняя проверка — сегодня", checkedDaysAgo: "Последняя проверка — {n} дн. назад", unverified: "Сыграно раундов: {n} · пока не проверено", unverifiedHint: "Эти ответы не были проверены VIRORA, поэтому они не учитываются при расчёте доли правильных ответов.", explainPct: "Доля правильных ответов — процент верных ответов среди всех проверенных на данный момент. Это не прогресс и не мастерство.", earlier: "Предыдущая активность: {n} раундов", conf_low: "низкая уверенность", conf_medium: "средняя уверенность", conf_high: "высокая уверенность", back: "Все разделы" },
};

const NODES = {
  uz: { systems: "Til tizimlari", use: "Tildan foydalanish", vocabulary: "Lug‘at", grammar: "Grammatika", orthography: "Imlo va tinish belgilari", pronunciation: "Talaffuz", comprehension: "Tushunish", production: "Og‘zaki va yozma nutq", "vocabulary.form_and_meaning": "Shakl va ma’no", "vocabulary.meaning_in_context": "Kontekstdagi ma’no", "vocabulary.sense_relations": "So‘zlar o‘rtasidagi munosabatlar", "vocabulary.collocations_chunks": "So‘z birikmalari va tayyor iboralar", "vocabulary.word_formation": "So‘z yasalishi", "vocabulary.register_connotation": "Uslub va ma’no nozikliklari", "orthography.spelling": "Imlo", "orthography.punctuation": "Tinish belgilari", "orthography.capitalization": "Bosh harflar", "comprehension.reading": "O‘qish", "comprehension.listening": "Tinglab tushunish", "production.writing_sentence": "Yozma nutq: gaplar", "production.writing_text": "Yozma nutq: matnlar", "production.speaking": "Gapirish", "grammar.tenses": "Fe’l zamonlari", "grammar.nouns-articles": "Otlar va artikllar", "grammar.pronouns": "Olmoshlar", "grammar.verb-patterns": "Fe’l qoliplari", "grammar.adj-adv": "Sifatlar va ravishlar", "grammar.comparison": "Taqqoslash", "grammar.questions-negation": "So‘roq va inkor shakllari", "grammar.modals": "Modal fe’llar", "grammar.prep-phrasal": "Predloglar va frazali fe’llar", "grammar.sentence-structure": "Gap tuzilishi", "grammar.conditionals-wishes": "Shart va istak gaplari", "grammar.passive-causative": "Majhul va orttirma nisbat", "grammar.reported-speech": "O‘zlashtirma nutq" },
  ru: { systems: "Системы языка", use: "Использование языка", vocabulary: "Лексика", grammar: "Грамматика", orthography: "Орфография и пунктуация", pronunciation: "Произношение", comprehension: "Понимание", production: "Устная и письменная речь", "vocabulary.form_and_meaning": "Форма и значение", "vocabulary.meaning_in_context": "Значение в контексте", "vocabulary.sense_relations": "Семантические связи", "vocabulary.collocations_chunks": "Сочетания и устойчивые выражения", "vocabulary.word_formation": "Словообразование", "vocabulary.register_connotation": "Регистр и коннотации", "orthography.spelling": "Правописание", "orthography.punctuation": "Пунктуация", "orthography.capitalization": "Заглавные буквы", "comprehension.reading": "Чтение", "comprehension.listening": "Аудирование", "production.writing_sentence": "Письменная речь: предложения", "production.writing_text": "Письменная речь: тексты", "production.speaking": "Говорение", "grammar.tenses": "Времена глагола", "grammar.nouns-articles": "Существительные и артикли", "grammar.pronouns": "Местоимения", "grammar.verb-patterns": "Глагольные модели", "grammar.adj-adv": "Прилагательные и наречия", "grammar.comparison": "Сравнение", "grammar.questions-negation": "Вопросы и отрицание", "grammar.modals": "Модальные глаголы", "grammar.prep-phrasal": "Предлоги и фразовые глаголы", "grammar.sentence-structure": "Структура предложения", "grammar.conditionals-wishes": "Условные предложения и конструкции с wish", "grammar.passive-causative": "Пассивные и каузативные конструкции", "grammar.reported-speech": "Косвенная речь" },
};

export const AREA_COLOR = { vocabulary: "#7C6BE8", grammar: "#3E9E92", orthography: "#B08D57", production: "#B678C9", comprehension: "#CE6A86", pronunciation: "#8B8071" };

export function useSkillMapCopy() {
  const { lang } = useAppLang();
  const s = useCallback((key, vars = {}) => {
    const str = (UI[lang] || UI.en)[key] ?? UI.en[key] ?? key;
    return Object.entries(vars).reduce((a, [k, v]) => a.replace(`{${k}}`, v), str);
  }, [lang]);
  const label = useCallback((node) => NODES[lang]?.[node.id] || node.label, [lang]);
  return { s, label };
}