import { useCallback } from "react";
import { useAppLang } from "@/hooks/useAppLang";

// Local copy for Related Words + Connection Challenge, following
// antonymHuntCopy.js's convention. Two games, one copy module — the
// strings that differ by mode are keyed with a mode prefix.
const COPY = {
  en: {
    // Shared
    xp: "XP",
    streak: "Streak",
    attempts: "Tries left",
    item_progress: "{n}/{total} done",
    question: "Word {n} of {total}",
    correct: "Correct!",
    miss: "Not that one",
    loading: "Building your round…",
    empty: "Not enough categories yet.",
    result_title: "Round complete",
    result_out_of_attempts: "Out of tries",
    result_pass: "Well done!",
    result_fail: "Keep practicing",
    first_try: "First-try correct",
    tries_used: "Tries used",
    accuracy: "Accuracy",
    best_streak: "Best streak",
    streak_bonus: "Streak bonus +{n}",
    words_this_round: "This round",
    keep_going: "Keep going",
    play_again: "Play again",
    got_it: "Got it",
    next: "Next",
    skip: "Skip",
    // Related Words mode
    rw_title: "Related Words",
    rw_instruction: "Pick the word that belongs to the same topic as the target.",
    rw_target_label: "Target word",
    // Connection Challenge mode
    cc_title: "Connection Challenge",
    cc_instruction: "Three words share a hidden connection. Pick the option that belongs to the same group.",
    cc_clues_label: "These three are connected",
    // Blitz: Related Words
    rw_blitz_1_title: "Related Words",
    rw_blitz_1_body: "You'll see a target word and four options. Pick the word that belongs to the same topic or category.",
    rw_blitz_2_title: "Example",
    rw_blitz_2_body: "Target: \"kitchen\" → correct: \"stove\" (both about cooking). Wrong: \"mountain,\" \"guitar,\" \"election\" — none are kitchen items.",
    // Blitz: Connection Challenge
    cc_blitz_1_title: "Connection Challenge",
    cc_blitz_1_body: "Three words will appear. They all share a hidden connection — a category you have to figure out yourself.",
    cc_blitz_2_title: "Your task",
    cc_blitz_2_body: "Pick the option that belongs to the same group as the three shown words. The category isn't named — you infer it from the examples.",
    cc_blitz_3_title: "Example",
    cc_blitz_3_body: "\"stove,\" \"fridge,\" \"sink\" → connection: kitchen items → correct: \"oven\". The link was never said — you had to see it.",
  },
  uz: {
    xp: "XP",
    streak: "Ketma-ketlik",
    attempts: "Qolgan urinish",
    item_progress: "{n}/{total} bajarildi",
    question: "{total} tadan {n}-so'z",
    correct: "To'g'ri!",
    miss: "Bu emas",
    loading: "Tur tayyorlanmoqda…",
    empty: "Hozircha kategoriyalar yetarli emas.",
    result_title: "Tur yakunlandi",
    result_out_of_attempts: "Urinishlar tugadi",
    result_pass: "Ajoyib!",
    result_fail: "Mashq qilishda davom eting",
    first_try: "Birinchi urinishda to'g'ri",
    tries_used: "Ishlatilgan urinish",
    accuracy: "Aniqlik",
    best_streak: "Eng uzun ketma-ketlik",
    streak_bonus: "Ketma-ketlik bonusi +{n}",
    words_this_round: "Bu tur",
    keep_going: "Davom etish",
    play_again: "Qayta o'ynash",
    got_it: "Tushundim",
    next: "Keyingi",
    skip: "O'tkazib yuborish",
    rw_title: "Qarindosh So'zlar",
    rw_instruction: "Maqsad so'zi bilan bir xil mavzuga tegishli so'zni tanlang.",
    rw_target_label: "Maqsad so'z",
    cc_title: "Bog'liqlik Challengi",
    cc_instruction: "Uchta so'z yashirin bog'liqlikka ega. Bir guruhga kirgan variantni tanlang.",
    cc_clues_label: "Bu uchtalasi bog'langan",
    rw_blitz_1_title: "Qarindosh So'zlar",
    rw_blitz_1_body: "Maqsad so'zi va to'rt variant ko'rasiz. Bir xil mavzu yoki kategoriyaga tegishli so'zni tanling.",
    rw_blitz_2_title: "Misol",
    rw_blitz_2_body: "Maqsad: \"kitchen\" → to'g'ri: \"stove\" (ikkalasi ham pishirish haqida). Noto'g'ri: \"mountain,\" \"guitar,\" \"election\" — hech biri oshxona buyumi emas.",
    cc_blitz_1_title: "Bog'liqlik Challengi",
    cc_blitz_1_body: "Uchta so'z ko'rsatiladi. Ular yashirin bog'liqlikka ega — kategoriyani o'zingiz topishingiz kerak.",
    cc_blitz_2_title: "Vazifangiz",
    cc_blitz_2_body: "Ko'rsatilgan uchta so'z bilan bir guruhga kirgan variantni tanlang. Kategoriya nomi aytilmaydi — misollardan xulosa chiqarasiz.",
    cc_blitz_3_title: "Misol",
    cc_blitz_3_body: "\"stove,\" \"fridge,\" \"sink\" → bog'liqlik: oshxona buyumlari → to'g'ri: \"oven\". Bog'liqlik aytilmagan — uni ko'rishingiz kerak edi.",
  },
  ru: {
    xp: "XP",
    streak: "Серия",
    attempts: "Попыток осталось",
    item_progress: "{n}/{total} выполнено",
    question: "Слово {n} из {total}",
    correct: "Верно!",
    miss: "Не то",
    loading: "Готовим раунд…",
    empty: "Пока недостаточно категорий.",
    result_title: "Раунд завершён",
    result_out_of_attempts: "Попытки закончились",
    result_pass: "Отлично!",
    result_fail: "Продолжайте тренироваться",
    first_try: "Верно с первой попытки",
    tries_used: "Использовано попыток",
    accuracy: "Точность",
    best_streak: "Лучшая серия",
    streak_bonus: "Бонус за серию +{n}",
    words_this_round: "Этот раунд",
    keep_going: "Продолжить",
    play_again: "Играть снова",
    got_it: "Понятно",
    next: "Далее",
    skip: "Пропустить",
    rw_title: "Родственные слова",
    rw_instruction: "Выберите слово, которое относится к той же теме, что и заданное.",
    rw_target_label: "Заданное слово",
    cc_title: "Поиск связи",
    cc_instruction: "Три слова имеют скрытую связь. Выберите вариант из той же группы.",
    cc_clues_label: "Эти три связаны",
    rw_blitz_1_title: "Родственные слова",
    rw_blitz_1_body: "Вы увидите слово и четыре варианта. Выберите слово из той же темы или категории.",
    rw_blitz_2_title: "Пример",
    rw_blitz_2_body: "Заданное: «kitchen» → верно: «stove» (оба — про готовку). Неверно: «mountain», «guitar», «election» — ничего из кухни.",
    cc_blitz_1_title: "Поиск связи",
    cc_blitz_1_body: "Появятся три слова. У них есть скрытая связь — категория, которую вам нужно определить.",
    cc_blitz_2_title: "Ваша задача",
    cc_blitz_2_body: "Выберите вариант из той же группы, что и три показанных слова. Категория не называется — вы выводите её из примеров.",
    cc_blitz_3_title: "Пример",
    cc_blitz_3_body: "«stove», «fridge», «sink» → связь: кухонные предметы → верно: «oven». Связь не назвали — нужно было увидеть её.",
  },
};

export function useRelatedWordsCopy() {
  const { lang, t } = useAppLang();
  const c = useCallback((key, vars) => {
    let s = (COPY[lang] || COPY.en)[key] ?? COPY.en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    return s;
  }, [lang]);
  return { c, t, lang };
}