import { useCallback } from "react";
import { useAppLang } from "@/hooks/useAppLang";

// Local copy for Spelling's three modes, following antonymHuntCopy.js's
// convention. The old SpellingGame used useAppLang's t() for some strings
// and hardcoded others — consolidated here into the local-copy-module
// pattern every rebuilt game uses.
const COPY = {
  en: {
    // shared
    title_typing: "Typing",
    title_letter_order: "Letter Order",
    title_missing_letters: "Missing Letters",
    xp: "XP",
    streak: "Streak",
    attempts: "Tries left",
    item_progress: "{n}/{total} words",
    question: "Word {n} of {total}",
    correct: "Correct!",
    miss: "Not quite",
    loading: "Building your round…",
    empty: "Not enough words for this game yet.",
    result_title: "Round complete",
    result_out_of_attempts: "Out of tries",
    result_pass: "Well spelled!",
    result_fail: "Keep practicing",
    first_try: "First-try correct",
    tries_used: "Tries used",
    accuracy: "Accuracy",
    best_streak: "Best streak",
    streak_bonus: "Streak bonus +{n}",
    words_this_round: "Words in this round",
    keep_going: "Keep going",
    play_again: "Play again",
    listen: "Listen",
    replay: "Replay",
    erase: "Erase",
    meaning: "Meaning",
    submit: "Check",
    clear: "Clear",
    // missing_letters
    ml_instruction: "Fill in the missing letters to complete the word.",
    // letter_order
    lo_instruction: "Tap the letters in the correct order to spell the word.",
    // typing
    ty_instruction: "Listen to the word, then type it.",
    // blitz lesson
    blitz_skip: "Got it",
    blitz_next: "Next",
    blitz_start: "Start",
    ml_blitz_1: "Some letters are hidden. Type the ones that are missing.",
    ml_blitz_2: "Example: h_pp_ → happy. Fill the gaps and check.",
    lo_blitz_1: "The letters are shuffled. Tap them in the right order to rebuild the word.",
    lo_blitz_2: "Tap Erase to undo your last letter.",
    ty_blitz_1: "You'll hear the word. Type the full spelling from memory.",
    ty_blitz_2: "Tap Listen again if you need to replay it.",
  },
  uz: {
    title_typing: "Yozish",
    title_letter_order: "Harf Tartibi",
    title_missing_letters: "Yetishmayotgan Harflar",
    xp: "XP",
    streak: "Ketma-ketlik",
    attempts: "Qolgan urinish",
    item_progress: "{n}/{total} so'z",
    question: "{total} tadan {n}-so'z",
    correct: "To'g'ri!",
    miss: "To'g'ri emas",
    loading: "Tur tayyorlanmoqda…",
    empty: "Bu o'yin uchun hozircha so'zlar yetarli emas.",
    result_title: "Tur yakunlandi",
    result_out_of_attempts: "Urinishlar tugadi",
    result_pass: "To'g'ri yozildi!",
    result_fail: "Mashq qilishda davom eting",
    first_try: "Birinchi urinishda to'g'ri",
    tries_used: "Ishlatilgan urinish",
    accuracy: "Aniqlik",
    best_streak: "Eng uzun ketma-ketlik",
    streak_bonus: "Ketma-ketlik bonusi +{n}",
    words_this_round: "Bu turdagi so'zlar",
    keep_going: "Davom etish",
    play_again: "Qayta o'ynash",
    listen: "Tinglash",
    replay: "Qayta tinglash",
    erase: "O'chirish",
    meaning: "Ma'nosi",
    submit: "Tekshirish",
    clear: "Tozalash",
    ml_instruction: "Yetishmayotgan harflarni to'ldiring.",
    lo_instruction: "Harflarni to'g'ri tartibda bosing.",
    ty_instruction: "So'zni tinglang, so'ng yozing.",
    blitz_skip: "Tushunarli",
    blitz_next: "Keyingi",
    blitz_start: "Boshlash",
    ml_blitz_1: "Ba'zi harflar yashirilgan. Yetishmayotganlarini yozing.",
    ml_blitz_2: "Misol: h_pp_ → happy. Bo'shliqlarni to'ldiring.",
    lo_blitz_1: "Harflar aralashtirilgan. To'g'ri tartibda bosing.",
    lo_blitz_2: "Oxirgi harfni bekor qilish uchun O'chirishni bosing.",
    ty_blitz_1: "So'zni eshitasiz. To'liq yozing.",
    ty_blitz_2: "Qayta tinglash uchun Tinglashni bosing.",
  },
  ru: {
    title_typing: "Набор",
    title_letter_order: "Порядок букв",
    title_missing_letters: "Пропущенные буквы",
    xp: "XP",
    streak: "Серия",
    attempts: "Попыток осталось",
    item_progress: "{n}/{total} слов",
    question: "Слово {n} из {total}",
    correct: "Верно!",
    miss: "Не совсем",
    loading: "Готовим раунд…",
    empty: "Пока недостаточно слов для этой игры.",
    result_title: "Раунд завершён",
    result_out_of_attempts: "Попытки закончились",
    result_pass: "Правильно!",
    result_fail: "Продолжайте тренироваться",
    first_try: "Верно с первой попытки",
    tries_used: "Использовано попыток",
    accuracy: "Точность",
    best_streak: "Лучшая серия",
    streak_bonus: "Бонус за серию +{n}",
    words_this_round: "Слова этого раунда",
    keep_going: "Продолжить",
    play_again: "Играть снова",
    listen: "Слушать",
    replay: "Повторить",
    erase: "Стереть",
    meaning: "Значение",
    submit: "Проверить",
    clear: "Очистить",
    ml_instruction: "Заполните пропущенные буквы.",
    lo_instruction: "Нажимайте буквы в правильном порядке.",
    ty_instruction: "Прослушайте слово и напишите его.",
    blitz_skip: "Понятно",
    blitz_next: "Далее",
    blitz_start: "Начать",
    ml_blitz_1: "Некоторые буквы скрыты. Впишите недостающие.",
    ml_blitz_2: "Пример: h_pp_ → happy. Заполните пропуски.",
    lo_blitz_1: "Буквы перемешаны. Нажимайте в правильном порядке.",
    lo_blitz_2: "Нажмите Стереть, чтобы отменить последнюю букву.",
    ty_blitz_1: "Вы услышите слово. Напишите его полностью.",
    ty_blitz_2: "Нажмите Слушать, чтобы повторить.",
  },
};

export function useSpellingCopy() {
  const { lang, t } = useAppLang();
  const c = useCallback((key, vars) => {
    let s = (COPY[lang] || COPY.en)[key] ?? COPY.en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    return s;
  }, [lang]);
  return { c, t, lang };
}