import { useCallback } from "react";
import { useAppLang } from "@/hooks/useAppLang";

const COPY = {
  en: {
    title_fill_blank: "Fill the Blank",
    title_best_word: "Choose the Best Word",
    title_sentence_repair: "Sentence Repair",
    title_collocation_match: "Collocation Match",
    xp: "XP",
    streak: "Streak",
    attempts: "Tries left",
    item_progress: "{n}/{total}",
    question: "Word {n} of {total}",
    correct: "Correct!",
    miss: "Not that one",
    loading: "Building your round…",
    empty: "Not enough words for this game yet.",
    result_title: "Round complete",
    result_out_of_attempts: "Out of tries",
    result_pass: "Well done!",
    result_fail: "Keep practicing",
    first_try: "First-try correct",
    tries_used: "Tries used",
    accuracy: "Accuracy",
    best_streak: "Best streak",
    streak_bonus: "Streak bonus +{n}",
    words_this_round: "Words in this round",
    keep_going: "Keep going",
    play_again: "Play again",
    // instructions
    fb_instruction: "Pick the word that fills the blank.",
    bw_instruction: "Pick the word that fits best in this context.",
    sr_instruction: "One word is wrong. Pick the correct replacement.",
    cm_instruction: "Pick the word that completes the expression.",
    // blitz
    fb_blitz_1: "Read the sentence and pick the word that fills the blank.",
    bw_blitz_1: "All four options are real English words. Pick the one that fits best in this specific context — not just any synonym.",
    sr_blitz_1: "One word in the sentence is the wrong choice. Pick the correct word to replace it.",
    cm_blitz_1: "A collocation is a natural word combination — words that go together in English. For example, we say 'make a decision', not 'do a decision'. Pick the word that completes the expression naturally.",
    cm_blitz_2: "Example: 'make a ___' → 'decision' (we say 'make a decision', not 'make a conclusion').",
    blitz_skip: "Skip",
    blitz_next: "Next",
    blitz_start: "Start",
  },
  uz: {
    title_fill_blank: "Bo'shliqni To'ldiring",
    title_best_word: "Eng Tepa So'zni Tanlang",
    title_sentence_repair: "Gapni Tuzating",
    title_collocation_match: "So'z Birikmasi",
    xp: "XP",
    streak: "Ketma-ketlik",
    attempts: "Qolgan urinish",
    item_progress: "{n}/{total}",
    question: "{total} tadan {n}-so'z",
    correct: "To'g'ri!",
    miss: "Bu emas",
    loading: "Tur tayyorlanmoqda…",
    empty: "Bu o'yin uchun hozircha so'zlar yetarli emas.",
    result_title: "Tur yakunlandi",
    result_out_of_attempts: "Urinishlar tugadi",
    result_pass: "Ajoyib!",
    result_fail: "Mashq qilishda davom eting",
    first_try: "Birinchi urinishda to'g'ri",
    tries_used: "Ishlatilgan urinish",
    accuracy: "Aniqlik",
    best_streak: "Eng uzun ketma-ketlik",
    streak_bonus: "Ketma-ketlik bonusi +{n}",
    words_this_round: "Bu turdagi so'zlar",
    keep_going: "Davom etish",
    play_again: "Qayta o'ynash",
    fb_instruction: "Bo'shliqni to'ldiruvchi so'zni tanlang.",
    bw_instruction: "Bu kontekstda eng mos keladigan so'zni tanlang.",
    sr_instruction: "Bitta so'z noto'g'ri. To'g'ri so'zni tanlang.",
    cm_instruction: "Iborani to'liqlaydigan so'zni tanlang.",
    fb_blitz_1: "Gapni o'qing va bo'shliqni to'ldiruvchi so'zni tanlang.",
    bw_blitz_1: "To'rtta variant ham haqiqiy ingliz so'zlari. Bu kontekstda eng mos keladiganini tanlang.",
    sr_blitz_1: "Gapdagi bitta so'z noto'g'ri tanlangan. To'g'ri so'zni tanlang.",
    cm_blitz_1: "So'z birikmasi — ingliz tilida tabiiy birikadigan so'zlar. Masalan, 'make a decision' deymiz, 'do a decision' emas.",
    cm_blitz_2: "Misol: 'make a ___' → 'decision' ('make a decision' to'g'ri, 'make a conclusion' emas).",
    blitz_skip: "O'tkazish",
    blitz_next: "Keyingi",
    blitz_start: "Boshlash",
  },
  ru: {
    title_fill_blank: "Заполни пропуск",
    title_best_word: "Лучшее слово",
    title_sentence_repair: "Почини предложение",
    title_collocation_match: "Словосочетание",
    xp: "XP",
    streak: "Серия",
    attempts: "Попыток осталось",
    item_progress: "{n}/{total}",
    question: "Слово {n} из {total}",
    correct: "Верно!",
    miss: "Не то",
    loading: "Готовим раунд…",
    empty: "Пока недостаточно слов для этой игры.",
    result_title: "Раунд завершён",
    result_out_of_attempts: "Попытки закончились",
    result_pass: "Отлично!",
    result_fail: "Продолжайте тренироваться",
    first_try: "Верно с первой попытки",
    tries_used: "Использовано попыток",
    accuracy: "Точность",
    best_streak: "Лучшая серия",
    streak_bonus: "Бонус за серию +{n}",
    words_this_round: "Слова этого раунда",
    keep_going: "Продолжить",
    play_again: "Играть снова",
    fb_instruction: "Выберите слово, которое заполняет пропуск.",
    bw_instruction: "Выберите слово, которое лучше всего подходит к контексту.",
    sr_instruction: "Одно слово неправильное. Выберите правильную замену.",
    cm_instruction: "Выберите слово, которое завершает выражение.",
    fb_blitz_1: "Прочитайте предложение и выберите слово для пропуска.",
    bw_blitz_1: "Все четыре варианта — настоящие английские слова. Выберите то, что лучше всего подходит к контексту.",
    sr_blitz_1: "Одно слово в предложении неправильное. Выберите правильную замену.",
    cm_blitz_1: "Коллокация — это естественное сочетание слов. Например, мы говорим 'make a decision', а не 'do a decision'.",
    cm_blitz_2: "Пример: 'make a ___' → 'decision' ('make a decision' правильно, 'make a conclusion' нет).",
    blitz_skip: "Пропустить",
    blitz_next: "Далее",
    blitz_start: "Начать",
  },
};

export function useUsageCopy() {
  const { lang, t } = useAppLang();
  const c = useCallback((key, vars) => {
    let s = (COPY[lang] || COPY.en)[key] ?? COPY.en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    return s;
  }, [lang]);
  return { c, t, lang };
}