import { useCallback } from "react";
import { useAppLang } from "@/hooks/useAppLang";

const COPY = {
  en: {
    // shared
    title_word_family: "Word Family Builder",
    title_prefix_match: "Prefix Match",
    title_suffix_builder: "Suffix Builder",
    title_root_hunt: "Root Hunt",
    xp: "XP",
    streak: "Streak",
    attempts: "Tries left",
    item_progress: "{n}/{total}",
    question: "Word {n} of {total}",
    correct: "Correct!",
    miss: "Not that one",
    loading: "Building your round…",
    empty: "Not enough words for this game yet.",
    result_title: "Round complete",
    result_out_of_attempts: "Out of tries",
    result_pass: "Well done!",
    result_fail: "Keep practicing",
    first_try: "First-try correct",
    tries_used: "Tries used",
    accuracy: "Accuracy",
    best_streak: "Best streak",
    streak_bonus: "Streak bonus +{n}",
    words_this_round: "Words in this round",
    keep_going: "Keep going",
    play_again: "Play again",
    // word_family
    wf_instruction: "Pick the correct form for each part of speech.",
    wf_noun: "Noun",
    wf_verb: "Verb",
    wf_adjective: "Adjective",
    wf_adverb: "Adverb",
    wf_blitz_1: "Many English words change form for different jobs in a sentence. A noun names the thing, a verb is the action, an adjective describes, and an adverb tells how.",
    wf_blitz_2: "Example: beauty (noun) → beautify (verb) → beautiful (adjective) → beautifully (adverb). Pick the correct form for each job.",
    // prefix_match
    pm_instruction: "Pick the prefix that matches the target meaning.",
    pm_target: "Target meaning",
    pm_result: "Result",
    pm_blitz_1: "A prefix is added to the START of a word to change its meaning. un- = not, re- = again, dis- = not/opposite, mis- = wrong, pre- = before, non- = not.",
    pm_blitz_2: "Example: happy → un + happy → unhappy (not happy). Pick the prefix that matches the target meaning.",
    // suffix_builder
    sb_instruction: "Pick the suffix that builds the target part of speech.",
    sb_target: "Target form",
    sb_result: "Result",
    sb_blitz_1: "A suffix is added to the END of a word to change its grammar. -tion makes a noun, -ness makes a noun, -ful makes an adjective, -ly makes an adverb, -able makes an adjective, -er makes a noun.",
    sb_blitz_2: "Example: beauty → beauty + ful → beautiful (adjective). Pick the suffix that builds the target part of speech.",
    // root_hunt
    rh_instruction: "Tap all words that share the given root.",
    rh_root: "Root",
    rh_meaning: "Meaning",
    rh_blitz_1: "Many English words share a common root — a core part that carries the main meaning. The root 'port' means 'carry': transport, import, export, report.",
    rh_blitz_2: "Tap all the words that contain the given root. Don't tap the ones that don't belong.",
    // blitz
    blitz_skip: "Skip",
    blitz_next: "Next",
    blitz_start: "Start",
  },
  uz: {
    title_word_family: "So'z Oilasi",
    title_prefix_match: "Prefiks Tanlash",
    title_suffix_builder: "Suffiks Qurish",
    title_root_hunt: "Ildiz Ovi",
    xp: "XP",
    streak: "Ketma-ketlik",
    attempts: "Qolgan urinish",
    item_progress: "{n}/{total}",
    question: "{total} tadan {n}-so'z",
    correct: "To'g'ri!",
    miss: "Bu emas",
    loading: "Tur tayyorlanmoqda…",
    empty: "Bu o'yin uchun hozircha so'zlar yetarli emas.",
    result_title: "Tur yakunlandi",
    result_out_of_attempts: "Urinishlar tugadi",
    result_pass: "Ajoyib!",
    result_fail: "Mashq qilishda davom eting",
    first_try: "Birinchi urinishda to'g'ri",
    tries_used: "Ishlatilgan urinish",
    accuracy: "Aniqlik",
    best_streak: "Eng uzun ketma-ketlik",
    streak_bonus: "Ketma-ketlik bonusi +{n}",
    words_this_round: "Bu turdagi so'zlar",
    keep_going: "Davom etish",
    play_again: "Qayta o'ynash",
    wf_instruction: "Har bir so'z turkumi uchun to'g'ri formani tanlang.",
    wf_noun: "Ot",
    wf_verb: "Fe'l",
    wf_adjective: "Sifat",
    wf_adverb: "Ravish",
    wf_blitz_1: "Ko'p ingliz so'zlari gapdagi vazifasiga qarab formasini o'zgartiradi. Ot — nom, fe'l — harakat, sifat — tavsif, ravish — qanday qilib.",
    wf_blitz_2: "Misol: beauty (ot) → beautify (fe'l) → beautiful (sifat) → beautifully (ravish). Har bir vazifa uchun to'g'ri formani tanlang.",
    pm_instruction: "Maqsad ma'nosiga mos prefiksni tanlang.",
    pm_target: "Maqsad ma'no",
    pm_result: "Natija",
    pm_blitz_1: "Prefiks so'z boshiga qo'shiladi. un- = emas, re- = qayta, dis- = emas/qarama-qarshi, mis- = noto'g'ri, pre- = oldin, non- = emas.",
    pm_blitz_2: "Misol: happy → un + happy → unhappy (baxtli emas). Maqsad ma'nosiga mos prefiksni tanlang.",
    sb_instruction: "Maqsad so'z turkumini quruvchi suffiksni tanlang.",
    sb_target: "Maqsad forma",
    sb_result: "Natija",
    sb_blitz_1: "Suffiks so'z oxiriga qo'shiladi. -tion ot yasaydi, -ness ot yasaydi, -ful sifat yasaydi, -ly ravish yasaydi, -able sifat yasaydi, -er ot yasaydi.",
    sb_blitz_2: "Misol: beauty → beauty + ful → beautiful (sifat). Maqsad so'z turkumini quruvchi suffiksni tanlang.",
    rh_instruction: "Berilgan ildizga ega bo'lgan barcha so'zlarni bosing.",
    rh_root: "Ildiz",
    rh_meaning: "Ma'no",
    rh_blitz_1: "Ko'p ingliz so'zlari umumiy ildizga ega — asosiy ma'noni ko'taruvchi qism. 'port' ildizi 'ko'tarmoq' degani: transport, import, export, report.",
    rh_blitz_2: "Berilgan ildizni o'z ichiga olgan barcha so'zlarni bosing. Tegishli emaslarini boshmang.",
    blitz_skip: "O'tkazish",
    blitz_next: "Keyingi",
    blitz_start: "Boshlash",
  },
  ru: {
    title_word_family: "Семья слова",
    title_prefix_match: "Приставка",
    title_suffix_builder: "Суффикс",
    title_root_hunt: "Охота за корнем",
    xp: "XP",
    streak: "Серия",
    attempts: "Попыток осталось",
    item_progress: "{n}/{total}",
    question: "Слово {n} из {total}",
    correct: "Верно!",
    miss: "Не то",
    loading: "Готовим раунд…",
    empty: "Пока недостаточно слов для этой игры.",
    result_title: "Раунд завершён",
    result_out_of_attempts: "Попытки закончились",
    result_pass: "Отлично!",
    result_fail: "Продолжайте тренироваться",
    first_try: "Верно с первой попытки",
    tries_used: "Использовано попыток",
    accuracy: "Точность",
    best_streak: "Лучшая серия",
    streak_bonus: "Бонус за серию +{n}",
    words_this_round: "Слова этого раунда",
    keep_going: "Продолжить",
    play_again: "Играть снова",
    wf_instruction: "Выберите правильную форму для каждой части речи.",
    wf_noun: "Существительное",
    wf_verb: "Глагол",
    wf_adjective: "Прилагательное",
    wf_adverb: "Наречие",
    wf_blitz_1: "Многие английские слова меняют форму для разных ролей в предложении. Существительное — название, глагол — действие, прилагательное — описание, наречие — как.",
    wf_blitz_2: "Пример: beauty (сущ.) → beautify (гл.) → beautiful (прил.) → beautifully (нареч.). Выберите правильную форму для каждой роли.",
    pm_instruction: "Выберите приставку, соответствующую целевому значению.",
    pm_target: "Целевое значение",
    pm_result: "Результат",
    pm_blitz_1: "Приставка добавляется в НАЧАЛО слова. un- = не, re- = снова, dis- = не/противоположно, mis- = неверно, pre- = до, non- = не.",
    pm_blitz_2: "Пример: happy → un + happy → unhappy (не счастливый). Выберите приставку, соответствующую целевому значению.",
    sb_instruction: "Выберите суффикс, образующий нужную часть речи.",
    sb_target: "Целевая форма",
    sb_result: "Результат",
    sb_blitz_1: "Суффикс добавляется в КОНЕЦ слова. -tion образует сущ., -ness — сущ., -ful — прил., -ly — нареч., -able — прил., -er — сущ.",
    sb_blitz_2: "Пример: beauty → beauty + ful → beautiful (прил.). Выберите суффикс, образующий нужную часть речи.",
    rh_instruction: "Нажмите все слова с данным корнем.",
    rh_root: "Корень",
    rh_meaning: "Значение",
    rh_blitz_1: "Многие английские слова имеют общий корень — основу с главным значением. Корень 'port' значит 'нести': transport, import, export, report.",
    rh_blitz_2: "Нажмите все слова, содержащие данный корень. Не нажимайте неподходящие.",
    blitz_skip: "Пропустить",
    blitz_next: "Далее",
    blitz_start: "Начать",
  },
};

export function useWordFormsCopy() {
  const { lang, t } = useAppLang();
  const c = useCallback((key, vars) => {
    let s = (COPY[lang] || COPY.en)[key] ?? COPY.en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    return s;
  }, [lang]);
  return { c, t, lang };
}