// Ingests verified practice-content JSON into a bank module. Dev-only: lives
// outside src/ so it never reaches the production bundle.
//
//   node tools/grammar-practice/ingest.mjs content/grammar-practice/<file>.json
//
// Assigns ids, normalises accepted answer variants, validates, and writes
// src/lib/grammarPractice/bank/<domain>.<branch>.<topic>.js
import { readFileSync, writeFileSync } from "node:fs";
import { validateBank, variantCount } from "../../src/lib/grammarPractice/schema.js";

const src = process.argv[2];
if (!src) { console.error("usage: ingest.mjs <file.json>"); process.exit(1); }
const raw = JSON.parse(readFileSync(src, "utf8"));

// Contractions are a real second valid answer — "doesn't watch" and "does not
// watch" are both correct and a string matcher accepts only one. Expand them
// here rather than asking the author to remember every time.
const CONTRACTIONS = [["doesn't", "does not"], ["don't", "do not"], ["isn't", "is not"], ["aren't", "are not"]];
function accepted(key) {
  if (typeof key !== "string") return null;
  const alts = new Set();
  for (const [short, long] of CONTRACTIONS) {
    if (key.includes(short)) alts.add(key.replace(short, long));
    if (key.includes(long)) alts.add(key.replace(long, short));
  }
  return alts.size ? [...alts] : null;
}

const seq = {};
const items = raw.map((it) => {
  const k = `${it.stage}`;
  seq[k] = (seq[k] || 0) + 1;
  const id = `gpr.${it.domain}.${it.branch}.${it.topic}.${it.stage}.${String(seq[k]).padStart(3, "0")}`;
  const alt = accepted(it.key);
  return { id, ...it, ...(alt ? { acceptable: alt } : {}) };
});

const problems = validateBank(items);
if (problems.length) {
  console.error(`REFUSED — ${problems.length} problem(s):`);
  problems.forEach((p) => console.error("  " + p));
  process.exit(1);
}

const { domain, branch, topic } = items[0];
const out = `src/lib/grammarPractice/bank/${domain}.${branch}.${topic}.js`;
writeFileSync(out,
  `// AUTO-GENERATED by tools/grammar-practice/ingest.mjs from ${src}\n` +
  `// Do not edit by hand — edit the source JSON and re-run the ingester.\n` +
  `export default ${JSON.stringify(items, null, 1)};\n`);

const byStage = {}; const variants = {};
for (const it of items) {
  byStage[it.stage] = (byStage[it.stage] || 0) + 1;
  variants[it.stage] = (variants[it.stage] || 0) + variantCount(it);
}
console.log(`wrote ${out}`);
console.log(`  ${items.length} authored items ->`, JSON.stringify(byStage));
console.log(`  surface variants after slot expansion ->`, JSON.stringify(variants));
console.log(`  accepted-answer variants added: ${items.filter((i) => i.acceptable).length}`);
