// Ingests verified practice-content JSON into a bank module. Dev-only: lives
// outside src/ so it never reaches the production bundle.
//
//   node tools/grammar-practice/ingest.mjs content/grammar-practice/<file>.json
//
// Assigns ids, normalises accepted answer variants, validates, and writes
// src/lib/grammarPractice/bank/<domain>.<branch>.<topic>.js
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { validateBank, variantCount } from "../../src/lib/grammarPractice/schema.js";

const src = process.argv[2];
const LEGACY = process.argv.includes("--allow-legacy");
if (!src) { console.error("usage: ingest.mjs <file.json>"); process.exit(1); }
const raw = JSON.parse(readFileSync(src, "utf8"));

// Contractions are a real second valid answer — "doesn't watch" and "does not
// watch" are both correct and a string matcher accepts only one. Expand them
// here rather than asking the author to remember every time.
const CONTRACTIONS = [["doesn't", "does not"], ["don't", "do not"], ["isn't", "is not"], ["aren't", "are not"]];
function accepted(key) {
  if (typeof key !== "string") return null;
  const alts = new Set();
  for (const [short, long] of CONTRACTIONS) {
    if (key.includes(short)) alts.add(key.replace(short, long));
    if (key.includes(long)) alts.add(key.replace(long, short));
  }
  return alts.size ? [...alts] : null;
}

// Prompt-version stamp. Every generated item carries "pv" naming the version of
// the generation prompt that produced it. Batches have twice been generated from
// a stale copy of the prompt pasted out of chat history, reintroducing defects
// that a later version had already fixed — and both times it cost a full
// regeneration to discover. The stamp turns that into a one-line check here.
// It is a provenance marker, not content, so it is stripped before the bank.
const MIN_PV = "2.5";
const versions = [...new Set(raw.map((it) => it.pv || "(unstamped)"))];
if (!LEGACY && (versions.length !== 1 || versions[0] < MIN_PV)) {
  console.error(`REFUSED — prompt version: found ${versions.join(", ")}, expected ${MIN_PV}`);
  console.error(`  An unstamped or older batch was generated from a stale prompt.`);
  console.error(`  Regenerate with the current 1-PASTE-<topic>-v${MIN_PV}.txt file.`);
  console.error(`  (--allow-legacy re-ingests already-shipped content unchanged.)`);
  process.exit(1);
}
console.log(`prompt version ${versions[0]} — ok`);

const seq = {};
const items = raw.map((it) => {
  const k = `${it.stage}`;
  seq[k] = (seq[k] || 0) + 1;
  const id = `gpr.${it.domain}.${it.branch}.${it.topic}.${it.stage}.${String(seq[k]).padStart(3, "0")}`;
  const alt = accepted(it.key);
  const { pv, ...rest } = it;
  return { id, ...rest, ...(alt ? { acceptable: alt } : {}) };
});

// Distinct sentences per stage. A batch met the 68-item count and the variance
// floor by shipping four `choose` sentences five times each — 320 claimed
// variants, 64 real ones. Both of those numbers became targets the moment they
// were written down, and duplication is the cheapest way to hit a target. So
// the floor is now computed on DISTINCT sentences and duplicates are refused
// outright, before the arithmetic that they were inflating.
const sentence = (it) => `${it.stage}::${it.prompt || it.source || ""}`;
const dupes = Object.entries(
  items.reduce((acc, it) => ({ ...acc, [sentence(it)]: (acc[sentence(it)] || 0) + 1 }), {})
).filter(([, n]) => n > 1);
if (dupes.length) {
  console.error(`REFUSED — ${dupes.length} sentence(s) repeated within a stage:`);
  dupes.forEach(([k, n]) => console.error(`  x${n}  ${k.slice(0, 78)}`));
  console.error(`  Every item in a stage must be a different sentence.`);
  process.exit(1);
}

// Variance floor — the reason slots exist. A stage below this repeats too soon.
const FLOOR = 200;
const pools = {};
for (const it of items) {
  if (["choose", "build", "transform"].includes(it.stage)) {
    pools[it.stage] = (pools[it.stage] || 0) + variantCount(it);
  }
}
const thin = LEGACY ? [] : Object.entries(pools).filter(([, n]) => n < FLOOR);
if (thin.length) {
  console.error(`REFUSED — variance floor is ${FLOOR} surface variants per stage:`);
  thin.forEach(([s, n]) => console.error(`  ${s}: ${n}`));
  console.error(`  Most items need two slots of four fillers. Regenerate.`);
  process.exit(1);
}

const problems = validateBank(items);
if (problems.length) {
  console.error(`REFUSED — ${problems.length} problem(s):`);
  problems.forEach((p) => console.error("  " + p));
  process.exit(1);
}

const { domain, branch, topic } = items[0];
const out = `src/lib/grammarPractice/bank/${domain}.${branch}.${topic}.js`;
writeFileSync(out,
  `// AUTO-GENERATED by tools/grammar-practice/ingest.mjs from ${src}\n` +
  `// Do not edit by hand — edit the source JSON and re-run the ingester.\n` +
  `export default ${JSON.stringify(items, null, 1)};\n`);

const byStage = {}; const variants = {};
for (const it of items) {
  byStage[it.stage] = (byStage[it.stage] || 0) + 1;
  variants[it.stage] = (variants[it.stage] || 0) + variantCount(it);
}
// Rebuild the manifest from every bank on disk. The node map needs pool sizes
// to render topic and stage nodes, and must not pay for loading whole banks to
// get them — so counts live here, and a bank is fetched only when a round starts.
const bankDir = "src/lib/grammarPractice/bank";
const manifest = {};
for (const file of readdirSync(bankDir).filter((f) => f.endsWith(".js"))) {
  const key = file.replace(/\.js$/, "");
  const rows = JSON.parse(
    readFileSync(`${bankDir}/${file}`, "utf8").replace(/^[\s\S]*?export default /, "").replace(/;\s*$/, "")
  );
  const stages = {};
  for (const it of rows) stages[it.stage] = (stages[it.stage] || 0) + variantCount(it);
  const [d, b, ...t] = key.split(".");
  // CEFR level of the topic. Every item in a topic shares one level, but take
  // the highest present rather than the first, so a mixed topic reports the
  // demand it actually makes on a student.
  const ORDER = ["A1", "A2", "B1", "B2", "C1", "C2"];
  const level = rows.map((r) => r.level).filter(Boolean)
    .sort((a, z) => ORDER.indexOf(z) - ORDER.indexOf(a))[0] || null;
  manifest[key] = { domain: d, branch: b, topic: t.join("."), level, authored: rows.length, stages };
}
writeFileSync("src/lib/grammarPractice/manifest.js",
  "// AUTO-GENERATED by tools/grammar-practice/ingest.mjs — do not edit by hand.\n" +
  "// Pool sizes per topic and stage, counting slot expansion. Lets the node map\n" +
  "// render real numbers without loading a single bank.\n" +
  `export const PRACTICE_MANIFEST = ${JSON.stringify(manifest, null, 1)};\n\n` +
  "export const topicsInBranch = (domain, branch) =>\n" +
  "  Object.values(PRACTICE_MANIFEST).filter((m) => m.domain === domain && m.branch === branch);\n\n" +
  "export const branchHasPractice = (domain, branch) =>\n" +
  "  Object.values(PRACTICE_MANIFEST).some((m) => m.domain === domain && m.branch === branch);\n");

console.log(`wrote ${out}`);
console.log(`manifest: ${Object.keys(manifest).length} topic(s)`);
console.log(`  ${items.length} authored items ->`, JSON.stringify(byStage));
console.log(`  surface variants after slot expansion ->`, JSON.stringify(variants));
console.log(`  accepted-answer variants added: ${items.filter((i) => i.acceptable).length}`);
