// Help button + dialog copy (en/uz/ru). The Help button is the single,
// always-available place for the app tour, bug reports and feedback.

export const HELP_COPY = {
  en: {
    button: "Help",
    buttonAria: "Help: app tour, bug reports and feedback",
    title: "How can we help?",
    subtitle: "Find your way around, or tell us what's broken or what could be better.",
    tourTitle: "Show me around",
    tourDesc: "A 1-minute tour of where everything is.",
    bugTitle: "Report a bug",
    bugDesc: "Something is broken or unexpected.",
    feedbackTitle: "Send feedback",
    feedbackDesc: "Ideas, requests, or general feedback.",
    formNote: "We automatically include the page you are on and the time of submission.",
    shortTitle: "Short title",
    expected: "What did you expect to happen? (optional)",
    bugDetails: "What happened? Include enough detail to reproduce it.",
    feedbackDetails: "What would make VIRORA better for you?",
    attach: "Attach screenshot (optional)",
    attached: "Screenshot attached: {name}",
    remove: "Remove",
    back: "Back",
    send: "Send",
    sending: "Sending…",
    thanks: "Thank you",
    sentBug: "Your bug report has been sent to the VIRORA team.",
    sentFeedback: "Your feedback has been sent to the VIRORA team.",
    done: "Done",
    errImage: "Please choose an image file.",
    errSize: "Screenshots must be 10 MB or smaller.",
    errBugEmpty: "Add a title and describe the issue.",
    errFeedbackEmpty: "Please enter your feedback.",
    errSend: "Your report could not be sent. Please try again.",
  },
  uz: {
    button: "Yordam",
    buttonAria: "Yordam: ilova bo'yicha sayohat, xatolar va fikrlar",
    title: "Qanday yordam bera olamiz?",
    subtitle: "Ilovada yo'lingizni toping yoki nima ishlamayotgani va nimani yaxshilash mumkinligini ayting.",
    tourTitle: "Ilovani ko'rsating",
    tourDesc: "Hamma narsa qayerdaligini 1 daqiqada ko'rsatamiz.",
    bugTitle: "Xato haqida xabar berish",
    bugDesc: "Nimadir ishlamayapti yoki kutilmagan holat.",
    feedbackTitle: "Fikr bildirish",
    feedbackDesc: "G'oyalar, so'rovlar yoki umumiy fikrlar.",
    formNote: "Siz turgan sahifa va yuborilgan vaqt avtomatik qo'shiladi.",
    shortTitle: "Qisqa sarlavha",
    expected: "Nima bo'lishini kutgan edingiz? (ixtiyoriy)",
    bugDetails: "Nima bo'ldi? Takrorlash mumkin bo'lishi uchun batafsil yozing.",
    feedbackDetails: "VIRORA'ni siz uchun nima yaxshiroq qiladi?",
    attach: "Skrinshot qo'shish (ixtiyoriy)",
    attached: "Skrinshot qo'shildi: {name}",
    remove: "O'chirish",
    back: "Orqaga",
    send: "Yuborish",
    sending: "Yuborilmoqda…",
    thanks: "Rahmat",
    sentBug: "Xato haqidagi xabaringiz VIRORA jamoasiga yuborildi.",
    sentFeedback: "Fikringiz VIRORA jamoasiga yuborildi.",
    done: "Tayyor",
    errImage: "Iltimos, rasm faylini tanlang.",
    errSize: "Skrinshot hajmi 10 MB dan oshmasligi kerak.",
    errBugEmpty: "Sarlavha qo'shing va muammoni tasvirlab bering.",
    errFeedbackEmpty: "Iltimos, fikringizni yozing.",
    errSend: "Xabaringizni yuborib bo'lmadi. Qaytadan urinib ko'ring.",
  },
  ru: {
    button: "Помощь",
    buttonAria: "Помощь: тур по приложению, ошибки и отзывы",
    title: "Чем помочь?",
    subtitle: "Разберитесь, где что находится, или расскажите, что не работает и что можно улучшить.",
    tourTitle: "Покажите, где что",
    tourDesc: "Минутный тур по приложению.",
    bugTitle: "Сообщить об ошибке",
    bugDesc: "Что-то не работает или работает не так.",
    feedbackTitle: "Оставить отзыв",
    feedbackDesc: "Идеи, пожелания или общий отзыв.",
    formNote: "Мы автоматически добавим страницу, на которой вы находитесь, и время отправки.",
    shortTitle: "Краткий заголовок",
    expected: "Что вы ожидали? (необязательно)",
    bugDetails: "Что произошло? Опишите подробно, чтобы мы могли это повторить.",
    feedbackDetails: "Что сделает VIRORA лучше для вас?",
    attach: "Прикрепить скриншот (необязательно)",
    attached: "Скриншот прикреплён: {name}",
    remove: "Убрать",
    back: "Назад",
    send: "Отправить",
    sending: "Отправка…",
    thanks: "Спасибо",
    sentBug: "Ваше сообщение об ошибке отправлено команде VIRORA.",
    sentFeedback: "Ваш отзыв отправлен команде VIRORA.",
    done: "Готово",
    errImage: "Пожалуйста, выберите изображение.",
    errSize: "Скриншот должен быть не больше 10 МБ.",
    errBugEmpty: "Добавьте заголовок и опишите проблему.",
    errFeedbackEmpty: "Пожалуйста, напишите отзыв.",
    errSend: "Не удалось отправить. Попробуйте ещё раз.",
  },
};
