// App walkthrough copy (en/uz/ru). Step ids must match STEPS in AppTour.jsx.

export const TOUR_COPY = {
  en: {
    next: "Next",
    back: "Back",
    skip: "Skip tour",
    finish: "Let's go",
    counter: "{n} of {total}",
    replay: "Replay app tour",
    helpTitle: "Take the app tour",
    helpDesc: "A 1-minute walkthrough of VIRORA.",
    steps: {
      welcome: { title: "Welcome to VIRORA", body: "Let's take a 1-minute tour so you know where everything is. You can replay it any time from Help or Settings." },
      home: { title: "Home", body: "Your daily base. Homework from your teacher, your progress, your streak and quick actions all live here." },
      missions: { title: "Today's mission", body: "Four small goals every day. Finish them to keep your streak alive." },
      skillhub: { title: "Skill Hub", body: "This is where you practise. Every skill is a branch on your skill tree." },
      stage: { title: "Your skill tree", body: "Tap Vocabulary or Grammar to open it, then tap a node to start a game. Branches marked \"soon\" are on the way." },
      toolbar: { title: "XP, My Words and modes", body: "You earn XP in every game. My Words keeps the words you save. Practice mode is on now; Learn mode is coming soon." },
      deep: { title: "Deep Mode (coming soon)", body: "Learn a word's whole family: meaning, prefixes, suffixes, synonyms, antonyms and word forms, then practise it with your AI teacher. Tap it any time for a preview." },
      settings: { title: "Settings", body: "Change your profile, language and theme. You'll also find your progress, the leaderboard and subscription plans here." },
      help: { title: "Need help?", body: "Report a bug, send us an idea, or replay this tour." },
      done: { title: "You're all set!", body: "Start with today's mission or jump into Skill Hub." },
    },
  },
  uz: {
    next: "Keyingi",
    back: "Orqaga",
    skip: "O'tkazib yuborish",
    finish: "Boshladik",
    counter: "{n} / {total}",
    replay: "Ilova bo'yicha sayohatni qayta ko'rish",
    helpTitle: "Ilova bo'yicha sayohat",
    helpDesc: "VIRORA bo'yicha 1 daqiqalik qo'llanma.",
    steps: {
      welcome: { title: "VIRORA'ga xush kelibsiz", body: "Hamma narsa qayerdaligini bilishingiz uchun 1 daqiqalik qisqa sayohat qilamiz. Uni istalgan vaqtda Yordam yoki Sozlamalar orqali qayta ko'rishingiz mumkin." },
      home: { title: "Bosh sahifa", body: "Kundalik bazangiz. O'qituvchingiz bergan uy vazifalari, natijalaringiz, streak va tezkor amallar shu yerda." },
      missions: { title: "Bugungi vazifa", body: "Har kuni to'rtta kichik maqsad. Streak uzilmasligi uchun ularni bajaring." },
      skillhub: { title: "Skill Hub", body: "Bu yerda mashq qilasiz. Har bir ko'nikma ko'nikmalar daraxtingizdagi bitta shox." },
      stage: { title: "Ko'nikmalar daraxti", body: "Vocabulary yoki Grammar'ni oching, so'ng o'yinni boshlash uchun tugunni bosing. \"soon\" belgili shoxlar tez orada qo'shiladi." },
      toolbar: { title: "XP, Mening so'zlarim va rejimlar", body: "Har bir o'yinda XP to'playsiz. Mening so'zlarim saqlagan so'zlaringizni jamlaydi. Hozir Practice rejimi ishlaydi, Learn rejimi tez orada." },
      deep: { title: "Deep Mode (tez orada)", body: "So'zning butun oilasini o'rganing: ma'nosi, old va keyingi qo'shimchalari, sinonim, antonim va shakllari, keyin uni AI ustoz bilan mashq qiling. Oldindan ko'rish uchun istalgan vaqtda bosing." },
      settings: { title: "Sozlamalar", body: "Profilingiz, til va mavzuni o'zgartiring. Bu yerda natijalaringiz, reyting jadvali va obuna tariflari ham bor." },
      help: { title: "Yordam kerakmi?", body: "Xato haqida xabar bering, g'oyangizni yuboring yoki bu sayohatni qayta ko'ring." },
      done: { title: "Hammasi tayyor!", body: "Bugungi vazifadan boshlang yoki Skill Hub'ga o'ting." },
    },
  },
  ru: {
    next: "Далее",
    back: "Назад",
    skip: "Пропустить",
    finish: "Поехали",
    counter: "{n} из {total}",
    replay: "Пройти тур по приложению снова",
    helpTitle: "Тур по приложению",
    helpDesc: "Минутное знакомство с VIRORA.",
    steps: {
      welcome: { title: "Добро пожаловать в VIRORA", body: "Давайте за 1 минуту покажем, где что находится. Тур можно пройти снова в любое время через «Помощь» или «Настройки»." },
      home: { title: "Главная", body: "Ваша база на каждый день: домашние задания от учителя, прогресс, серия дней и быстрые действия." },
      missions: { title: "Задание дня", body: "Четыре небольшие цели каждый день. Выполняйте их, чтобы не прерывать серию." },
      skillhub: { title: "Skill Hub", body: "Здесь вы тренируетесь. Каждый навык — это ветка вашего дерева навыков." },
      stage: { title: "Дерево навыков", body: "Откройте Vocabulary или Grammar, затем нажмите на узел, чтобы начать игру. Ветки с пометкой «soon» скоро появятся." },
      toolbar: { title: "XP, Мои слова и режимы", body: "XP начисляется за каждую игру. В «Мои слова» хранятся сохранённые слова. Сейчас работает режим Practice, режим Learn скоро появится." },
      deep: { title: "Deep Mode (скоро)", body: "Изучайте всю семью слова: значение, приставки, суффиксы, синонимы, антонимы и формы, а затем практикуйтесь с ИИ-учителем. Нажмите в любое время, чтобы посмотреть превью." },
      settings: { title: "Настройки", body: "Меняйте профиль, язык и тему. Здесь же ваш прогресс, рейтинг и тарифы подписки." },
      help: { title: "Нужна помощь?", body: "Сообщите об ошибке, отправьте идею или пройдите этот тур снова." },
      done: { title: "Всё готово!", body: "Начните с задания дня или переходите в Skill Hub." },
    },
  },
};
