// UI labels for the Deep Mode word map (en/uz/ru). Word content stays English.

export const DEEP_MAP_COPY = {
  en: {
    brandSub: "Word family map",
    vocab: "Vocabulary", grammar: "Grammar", soon: "soon",
    preview: "Preview · 3 sample words",
    branches: { meaning: "Meaning", syn: "Synonyms", ant: "Antonyms", forms: "Word forms", context: "In context", root: "Root", affixes: "Affixes" },
    pos: { noun: "noun", verb: "verb", adjective: "adjective", adverb: "adverb" },
    of4: "{n} of 4",
    noForm: "No such form",
    atLevel: "At your level · {level}",
    inLang: "In your language",
    formMeaning: "Meaning · {pos}",
    example: "Example",
    prefix: "Prefix", suffix: "Suffix", suffixIn: "Suffix in {w}",
    alsoIn: "{a} = {m} · also in",
    noAffix: "No prefix or suffix",
    origin: "Origin", story: "The story", sameRoot: "Same root",
    synonym: "synonym", related: "related",
    howClose: "How close it is", howDiffers: "How it differs",
    opposite: "opposite", note: "Note", noAntonym: "No true antonym",
    contextCard: "The family in a short text",
    try: "Try",
    hint: "Tap a branch to grow it. Drag to move, pinch to zoom.",
    fit: "Show the whole map",
    grammarTitle: "Grammar Deep Mode",
    grammarBody: "The same map, for grammar: how a structure is built, when to use it, the mistakes Uzbek and Russian speakers make, and practice with your AI teacher.",
    backVocab: "Back to vocabulary",
    stageLabel: "Word family map. Tap a branch to grow it.",
    familyOf: "family of {w}",
    hereLabel: "{pos} · centre",
    explore: "Explore {w} →",
    backTo: "Back to {w}",
  },
  uz: {
    brandSub: "So'z oilasi xaritasi",
    vocab: "Lug'at", grammar: "Grammatika", soon: "tez orada",
    preview: "Namuna · 3 ta so'z",
    branches: { meaning: "Ma'nosi", syn: "Sinonimlar", ant: "Antonimlar", forms: "So'z shakllari", context: "Kontekstda", root: "Kelib chiqishi", affixes: "Qo'shimchalar" },
    pos: { noun: "ot", verb: "fe'l", adjective: "sifat", adverb: "ravish" },
    of4: "4 tadan {n}",
    noForm: "Bunday shakl yo'q",
    atLevel: "Sizning darajangizda · {level}",
    inLang: "Sizning tilingizda",
    formMeaning: "Ma'nosi · {pos}",
    example: "Misol",
    prefix: "Old qo'shimcha", suffix: "Qo'shimcha", suffixIn: "{w} so'zidagi qo'shimcha",
    alsoIn: "{a} = {m} · yana",
    noAffix: "Old yoki keyingi qo'shimcha yo'q",
    origin: "Kelib chiqishi", story: "Tarixi", sameRoot: "O'zakdosh so'zlar",
    synonym: "sinonim", related: "o'xshash",
    howClose: "Qanchalik yaqin", howDiffers: "Farqi nimada",
    opposite: "qarama-qarshi", note: "Izoh", noAntonym: "Aniq antonimi yo'q",
    contextCard: "So'z oilasi qisqa matnda",
    try: "Sinab ko'ring",
    hint: "Shoxni bosing va u o'sadi. Surish uchun torting, kattalashtirish uchun chimchilang.",
    fit: "Butun xaritani ko'rsatish",
    grammarTitle: "Grammatika uchun Deep Mode",
    grammarBody: "Xuddi shu xarita, grammatika uchun: tuzilma qanday quriladi, qachon ishlatiladi, o'zbek va rus tilida so'zlashuvchilar qanday xatolarga yo'l qo'yadi va AI ustoz bilan mashq.",
    backVocab: "Lug'atga qaytish",
    stageLabel: "So'z oilasi xaritasi. Shoxni bosing va u o'sadi.",
    familyOf: "{w} oilasi",
    hereLabel: "{pos} · markazda",
    explore: "{w} ni o'rganish →",
    backTo: "{w} ga qaytish",
  },
  ru: {
    brandSub: "Карта семьи слова",
    vocab: "Лексика", grammar: "Грамматика", soon: "скоро",
    preview: "Превью · 3 слова",
    branches: { meaning: "Значение", syn: "Синонимы", ant: "Антонимы", forms: "Формы слова", context: "В контексте", root: "Корень", affixes: "Аффиксы" },
    pos: { noun: "сущ.", verb: "глагол", adjective: "прил.", adverb: "наречие" },
    of4: "{n} из 4",
    noForm: "Такой формы нет",
    atLevel: "На вашем уровне · {level}",
    inLang: "На вашем языке",
    formMeaning: "Значение · {pos}",
    example: "Пример",
    prefix: "Приставка", suffix: "Суффикс", suffixIn: "Суффикс в {w}",
    alsoIn: "{a} = {m} · также в",
    noAffix: "Нет приставки или суффикса",
    origin: "Происхождение", story: "История слова", sameRoot: "Однокоренные",
    synonym: "синоним", related: "близкое",
    howClose: "Насколько близко", howDiffers: "Чем отличается",
    opposite: "противоположное", note: "Заметка", noAntonym: "Нет точного антонима",
    contextCard: "Семья слова в коротком тексте",
    try: "Попробуйте",
    hint: "Нажмите на ветку, чтобы она выросла. Перетаскивайте карту, щипок меняет масштаб.",
    fit: "Показать всю карту",
    grammarTitle: "Deep Mode для грамматики",
    grammarBody: "Та же карта для грамматики: как строится конструкция, когда её использовать, какие ошибки делают носители узбекского и русского, и практика с ИИ-учителем.",
    backVocab: "Вернуться к лексике",
    stageLabel: "Карта семьи слова. Нажмите на ветку, чтобы она выросла.",
    familyOf: "семья слова {w}",
    hereLabel: "{pos} · в центре",
    explore: "Изучить {w} →",
    backTo: "Назад к {w}",
  },
};

export const fill = (s, vars) => String(s).replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? ""));
