// Deep Mode "coming soon" screen copy (en/uz/ru). Deep Mode replaces the old
// student AI Teacher tab (Tee, 2026-10-05): instead of a chat that answers
// "what does X mean?" (which Google already does), the connected LLM will
// build each word's full family and then practise it with the learner.
// The example word map below is static, hand-checked content.

export const DEEP_MODE_COPY = {
  en: {
    badge: "Coming soon",
    title: "Deep Mode",
    tagline: "Don't just learn a word. Learn its whole family.",
    intro:
      "A dictionary tells you what a word means. Deep Mode shows you how it works: how it is built, how it changes, and how to use every form of it correctly. Your AI teacher builds the map, then practises it with you.",
    previewTitle: "Try it now",
    previewBody: "Explore three sample words. The full word library is coming soon.",
    exampleLabel: "Example",
    definitionLabel: "Meaning",
    definition: "to join things or people together so they become one",
    prefixLabel: "Prefix",
    prefixValue: "uni- = one",
    prefixAlso: "also in: uniform, unique, universe",
    suffixLabel: "Suffix",
    suffixValue: "-fy = make",
    suffixAlso: "also in: simplify, clarify, beautify",
    synonymsLabel: "Synonyms",
    antonymsLabel: "Antonyms",
    formsLabel: "Word forms",
    noun: "Noun",
    verb: "Verb",
    adjective: "Adjective",
    adverb: "Adverb",
    noAdverb: "none in common use",
    formsNote: "Not every word has all four forms. Deep Mode tells you honestly instead of inventing one.",
    howTitle: "How it will work",
    step1Title: "Explore",
    step1Body: "Open a word and see its full map: meaning, prefixes and suffixes, synonyms, antonyms and every word form with its own meaning.",
    step2Title: "Practise with your AI teacher",
    step2Body: "Use each form in your own sentences and get instant feedback. Ask why one word fits and another doesn't, in English, Uzbek or Russian.",
    step3Title: "Track it",
    step3Body: "See which words you've explored and practised, so nothing you learn gets lost.",
    meanwhile: "Until then, keep building your vocabulary in Skill Hub.",
    cta: "Go to Skill Hub",
  },
  uz: {
    badge: "Tez orada",
    title: "Deep Mode",
    tagline: "Faqat so'zni emas, uning butun oilasini o'rganing.",
    intro:
      "Lug'at so'z nimani anglatishini aytadi. Deep Mode esa so'z qanday ishlashini ko'rsatadi: u qanday tuzilgan, qanday o'zgaradi va uning har bir shaklini qanday to'g'ri ishlatish kerak. AI ustozingiz so'z xaritasini tuzadi, keyin siz bilan birga mashq qiladi.",
    previewTitle: "Hozir sinab ko'ring",
    previewBody: "Uchta namunaviy so'zni o'rganing. To'liq so'z kutubxonasi tez orada.",
    exampleLabel: "Misol",
    definitionLabel: "Ma'nosi",
    definition: "narsalarni yoki odamlarni bir butun qilib birlashtirmoq",
    prefixLabel: "Old qo'shimcha",
    prefixValue: "uni- = bir",
    prefixAlso: "yana: uniform, unique, universe",
    suffixLabel: "Qo'shimcha",
    suffixValue: "-fy = qilmoq",
    suffixAlso: "yana: simplify, clarify, beautify",
    synonymsLabel: "Sinonimlar",
    antonymsLabel: "Antonimlar",
    formsLabel: "So'z shakllari",
    noun: "Ot",
    verb: "Fe'l",
    adjective: "Sifat",
    adverb: "Ravish",
    noAdverb: "keng qo'llanmaydi",
    formsNote: "Har bir so'zning to'rtala shakli ham bo'lavermaydi. Deep Mode yo'q shaklni o'ylab topmaydi, rostini aytadi.",
    howTitle: "Qanday ishlaydi",
    step1Title: "O'rganing",
    step1Body: "So'zni oching va uning to'liq xaritasini ko'ring: ma'nosi, old va keyingi qo'shimchalari, sinonim va antonimlari hamda har bir shaklning o'z ma'nosi.",
    step2Title: "AI ustoz bilan mashq qiling",
    step2Body: "Har bir shaklni o'z gaplaringizda ishlating va darhol fikr-mulohaza oling. Nega bir so'z mos kelib, boshqasi mos kelmasligini ingliz, o'zbek yoki rus tilida so'rang.",
    step3Title: "Kuzatib boring",
    step3Body: "Qaysi so'zlarni o'rganganingiz va mashq qilganingizni ko'ring, shunda o'rganganlaringiz yo'qolib ketmaydi.",
    meanwhile: "Hozircha Skill Hub'da so'z boyligingizni oshirishda davom eting.",
    cta: "Skill Hub'ga o'tish",
  },
  ru: {
    badge: "Скоро",
    title: "Deep Mode",
    tagline: "Учите не просто слово, а всю его семью.",
    intro:
      "Словарь говорит, что слово значит. Deep Mode показывает, как оно работает: как оно устроено, как меняется и как правильно использовать каждую его форму. ИИ-учитель строит карту слова, а потом тренирует её вместе с вами.",
    previewTitle: "Попробуйте сейчас",
    previewBody: "Изучите три слова-примера. Полная библиотека слов скоро появится.",
    exampleLabel: "Пример",
    definitionLabel: "Значение",
    definition: "объединять вещи или людей в одно целое",
    prefixLabel: "Приставка",
    prefixValue: "uni- = один",
    prefixAlso: "также в: uniform, unique, universe",
    suffixLabel: "Суффикс",
    suffixValue: "-fy = делать",
    suffixAlso: "также в: simplify, clarify, beautify",
    synonymsLabel: "Синонимы",
    antonymsLabel: "Антонимы",
    formsLabel: "Формы слова",
    noun: "Сущ.",
    verb: "Глагол",
    adjective: "Прил.",
    adverb: "Наречие",
    noAdverb: "не употребляется",
    formsNote: "Не у каждого слова есть все четыре формы. Deep Mode честно скажет об этом, а не придумает несуществующую.",
    howTitle: "Как это будет работать",
    step1Title: "Изучайте",
    step1Body: "Откройте слово и увидите его полную карту: значение, приставки и суффиксы, синонимы, антонимы и каждую форму слова с её значением.",
    step2Title: "Практикуйтесь с ИИ-учителем",
    step2Body: "Используйте каждую форму в своих предложениях и сразу получайте обратную связь. Спрашивайте, почему одно слово подходит, а другое нет, на английском, узбекском или русском.",
    step3Title: "Отслеживайте",
    step3Body: "Смотрите, какие слова вы уже изучили и отработали, чтобы ничего не потерялось.",
    meanwhile: "А пока продолжайте пополнять словарный запас в Skill Hub.",
    cta: "Перейти в Skill Hub",
  },
};
