import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("conditionals-wishes");
const A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR");

export default [
  // ---------------- A2 ---------------- (domain introduced at A2)
  d.mcq({ b: "zero-first", t: "zero-general-truth", L: "A2", diff: 1, focus: "Zero conditional: present simple in both clauses", pre: ["zero-conditional", "present-simple"],
    prompt: "If you heat ice, it ______.", options: ["melts", "will melt", "melted", "is melting"], key: 0, why: "General truth → present simple.", legacy: A2("If you heat ice, it ______.") }),
  d.mcq({ b: "zero-first", t: "first-will", L: "A2", diff: 1, focus: "First conditional: will in the result clause", pre: ["first-conditional", "future-will"],
    prompt: "If it rains tomorrow, we ______ at home.", options: ["stay", "stayed", "will stay", "have stayed"], key: 2, why: "Real future → will + base.", legacy: A2("If it rains tomorrow, we ______ at home.") }),
  d.mcq({ b: "zero-first", t: "first-will", L: "A2", diff: 2, focus: "First conditional with a negative if-clause", pre: ["first-conditional"],
    prompt: "If you don't hurry, you ______ the bus.", options: ["miss", "will miss", "missed", "are missing"], key: 1, why: "Result → will miss.", legacy: A2("If you don't hurry, you ______ the bus.") }),
  d.gap({ b: "zero-first", t: "first-if-clause", L: "A2", diff: 2, focus: "Present simple (not will) in the if-clause", pre: ["first-conditional", "present-simple"],
    source: "If she ______ (pass) the exam, her parents will buy her a bike.", key: "passes", why: "If-clause → present simple." }),
  d.correct({ b: "zero-first", t: "first-if-clause", L: "A2", diff: 2, focus: "No 'will' in the if-clause", pre: ["first-conditional"],
    source: "If it will be sunny tomorrow, we will go to the beach.", key: "If it is sunny tomorrow, we will go to the beach.", alt: ["If it's sunny tomorrow, we will go to the beach.", "If it is sunny tomorrow, we'll go to the beach."], why: "Present simple after if." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "zero-first", t: "zero-general-truth", L: "B1", diff: 1, focus: "Zero (not first) conditional for a general consequence", pre: ["zero-conditional"],
    prompt: "If you don't water plants, they ______.", options: ["will die", "died", "die", "are dying"], key: 2, why: "Always true → present simple.", legacy: B1("If you don't water plants, they ______."),
    flags: ["'will die' is also natural here (first conditional reading). Legacy key kept; stem would benefit from an 'in general' anchor before mass use."] }),
  d.mcq({ b: "second", t: "if-i-were-you", L: "B1", diff: 1, focus: "would + base in the second conditional result", pre: ["second-conditional", "past-simple"],
    prompt: "If I were you, I ______ for that job.", options: ["apply", "will apply", "would apply", "applied"], key: 2, why: "Hypothetical → would.", legacy: B1("If I were you, I ______ for that job.") }),
  d.mcq({ b: "second", t: "second-if-clause", L: "B1", diff: 2, focus: "Past simple in the second-conditional if-clause", pre: ["second-conditional", "past-simple"],
    prompt: "What would you do if you ______ a million dollars?", options: ["win", "won", "will win", "have won"], key: 1, why: "would ... if + past simple.", legacy: B1("What would you do if you ______ a million dollars?") }),
  d.mcq({ b: "linkers", t: "unless", L: "B1", diff: 2, focus: "unless = if not", pre: ["unless"],
    prompt: "You won't pass the exam ______ you study more.", options: ["if", "unless", "although", "because"], key: 1, why: "Negative condition → unless.", legacy: B1("You won't pass the exam ______ you study more.") }),
  d.gap({ b: "second", t: "second-if-clause", L: "B1", diff: 2, focus: "Producing both halves of a second conditional", pre: ["second-conditional"],
    source: "If I ______ (have) more free time, I ______ (learn) to play the piano.", key: ["had", "would learn"], alt: [["had", "'d learn"]], why: "if + past simple, would + base." }),
  d.rewrite({ b: "linkers", t: "unless", L: "B1", diff: 2, focus: "if ... not → unless", pre: ["unless", "first-conditional"],
    source: "If you don't leave now, you will miss the train.", hint: "Unless ______, you will miss the train.", key: "you leave now", why: "unless removes the negation." }),
  d.guided({ b: "second", t: "if-i-were-you", L: "B1", diff: 2, focus: "Productive second conditional with 'If I were'", pre: ["second-conditional"],
    prompt: "Write one sentence beginning with 'If I were...' and describe what you would do.", required: "second conditional beginning with 'If I were...' followed by would + base verb",
    legacy: B1O("Write one sentence beginning with 'If I were...' and describe what you would do.") }),
  d.guided({ b: "linkers", t: "unless", L: "B1", diff: 2, focus: "Productive unless", pre: ["unless"],
    prompt: "Write one sentence using unless to describe a condition for a future situation.", required: "unless + present simple used correctly to express a negative condition",
    legacy: B1O("Write one sentence using unless to describe a condition for a future situation.") }),

  // ---------------- B2 ----------------
  d.mcq({ b: "second", t: "second-result", L: "B2", diff: 1, focus: "Second conditional result for a present hypothetical", pre: ["second-conditional"],
    prompt: "If I had more time, I ______ another language.", options: ["learn", "will learn", "would learn", "had learned"], key: 2, why: "Present unreal → would.", legacy: B2("If I had more time, I ______ another language.") }),
  d.mcq({ b: "third", t: "third-result", L: "B2", diff: 2, focus: "would have + pp in the third conditional", pre: ["third-conditional", "past-perfect"],
    prompt: "If you had told me, I ______ you.", options: ["would help", "would have helped", "helped", "will help"], key: 1, why: "Past unreal → would have + pp.", legacy: B2("If you had told me, I ______ you.") }),
  d.mcq({ b: "mixed", t: "past-condition-present-result", L: "B2", diff: 3, focus: "Mixed: past perfect condition + present (would + base) result", pre: ["mixed-conditional", "third-conditional", "second-conditional"],
    prompt: "If I had studied medicine, I ______ a doctor now.", options: ["am", "would be", "would have been", "was"], key: 1, why: "'now' → present result → would be.", legacy: B2("If I had studied medicine, I ______ a doctor now.") }),
  d.gap({ b: "mixed", t: "past-condition-present-result", L: "B2", diff: 3, focus: "Producing a mixed conditional", pre: ["mixed-conditional", "past-perfect"],
    source: "If I ______ (take) the earlier train, I ______ (be) at the meeting now.", key: ["had taken", "would be"], alt: [["had taken", "'d be"]], why: "Past condition, present result." }),
  d.mcq({ b: "linkers", t: "provided-that", L: "B2", diff: 2, focus: "provided that = on condition that", pre: ["conditional-linkers"],
    prompt: "You may use my car ______ you drive carefully.", options: ["unless", "provided that", "otherwise", "despite"], key: 1, why: "Positive condition → provided that.", legacy: B2("You may use my car ______ you drive carefully.") }),
  d.mcq({ b: "wishes-preference", t: "wish-past-perfect", L: "B2", diff: 2, focus: "wish + past perfect for past regret", pre: ["wish-unreal-past", "past-perfect"],
    prompt: "I wish I ______ more attention during the lesson.", options: ["paid", "had paid", "have paid", "would pay"], key: 1, why: "Regret about the past → past perfect.", legacy: B2("I wish I ______ more attention during the lesson.") }),
  d.mcq({ b: "wishes-preference", t: "would-rather-past", L: "B2", diff: 2, focus: "would rather + subject + past simple for another person's action", pre: ["would-rather"],
    prompt: "I'd rather you ______ anyone about this.", options: ["don't tell", "didn't tell", "won't tell", "haven't told"], key: 1, why: "would rather + sb + past simple.", legacy: B2("I'd rather you ______ anyone about this.") }),
  d.mcq({ b: "wishes-preference", t: "wish-present", L: "B2", diff: 1, focus: "wish + past simple for a present unreal situation", pre: ["wish-unreal-present", "past-simple"],
    prompt: "I wish I ______ how to swim — the sea looks wonderful.", options: ["know", "knew", "had known", "would know"], key: 1, why: "Present wish → past simple." }),
  d.mcq({ b: "wishes-preference", t: "wish-would", L: "B2", diff: 2, focus: "wish + would for an annoying habit of another person", pre: ["wish-would"],
    prompt: "I wish my neighbours ______ playing loud music at night.", options: ["stopped", "would stop", "will stop", "had stopped"], key: 1, why: "Complaint about others' behaviour → wish + would." }),
  d.rewrite({ b: "third", t: "third-result", L: "B2", diff: 2, focus: "Producing a third conditional from two past facts", pre: ["third-conditional"],
    source: "I didn't set my alarm, so I missed the bus.", hint: "If I ______, I ______ the bus.", key: ["had set my alarm", "wouldn't have missed"], alt: [["had set my alarm", "would not have missed"]], why: "if + past perfect, would have + pp." }),
  d.mcq({ b: "linkers", t: "in-case", L: "B2", diff: 2, focus: "in case (precaution) vs if (condition)", pre: ["conditional-linkers"],
    prompt: "Take an umbrella ______ it rains.", options: ["in case", "if", "unless", "so that"], key: 0, why: "Precaution against a possibility → in case." }),
  d.guided({ b: "third", t: "third-result", L: "B2", diff: 2, focus: "Productive third conditional", pre: ["third-conditional"],
    prompt: "Describe a past situation you wish had happened differently. Use the third conditional.", required: "third conditional: if + past perfect, would have + past participle, expressing past regret",
    legacy: B2O("Describe a past situation you wish had happened differently. Use the third conditional.") }),
  d.guided({ b: "mixed", t: "past-condition-present-result", L: "B2", diff: 3, focus: "Productive mixed conditional", pre: ["mixed-conditional"],
    prompt: "Write a mixed conditional connecting a different past event with a present result.", required: "a mixed conditional correctly combining a past condition (past perfect) with a present result (would + base verb)",
    legacy: B2O("Write a mixed conditional connecting a different past event with a present result.") }),
  d.guided({ b: "wishes-preference", t: "would-rather-past", L: "B2", diff: 2, focus: "Productive would rather + subject + past simple", pre: ["would-rather"],
    prompt: "Write one sentence expressing a preference about another person's present or future action. Use would rather + subject + past simple.", required: "would rather + subject + past simple expressing a preference about someone else's action",
    legacy: B2O("Write one sentence expressing a preference about another person's present or future action. Use would rather + subject + past simple.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "inverted", t: "had-inversion", L: "C1", diff: 1, focus: "Inverted third conditional: Had + subject + pp", pre: ["inverted-conditional", "third-conditional", "subject-auxiliary-inversion"],
    prompt: "______ I known about the problem, I would have acted sooner.", options: ["Had", "Have", "Did", "Were"], key: 0, why: "If I had known → Had I known.", legacy: B2("______ I known about the problem, I would have acted sooner."),
    flags: ["cefr-conflict: legacy pool B2; placed at C1 per provisional ruling."], overlaps: ["sentence-structure"] }),
  d.rewrite({ b: "inverted", t: "were-inversion", L: "C1", diff: 2, focus: "Were + subject + to-infinitive for a formal hypothetical", pre: ["inverted-conditional", "second-conditional"],
    source: "If the company lost this contract, hundreds of jobs would be at risk.", hint: "Were ______, hundreds of jobs would be at risk.", key: "the company to lose this contract", why: "If X did → Were X to do." }),
  d.rewrite({ b: "inverted", t: "should-inversion", L: "C1", diff: 2, focus: "Should + subject for a formal open condition", pre: ["inverted-conditional", "first-conditional"],
    source: "If you need any further information, please contact our office.", hint: "Should ______, please contact our office.", key: "you need any further information", why: "If you (should) need → Should you need." }),
  d.mcq({ b: "wishes-preference", t: "its-time", L: "C1", diff: 2, focus: "It's (high) time + past simple", pre: ["wish-unreal-present"],
    prompt: "It's high time the government ______ something about the housing crisis.", options: ["did", "does", "will do", "has done"], key: 0, why: "It's time + unreal past." }),
  d.mcq({ b: "wishes-preference", t: "as-if-unreal", L: "C1", diff: 2, focus: "as if + past perfect for an unreal past comparison", pre: ["as-if", "past-perfect"],
    prompt: "He talks about the trip as if he ______ there himself, but he never left the country.", options: ["had been", "has been", "was being", "is"], key: 0, why: "Contrary to fact, past → as if + past perfect." }),
  d.gap({ b: "linkers", t: "implied-conditional", L: "C1", diff: 3, focus: "Implied condition with 'but for' / 'otherwise'", pre: ["implied-conditional", "third-conditional"],
    instr: "Complete the gap with TWO words so the sentence means 'if it had not been for your help'.", source: "______ ______ your help, we would never have finished on time.", key: ["But", "for"], why: "But for + noun = if it hadn't been for." }),
  d.mcq({ b: "mixed", t: "present-condition-past-result", L: "C1", diff: 3, focus: "Mixed: present/general condition (past simple) with a past result", pre: ["mixed-conditional"],
    prompt: "If she ______ so stubborn, she would have accepted their help last year.", options: ["weren't", "hadn't been", "isn't", "wouldn't be"], key: 0, why: "A permanent present characteristic → past simple; result is past." }),
  d.guided({ b: "inverted", t: "had-inversion", L: "C1", diff: 2, focus: "Productive inverted third conditional", pre: ["inverted-conditional"],
    prompt: "Rewrite an ordinary third conditional using Had + subject + past participle, without using if.", required: "inverted third conditional: Had + subject + past participle, ..., would have + past participle, with no 'if'",
    legacy: B2O("Rewrite an ordinary third conditional using Had + subject + past participle, without using if."), flags: ["cefr-conflict: legacy pool B2; placed at C1 per provisional ruling."] }),

  // ---------------- C2 ----------------
  d.rewrite({ b: "inverted", t: "were-it-not-for", L: "C2", diff: 2, focus: "'Were it not for / Had it not been for' inverted implied conditional", pre: ["inverted-conditional", "implied-conditional"],
    source: "If it had not been for the quick reaction of the pilot, the plane would have crashed.", hint: "Had ______, the plane would have crashed.", key: "it not been for the quick reaction of the pilot", why: "Inversion + negative + 'for' phrase.",
    flags: ["c2-check: combines inversion, negation placement and an implied-condition idiom in one clause. C2 provisional."] }),
  d.mcq({ b: "wishes-preference", t: "would-sooner-perfect", L: "C2", diff: 3, focus: "would rather/sooner + perfect infinitive for a past preference about one's own action", pre: ["would-rather", "perfect-infinitive"],
    prompt: "I ______ stayed at home last night — the party was dreadful.", options: ["would rather have", "would rather had", "would rather", "had rather"], key: 0, why: "Own past action → would rather have + pp.", overlaps: ["verb-patterns"],
    flags: ["c2-check: contrast with B2 'would rather + sb + past simple'; the perfect-infinitive form is late-acquired. C2 provisional (upper C1 possible)."] }),
];