import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("modals");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), C1 = leg("C1_MCQ"), B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR"), C1O = leg("C1_OPEN_GRAMMAR");

export default [
  // ---------------- A1 ----------------
  d.mcq({ b: "ability-permission", t: "can-ability", L: "A1", diff: 1, focus: "can + base verb for ability", pre: ["modal-base-form", "ability-modals"],
    prompt: "I ______ swim.", options: ["can", "am", "do", "have"], key: 0, why: "Ability → can.", legacy: A1("I ______ swim.") }),
  d.mcq({ b: "ability-permission", t: "can-form", L: "A1", diff: 2, focus: "Modal takes no -s and no 'to'", pre: ["modal-base-form"],
    prompt: "She ______ speak French.", options: ["can to", "cans", "can", "is can"], key: 2, why: "Modals are invariable: can.", legacy: A1("She ______ speak French.") }),
  d.mcq({ b: "ability-permission", t: "can-request", L: "A1", diff: 1, focus: "Can for a request", pre: ["modal-base-form", "permission-modals"],
    prompt: "______ you help me?", options: ["Do", "Can", "Are", "Have"], key: 1, why: "Request → Can you.", legacy: A1("______ you help me?") }),
  d.mcq({ b: "ability-permission", t: "cant-ability", L: "A1", diff: 1, focus: "can't for lack of ability; no 'doesn't'", pre: ["modal-base-form", "ability-modals"],
    prompt: "He ______ drive. He is only 12.", options: ["can", "can't", "doesn't can", "isn't"], key: 1, why: "Negative ability → can't.", legacy: A1("He ______ drive. He is only 12.") }),
  d.order({ b: "ability-permission", t: "can-question", L: "A1", diff: 2, focus: "Modal question: can + subject + verb", pre: ["modal-base-form", "subject-auxiliary-inversion"],
    tokens: ["play", "can", "the guitar", "you", "?"], key: ["can", "you", "play", "the guitar", "?"], why: "Modal + S + V." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "obligation", t: "must", L: "A2", diff: 1, focus: "must for strong obligation", pre: ["obligation-modals"],
    prompt: "You ______ wear a seatbelt in a car.", options: ["must", "might", "could", "would"], key: 0, why: "Law/rule → must.", legacy: A2("You ______ wear a seatbelt in a car.") }),
  d.mcq({ b: "advice", t: "should", L: "A2", diff: 1, focus: "should for advice", pre: ["advice-modals"],
    prompt: "You ______ see a doctor if you feel worse.", options: ["should", "can't", "mustn't", "would"], key: 0, why: "Advice → should.", legacy: A2("You ______ see a doctor if you feel worse.") }),
  d.mcq({ b: "ability-permission", t: "could-past-ability", L: "A2", diff: 1, focus: "could for past ability", pre: ["ability-modals"],
    prompt: "When I was five, I ______ swim.", options: ["can", "could", "must", "should"], key: 1, why: "Past ability → could.", legacy: A2("When I was five, I ______ swim.") }),
  d.mcq({ b: "deduction", t: "might-possibility", L: "A2", diff: 1, focus: "might for possibility", pre: ["deduction-modals"],
    prompt: "It is possible that Anna ______ come later.", options: ["must", "should", "might", "has to"], key: 2, why: "Possibility → might.", legacy: A2("It is possible that Anna ______ come later.") }),
  d.mcq({ b: "obligation", t: "mustnt-vs-dont-have-to", L: "A2", diff: 2, focus: "mustn't (prohibition) vs don't have to (no obligation)", pre: ["obligation-modals"],
    prompt: "You ______ park here. It is not allowed.", options: ["don't have to", "mustn't", "might not", "shouldn't to"], key: 1, why: "Prohibition → mustn't.", legacy: A2("You ______ park here. It is not allowed.") }),
  d.mcq({ b: "semi-modals", t: "have-to", L: "A2", diff: 1, focus: "have to for external necessity", pre: ["semi-modals", "obligation-modals"],
    prompt: "You ______ bring your passport. It is necessary for the trip.", options: ["have to", "might", "could", "don't have"], key: 0, why: "External necessity → have to.", legacy: A2("You ______ bring your passport. It is necessary for the trip.") }),
  d.gap({ b: "obligation", t: "mustnt-vs-dont-have-to", L: "A2", diff: 2, focus: "don't have to = not necessary", pre: ["obligation-modals", "semi-modals"],
    instr: "Complete the gap with mustn't or don't have to.", source: "It's a casual party, so you ______ wear a suit.", key: "don't have to", why: "No obligation → don't have to." }),
  d.correct({ b: "ability-permission", t: "can-form", L: "A2", diff: 2, focus: "Modal + bare infinitive (no 'to')", pre: ["modal-base-form"],
    source: "We must to finish the project by Friday.", key: "We must finish the project by Friday.", why: "Modal + base form." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "deduction", t: "must-present", L: "B1", diff: 1, focus: "must for a confident present deduction", pre: ["deduction-modals"],
    prompt: "The lights are on and his car is outside. He ______ be at home.", options: ["must", "might", "can't", "should"], key: 0, why: "Strong evidence → must.", legacy: B1("The lights are on and his car is outside. He ______ be at home.") }),
  d.mcq({ b: "deduction", t: "might-present", L: "B1", diff: 1, focus: "might for an uncertain deduction", pre: ["deduction-modals"],
    prompt: "She isn't answering. She ______ be busy.", options: ["mustn't", "might", "has to", "should have"], key: 1, why: "Uncertain → might.", legacy: B1("She isn't answering. She ______ be busy.") }),
  d.mcq({ b: "deduction", t: "cant-present", L: "B1", diff: 2, focus: "can't (not mustn't) for a negative deduction", pre: ["deduction-modals"],
    prompt: "That ______ be John. John is in Canada this week.", options: ["must", "should", "can't", "might"], key: 2, why: "Impossible → can't.", legacy: B1("That ______ be John. John is in Canada this week.") }),
  d.mcq({ b: "past-modals", t: "must-have", L: "B1", diff: 2, focus: "must have + past participle for a confident past deduction", pre: ["deduction-modals", "modal-perfect", "past-participle"],
    prompt: "The ground is wet. It ______ during the night.", options: ["must rain", "must have rained", "should rain", "can have rained"], key: 1, why: "Present evidence about the past → must have + pp.",
    legacy: B1("The ground is wet. It ______ have rained during the night.", "Legacy stem already contained 'have', so the key 'must have' produced 'must have have rained'. Stem rewritten to remove the duplicated auxiliary; the same distinction is tested.") }),
  d.mcq({ b: "past-modals", t: "might-have", L: "B1", diff: 2, focus: "might have + pp for an uncertain past possibility", pre: ["deduction-modals", "modal-perfect"],
    prompt: "He isn't here. He ______ the bus.", options: ["might have missed", "might miss", "must miss", "has to missed"], key: 0, why: "Past possibility → might have + pp.",
    legacy: B1("He isn't here. He ______ have missed the bus.", "Legacy stem contained 'have' before the gap while the key was 'might have', doubling the auxiliary. Stem rewritten; distinction unchanged.") }),
  d.mcq({ b: "past-modals", t: "should-have", L: "B1", diff: 2, focus: "should have + pp for past criticism", pre: ["advice-modals", "modal-perfect"],
    prompt: "You ______ told me about the problem earlier.", options: ["should", "should have", "must have", "could"], key: 1, why: "Criticism of a past omission → should have.", legacy: B1("You ______ told me about the problem earlier.") }),
  d.mcq({ b: "obligation", t: "modal-passive", L: "B1", diff: 3, focus: "Modal + be + pp when the subject receives the action", pre: ["obligation-modals", "modal-passive"],
    prompt: "All visitors ______ show identification at the entrance.", options: ["must be", "must", "must to", "are must"], key: 1, why: "Visitors perform the action → active 'must show'.",
    legacy: B1("All visitors ______ show identification at the entrance.", "Legacy key was 'must be', producing the ungrammatical 'must be show'. Key corrected to 'must' (active). The item now tests modal + bare infinitive against a spurious passive."), overlaps: ["passive-causative"] }),
  d.gap({ b: "semi-modals", t: "be-able-to", L: "B1", diff: 2, focus: "be able to where 'can' has no future/perfect form", pre: ["semi-modals", "ability-modals"],
    instr: "Complete the gap with a form of 'be able to'.", source: "I hope I ______ come to your wedding next year.", key: "will be able to", alt: ["'ll be able to", "am able to"], why: "Future ability → will be able to." }),
  d.correct({ b: "semi-modals", t: "have-to-past", L: "B1", diff: 2, focus: "Past obligation uses had to (must has no past form)", pre: ["semi-modals", "obligation-modals"],
    source: "Yesterday I must stay late at work.", key: "Yesterday I had to stay late at work.", why: "Past obligation → had to." }),
  d.guided({ b: "deduction", t: "must-present", L: "B1", diff: 1, focus: "Productive must for present deduction", pre: ["deduction-modals"],
    prompt: "Write one sentence making a strong deduction about a present situation. Use must.", required: "must + base verb for a strong present deduction",
    legacy: B1O("Write one sentence making a strong deduction about a present situation. Use must.") }),
  d.guided({ b: "past-modals", t: "should-have", L: "B1", diff: 2, focus: "Productive should have + pp for regret/criticism", pre: ["modal-perfect", "advice-modals"],
    prompt: "Write one sentence criticizing or expressing regret about a past action. Use should have.", required: "should have + past participle expressing regret or criticism about the past",
    legacy: B1O("Write one sentence criticizing or expressing regret about a past action. Use should have.") }),

  // ---------------- B2 ----------------
  d.mcq({ b: "deduction", t: "cant-present", L: "B2", diff: 1, focus: "can't for a negative deduction in an extended context", pre: ["deduction-modals"],
    prompt: "The lights are off and nobody is answering. They ______ be at home.", options: ["must", "can't", "should", "need"], key: 1, why: "Evidence against → can't.", legacy: B2("The lights are off and nobody is answering. They ______ be at home.") }),
  d.mcq({ b: "past-modals", t: "must-have", L: "B2", diff: 2, focus: "must have + pp from indirect evidence", pre: ["modal-perfect", "deduction-modals"],
    prompt: "She knew all the details. She ______ to him earlier.", options: ["must have spoken", "must speak", "should speak", "has to spoken"], key: 0, why: "Confident past deduction → must have + pp.",
    legacy: B2("She knew all the details. She ______ have spoken to him earlier.", "Duplicated 'have' in the legacy stem removed; key rewritten as the full perfect modal phrase.") }),
  d.mcq({ b: "past-modals", t: "neednt-have", L: "B2", diff: 2, focus: "needn't have + pp: done but unnecessary", pre: ["modal-perfect", "need-modal"],
    prompt: "You ______ bought any food. We already had plenty.", options: ["didn't need", "needn't have", "shouldn't", "don't need"], key: 1, why: "It was done and was unnecessary → needn't have.", legacy: B2("You ______ bought any food. We already had plenty.") }),
  d.mcq({ b: "past-modals", t: "should-have", L: "B2", diff: 1, focus: "should have + pp with a consequence clause", pre: ["modal-perfect", "advice-modals"],
    prompt: "You ______ told me about the change. I could have helped.", options: ["should have", "should", "must", "ought"], key: 0, why: "Past criticism → should have.", legacy: B2("You ______ told me about the change. I could have helped.") }),
  d.mcq({ b: "past-modals", t: "didnt-need-vs-neednt-have", L: "B2", diff: 3, focus: "didn't need to (not done) vs needn't have (done, unnecessary)", pre: ["need-modal", "modal-perfect"],
    prompt: "Which sentence means the speaker did NOT go to the office?", options: ["I didn't need to go to the office, so I stayed at home.", "I needn't have gone to the office.", "I should have gone to the office.", "I must have gone to the office."], key: 0, why: "didn't need to → action not performed." }),
  d.mcq({ b: "past-modals", t: "could-have", L: "B2", diff: 2, focus: "could have + pp for an unrealised past possibility", pre: ["modal-perfect", "ability-modals"],
    prompt: "We ______ the early train, but we decided to have breakfast first.", options: ["could have caught", "could catch", "must have caught", "can have caught"], key: 0, why: "Possible but not done → could have + pp." }),
  d.gap({ b: "semi-modals", t: "ought-to", L: "B2", diff: 2, focus: "ought to + have + pp for past advice", pre: ["semi-modals", "modal-perfect"],
    instr: "Complete the gap using 'ought to' and the verb in brackets.", source: "You ______ (check) the timetable before you left.", key: "ought to have checked", why: "Past advice → ought to have + pp." }),
  d.rewrite({ b: "past-modals", t: "neednt-have", L: "B2", diff: 2, focus: "Transforming 'it wasn't necessary but you did it' into needn't have", pre: ["need-modal", "modal-perfect"],
    source: "You paid for the tickets, but it wasn't necessary — they were free.", hint: "You ______ for the tickets — they were free.", key: "needn't have paid", why: "Done + unnecessary → needn't have + pp." }),
  d.mcq({ b: "obligation", t: "be-to-instruction", L: "B2", diff: 3, focus: "be to + infinitive for formal instructions", pre: ["be-to", "obligation-modals"],
    prompt: "Passengers ______ remain seated until the aircraft has stopped.", options: ["are to", "have been to", "are going", "must to"], key: 0, why: "Formal instruction → are to + infinitive.", overlaps: ["tenses"] }),
  d.guided({ b: "past-modals", t: "neednt-have", L: "B2", diff: 2, focus: "Productive needn't have + pp", pre: ["need-modal", "modal-perfect"],
    prompt: "Write a sentence explaining that someone did something unnecessary in the past. Use needn't have.", required: "needn't have + past participle for an unnecessary past action that was still done",
    legacy: B2O("Write a sentence explaining that someone did something unnecessary in the past. Use needn't have.") }),
  d.guided({ b: "deduction", t: "cant-present", L: "B2", diff: 2, focus: "Productive can't be for negative deduction", pre: ["deduction-modals"],
    prompt: "Write a sentence making a strong negative deduction about a present situation. Use can't be.", required: "can't be + adjective/-ing for a strong present negative deduction",
    legacy: B2O("Write a sentence making a strong negative deduction about a present situation. Use can't be.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "hedging", t: "might-academic", L: "C1", diff: 2, focus: "might as an epistemic hedge in academic prose", pre: ["hedging-modals"],
    prompt: "The findings ______ indicate that the original assumption was overly simplistic.", options: ["must", "might", "have to", "ought"], key: 1, why: "Tentative claim → might.", legacy: C1("The findings ______ indicate that the original assumption was overly simplistic.") }),
  d.mcq({ b: "past-modals", t: "must-have", L: "C1", diff: 2, focus: "must have + pp for past deduction in formal register", pre: ["modal-perfect", "deduction-modals"],
    prompt: "Given the available evidence, the discrepancy ______ from a measurement error.", options: ["must have resulted", "must result", "should result", "would resulted"], key: 0, why: "Confident past deduction → must have + pp.",
    legacy: C1("Given the available evidence, the discrepancy ______ have resulted from a measurement error.", "Duplicated 'have' removed from the stem; key expanded to the full perfect modal phrase.") }),
  d.mcq({ b: "hedging", t: "might-have-tentative", L: "C1", diff: 2, focus: "might have + pp as a tentative claim about a past event", pre: ["modal-perfect", "hedging-modals"],
    prompt: "The participants ______ have completed the questionnaire, but the database has not yet been updated.", options: ["needn't", "might", "ought", "mustn't"], key: 1, why: "Tentative past possibility → might have.", legacy: C1("The participants ______ have completed the questionnaire, but the database has not yet been updated.") }),
  d.mcq({ b: "hedging", t: "would-tentative", L: "C1", diff: 3, focus: "'would' softening an assertion (tentative would)", pre: ["hedging-modals"],
    prompt: "This ______ appear to be the first recorded case of its kind.", options: ["would", "will", "must", "shall"], key: 0, why: "Tentative 'would appear' hedges the claim." }),
  d.mcq({ b: "semi-modals", t: "dare-need-bare", L: "C1", diff: 3, focus: "'dare' as a modal takes bare infinitive in negatives/questions", pre: ["semi-modals", "modal-base-form"],
    prompt: "Nobody ______ question the director's decision.", options: ["dared", "dare", "dares to", "dare to"], key: 1, why: "Modal 'dare' → bare infinitive, no -s in negative context.", flags: ["'dared' (as a lexical verb with bare infinitive) is also attested; the modal form is the target. Review."] }),
  d.guided({ b: "hedging", t: "might-academic", L: "C1", diff: 2, focus: "Productive academic hedging with a modal", pre: ["hedging-modals"],
    prompt: "Write an academic-style sentence using a modal verb to hedge a claim rather than state it as certain.", required: "a hedging modal (e.g. may/might/could/would seem to) softening an academic claim rather than stating it as fact",
    constraints: ["exactly one sentence", "the modal must express tentativeness, not ability or obligation"],
    legacy: C1O("Write an academic-style sentence using a modal verb to hedge a claim rather than state it as certain.") }),

  // ---------------- C2 ----------------
  d.mcq({ b: "hedging", t: "shall-formal", L: "C2", diff: 3, focus: "'shall' as a deontic marker in legal/regulatory text (obligation, not future)", pre: ["obligation-modals"],
    prompt: "In 'The tenant shall keep the premises in good repair', 'shall' expresses:", options: ["a binding obligation", "a prediction about the future", "a polite offer", "a possibility"], key: 0, why: "Regulatory 'shall' = must.",
    flags: ["c2-check: register-bound modal meaning; the grammatical form is shared with future 'shall', so the distinction is functional rather than formal. C2 provisional — could be argued C1."] }),
  d.rewrite({ b: "past-modals", t: "modal-perfect-progressive", L: "C2", diff: 3, focus: "Modal + perfect progressive (must have been + -ing)", pre: ["modal-perfect", "past-perfect-continuous"],
    instr: "Rewrite as one sentence with a modal, starting with the words given.", source: "I am sure they were waiting for hours — look how cold they are.", hint: "They ______ for hours — look how cold they are.", key: "must have been waiting", why: "Deduction about a past activity in progress → must have been + -ing.",
    flags: ["c2-check: stacks three auxiliaries (modal + perfect + progressive); genuinely late-acquired form. C2 provisional."] }),
];