import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("modals");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), C1 = leg("C1_MCQ");
const B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR"), C1O = leg("C1_OPEN_GRAMMAR");

export default [
  // ---------------- A1 ----------------
  d.mcq({ b: "ability-permission", t: "can-ability", L: "A1", diff: 1, focus: "can for present ability", pre: ["ability-modals", "modal-base-form"],
    prompt: "I ______ swim.", options: ["can", "am", "do", "have"], key: 0, why: "Ability → can + base verb.", legacy: A1("I ______ swim.") }),
  d.mcq({ b: "ability-permission", t: "can-invariable", L: "A1", diff: 2, focus: "Modals take no -s and no 'to'", pre: ["modal-base-form"],
    prompt: "She ______ speak French.", options: ["can to", "cans", "can", "is can"], key: 2, why: "Modals are invariable.", legacy: A1("She ______ speak French.") }),
  d.mcq({ b: "ability-permission", t: "can-request", L: "A1", diff: 1, focus: "Can you ...? for a request", pre: ["permission-modals", "subject-auxiliary-inversion"],
    prompt: "______ you help me?", options: ["Do", "Can", "Are", "Have"], key: 1, why: "Request → Can you.", legacy: A1("______ you help me?") }),
  d.mcq({ b: "ability-permission", t: "cant-negative", L: "A1", diff: 2, focus: "can't for inability", pre: ["ability-modals"],
    prompt: "He ______ drive. He is only 12.", options: ["can", "can't", "doesn't can", "isn't"], key: 1, why: "Inability → can't.", legacy: A1("He ______ drive. He is only 12.") }),
  d.gap({ b: "ability-permission", t: "can-ability", L: "A1", diff: 2, focus: "Producing can't + base verb", pre: ["ability-modals", "modal-base-form"],
    instr: "Complete the gap with two words: the negative of 'can' plus the verb in brackets.", source: "My little sister ______ (ride) a bicycle yet.", key: "can't ride", alt: ["cannot ride"], why: "can't + base form." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "obligation", t: "must-rule", L: "A2", diff: 1, focus: "must for a rule/strong obligation", pre: ["obligation-modals"],
    prompt: "You ______ wear a seatbelt in a car.", options: ["must", "might", "could", "would"], key: 0, why: "Legal rule → must.", legacy: A2("You ______ wear a seatbelt in a car.") }),
  d.mcq({ b: "advice", t: "should-advice", L: "A2", diff: 1, focus: "should for advice", pre: ["advice-modals"],
    prompt: "You ______ see a doctor if you feel worse.", options: ["should", "can't", "mustn't", "would"], key: 0, why: "Advice → should.", legacy: A2("You ______ see a doctor if you feel worse.") }),
  d.mcq({ b: "ability-permission", t: "could-past-ability", L: "A2", diff: 2, focus: "could for past ability", pre: ["ability-modals"],
    prompt: "When I was five, I ______ swim.", options: ["can", "could", "must", "should"], key: 1, why: "Past ability → could.", legacy: A2("When I was five, I ______ swim.") }),
  d.mcq({ b: "deduction", t: "might-possibility", L: "A2", diff: 2, focus: "might for present possibility", pre: ["deduction-modals"],
    prompt: "It is possible that Anna ______ come later.", options: ["must", "should", "might", "has to"], key: 2, why: "Possibility → might.", legacy: A2("It is possible that Anna ______ come later.") }),
  d.mcq({ b: "obligation", t: "mustnt-prohibition", L: "A2", diff: 2, focus: "mustn't = prohibition (not absence of obligation)", pre: ["obligation-modals"],
    prompt: "You ______ park here. It is not allowed.", options: ["don't have to", "mustn't", "might not", "shouldn't to"], key: 1, why: "Prohibition → mustn't.", legacy: A2("You ______ park here. It is not allowed.") }),
  d.mcq({ b: "semi-modals", t: "have-to-necessity", L: "A2", diff: 2, focus: "have to for external necessity", pre: ["semi-modals", "obligation-modals"],
    prompt: "You ______ bring your passport. It is necessary for the trip.", options: ["have to", "might", "could", "don't have"], key: 0, why: "External necessity → have to.", legacy: A2("You ______ bring your passport. It is necessary for the trip.") }),
  d.gap({ b: "obligation", t: "dont-have-to", L: "A2", diff: 3, focus: "don't have to (no obligation) vs mustn't (prohibition)", pre: ["obligation-modals", "semi-modals"],
    instr: "Complete each gap with mustn't or don't have to.", source: "You ______ come tomorrow if you're busy — it's optional. But you ______ tell anyone about the surprise.",
    key: ["don't have to", "mustn't"], why: "Optional → don't have to; forbidden → mustn't." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "deduction", t: "must-deduction", L: "B1", diff: 2, focus: "must for a confident present deduction", pre: ["deduction-modals"],
    prompt: "The lights are on and his car is outside. He ______ be at home.", options: ["must", "might", "can't", "should"], key: 0, why: "Strong evidence → must be.", legacy: B1("The lights are on and his car is outside. He ______ be at home.") }),
  d.mcq({ b: "deduction", t: "cant-deduction", L: "B1", diff: 2, focus: "can't for a confident negative deduction", pre: ["deduction-modals"],
    prompt: "That ______ be John. John is in Canada this week.", options: ["must", "should", "can't", "might"], key: 2, why: "Impossible → can't be.", legacy: B1("That ______ be John. John is in Canada this week.") }),
  d.mcq({ b: "deduction", t: "might-uncertainty", L: "B1", diff: 1, focus: "might for an uncertain explanation", pre: ["deduction-modals"],
    prompt: "She isn't answering. She ______ be busy.", options: ["mustn't", "might", "has to", "should have"], key: 1, why: "Uncertain → might be.", legacy: B1("She isn't answering. She ______ be busy.") }),
  d.mcq({ b: "past-modals", t: "must-have", L: "B1", diff: 2, focus: "must have + past participle for a past deduction", pre: ["modal-perfect", "deduction-modals"],
    prompt: "The ground is wet. It ______ during the night.", options: ["must rain", "must have rained", "must raining", "must had rained"], key: 1, why: "Past deduction → must have + pp.",
    legacy: B1("The ground is wet. It ______ have rained during the night.", "The legacy stem already contained 'have', so the keyed option produced 'must have have rained'. The stem now ends after 'It ______' and the options carry the full verb phrase.") }),
  d.mcq({ b: "past-modals", t: "might-have", L: "B1", diff: 2, focus: "might have + past participle for an uncertain past event", pre: ["modal-perfect"],
    prompt: "He isn't here. He ______ the bus.", options: ["might miss", "might have missed", "might had missed", "might missing"], key: 1, why: "Uncertain past → might have + pp.",
    legacy: B1("He isn't here. He ______ have missed the bus.", "Legacy stem already contained 'have', duplicating it with the key. Stem shortened and options rebuilt as full verb phrases.") }),
  d.mcq({ b: "past-modals", t: "should-have", L: "B1", diff: 2, focus: "should have + past participle for criticism/regret", pre: ["modal-perfect", "advice-modals"],
    prompt: "You ______ told me about the problem earlier.", options: ["should", "should have", "must have", "could"], key: 1, why: "Regret about the past → should have.", legacy: B1("You ______ told me about the problem earlier.") }),
  d.gap({ b: "past-modals", t: "cant-have", L: "B1", diff: 3, focus: "can't have + past participle for a negative past deduction", pre: ["modal-perfect", "deduction-modals"],
    instr: "Complete the gap with three words, using can't and the verb in brackets.", source: "She ______ (see) us — she was facing the other way.", key: "can't have seen", alt: ["cannot have seen"], why: "Negative past deduction → can't have + pp." }),
  d.guided({ b: "deduction", t: "must-deduction", L: "B1", diff: 1, focus: "Productive must for a present deduction", pre: ["deduction-modals"],
    prompt: "Write one sentence making a strong deduction about a present situation. Use must.", required: "must + base verb for a strong present deduction",
    legacy: B1O("Write one sentence making a strong deduction about a present situation. Use must.") }),
  d.guided({ b: "past-modals", t: "should-have", L: "B1", diff: 2, focus: "Productive should have for regret", pre: ["modal-perfect"],
    prompt: "Write one sentence criticizing or expressing regret about a past action. Use should have.", required: "should have + past participle expressing regret or criticism about the past",
    legacy: B1O("Write one sentence criticizing or expressing regret about a past action. Use should have.") }),

  // ---------------- B2 ----------------
  d.mcq({ b: "deduction", t: "cant-deduction", L: "B2", diff: 1, focus: "can't be for a negative deduction from combined evidence", pre: ["deduction-modals"],
    prompt: "The lights are off and nobody is answering. They ______ be at home.", options: ["must", "can't", "should", "need"], key: 1, why: "Evidence rules it out → can't.", legacy: B2("The lights are off and nobody is answering. They ______ be at home.") }),
  d.mcq({ b: "past-modals", t: "must-have", L: "B2", diff: 2, focus: "must have + pp inferring a past action from present knowledge", pre: ["modal-perfect"],
    prompt: "She knew all the details. She ______ to him earlier.", options: ["must speak", "must have spoken", "must had spoken", "must speaking"], key: 1, why: "Past inference → must have spoken.",
    legacy: B2("She knew all the details. She ______ have spoken to him earlier.", "Legacy stem contained 'have' before the gap, so the key produced 'must have have spoken'. Stem and options rebuilt.") }),
  d.mcq({ b: "past-modals", t: "might-have", L: "B2", diff: 2, focus: "might have + pp for an uncertain past explanation", pre: ["modal-perfect"],
    prompt: "He isn't here yet. He ______ the train.", options: ["might miss", "might have missed", "must miss", "should missing"], key: 1, why: "Uncertain past → might have missed.",
    legacy: B2("He isn't here yet. He ______ have missed the train.", "Legacy stem already contained 'have', duplicating it with the key. Stem shortened, options rebuilt.") }),
  d.mcq({ b: "past-modals", t: "neednt-have", L: "B2", diff: 3, focus: "needn't have + pp = did it but it was unnecessary", pre: ["modal-perfect", "need-modal"],
    prompt: "You ______ bought any food. We already had plenty.", options: ["didn't need", "needn't have", "shouldn't", "don't need"], key: 1, why: "Unnecessary action that happened → needn't have.", legacy: B2("You ______ bought any food. We already had plenty.") }),
  d.mcq({ b: "hedging", t: "would-hedge", L: "B2", diff: 2, focus: "would + seem/appear to soften a claim", pre: ["hedging-modals"],
    prompt: "The results ______ to suggest that the treatment is effective, although more data is needed.", options: ["would seem", "will seem", "must seem", "should seem"], key: 0, why: "Tentative claim → would seem to." }),
  d.gap({ b: "past-modals", t: "didnt-need-vs-neednt-have", L: "B2", diff: 3, focus: "didn't need to (not done) vs needn't have (done unnecessarily)", pre: ["modal-perfect", "need-modal"],
    instr: "Complete each gap with didn't need to or needn't have.", source: "I ______ pay for the ticket — entry was free, so I saved my money. But I ______ arrived so early; the doors opened an hour late.",
    key: ["didn't need to", "needn't have"], why: "First: obligation absent and action not done. Second: action done but unnecessary." }),
  d.guided({ b: "past-modals", t: "neednt-have", L: "B2", diff: 3, focus: "Productive needn't have for an unnecessary completed action", pre: ["modal-perfect", "need-modal"],
    prompt: "Write a sentence explaining that someone did something unnecessary in the past. Use needn't have.", required: "needn't have + past participle for an unnecessary past action that was still done",
    legacy: B2O("Write a sentence explaining that someone did something unnecessary in the past. Use needn't have.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "hedging", t: "modal-hedge-academic", L: "C1", diff: 2, focus: "Hedging modal (might) rather than a certainty modal in academic claims", pre: ["hedging-modals", "deduction-modals"],
    prompt: "The findings ______ indicate that the original assumption was overly simplistic.", options: ["must", "might", "have to", "ought"], key: 1, why: "Cautious academic claim → might.", legacy: C1("The findings ______ indicate that the original assumption was overly simplistic.") }),
  d.mcq({ b: "past-modals", t: "must-have", L: "C1", diff: 2, focus: "must have + pp in a formal evidential context", pre: ["modal-perfect"],
    prompt: "Given the available evidence, the discrepancy ______ from a measurement error.", options: ["must result", "must have resulted", "should result", "would result"], key: 1, why: "Past cause inferred from evidence → must have resulted.",
    legacy: C1("Given the available evidence, the discrepancy ______ have resulted from a measurement error.", "Legacy stem contained 'have' before the gap; stem shortened and options rebuilt as full verb phrases.") }),
  d.mcq({ b: "hedging", t: "may-concessive", L: "C1", diff: 3, focus: "Concessive 'may' ('X may be true, but...') rather than possibility", pre: ["hedging-modals"],
    prompt: "The method ______ be time-consuming, but it produces far more reliable results.", options: ["may", "must", "can't", "should"], key: 0, why: "Concessive admission before 'but' → may." }),
  d.mcq({ b: "semi-modals", t: "be-supposed-to", L: "C1", diff: 2, focus: "be supposed to for an expectation not met", pre: ["semi-modals"],
    prompt: "The report ______ submitted last Friday, but nobody had finished their section.", options: ["was supposed to be", "must be", "should be", "is supposed to be"], key: 0, why: "Past unmet expectation → was supposed to be + pp.", overlaps: ["passive-causative"] }),
  d.gap({ b: "hedging", t: "modal-hedge-academic", L: "C1", diff: 2, focus: "Producing a hedged modal claim in place of a categorical one", pre: ["hedging-modals"],
    instr: "Rewrite the gap with TWO words so the claim is hedged rather than certain.", source: "This pattern ______ (certainly shows) suggest a seasonal effect, though the sample is small.",
    key: "would seem to", alt: ["may well", "might possibly"], why: "Hedging replaces categorical assertion.",
    flags: ["Multiple acceptable hedges; grading depends on 'acceptable' list breadth. Consider converting to guided production if grading proves brittle."] }),
  d.guided({ b: "hedging", t: "modal-hedge-academic", L: "C1", diff: 2, focus: "Productive hedging modal in academic register", pre: ["hedging-modals"],
    prompt: "Write an academic-style sentence using a modal verb to hedge a claim rather than state it as certain.", required: "a hedging modal (e.g. may/might/could/would seem to) softening an academic claim rather than stating it as fact",
    legacy: C1O("Write an academic-style sentence using a modal verb to hedge a claim rather than state it as certain.") }),

  // ---------------- C2 ----------------
  d.mcq({ b: "past-modals", t: "would-have-unfulfilled", L: "C2", diff: 3, focus: "'might have + pp' as unrealised past potential rather than uncertain past fact", pre: ["modal-perfect", "third-conditional"],
    prompt: "If the pilot hadn't reacted so quickly, dozens of passengers ______ their lives.", options: ["might have lost", "might lose", "must have lost", "could lose"], key: 0, why: "Counterfactual unrealised outcome → might have + pp (the event did NOT happen).", overlaps: ["conditionals-wishes"],
    flags: ["c2-check: separates the counterfactual reading of 'might have' from the epistemic reading tested at B1/B2 — a genuine grammatical (modal-scope) distinction. C2 provisional."] }),
  d.mcq({ b: "semi-modals", t: "may-well-have", L: "C2", diff: 3, focus: "Stacked modal hedging: may well have + pp", pre: ["modal-perfect", "hedging-modals"],
    prompt: "The delay ______ contributed to the failure, though we cannot prove it.", options: ["may well have", "may well", "will well have", "might be"], key: 0, why: "Hedged past probability → may well have + past participle.",
    flags: ["c2-check: 'may well have' combines a hedging modal with a perfect infinitive and an intensifying adverb inside the verb phrase — structural. C2 provisional."] }),
];