import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("nouns-articles");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), C1 = leg("C1_MCQ"), B1O = leg("B1_OPEN_GRAMMAR");

export default [
  // ---------------- A1 ----------------
  d.mcq({ b: "articles", t: "a-an", L: "A1", diff: 1, focus: "a before a consonant sound", pre: [],
    prompt: "I have ______ cat.", options: ["a", "an", "the", "no article"], key: 0, why: "Consonant sound → a.", legacy: A1("I have ______ cat.") }),
  d.mcq({ b: "articles", t: "a-an", L: "A1", diff: 1, focus: "an before a vowel sound", pre: [],
    prompt: "She is ______ English teacher.", options: ["a", "an", "the", "no article"], key: 1, why: "Vowel sound → an.", legacy: A1("She is ______ English teacher.") }),
  d.mcq({ b: "articles", t: "a-an", L: "A1", diff: 1, focus: "an before a vowel sound (umbrella)", pre: [],
    prompt: "He has ______ umbrella.", options: ["a", "an", "the", "no article"], key: 1, why: "Vowel sound → an.", legacy: A1("He has ______ umbrella.") }),
  d.mcq({ b: "articles", t: "the-unique", L: "A1", diff: 2, focus: "the for a unique referent", pre: ["definite-article"],
    prompt: "______ sun is very bright today.", options: ["A", "An", "The", "No article"], key: 2, why: "Only one sun → the.", legacy: A1("______ sun is very bright today.") }),
  d.mcq({ b: "articles", t: "the-shared-context", L: "A1", diff: 2, focus: "the for something both speakers can identify", pre: ["definite-article"],
    prompt: "Please close ______ door.", options: ["a", "an", "the", "no article"], key: 2, why: "Specific door known to both → the.", legacy: A1("Please close ______ door.") }),
  d.mcq({ b: "plurals-agreement", t: "irregular-plural", L: "A1", diff: 1, focus: "Irregular plural (children)", pre: ["plural-formation"],
    prompt: "I have two ______.", options: ["child", "childs", "children", "childrens"], key: 2, why: "child → children.", legacy: A1("I have two ______.") }),
  d.mcq({ b: "plurals-agreement", t: "es-plural", L: "A1", diff: 1, focus: "-es plural after -x", pre: ["plural-formation"],
    prompt: "There are three ______ on the table.", options: ["box", "boxs", "boxes", "boxies"], key: 2, why: "box → boxes.", legacy: A1("There are three ______ on the table.") }),
  d.mcq({ b: "plurals-agreement", t: "y-ies-plural", L: "A1", diff: 1, focus: "consonant + y → -ies", pre: ["plural-formation"],
    prompt: "She has two ______.", options: ["baby", "babys", "babies", "babyes"], key: 2, why: "baby → babies.", legacy: A1("She has two ______.") }),
  d.mcq({ b: "countability", t: "uncountable-no-plural", L: "A1", diff: 1, focus: "Uncountable noun takes no plural or 'a'", pre: ["countable-uncountable"],
    prompt: "I need some ______.", options: ["water", "waters", "wateres", "a water"], key: 0, why: "'water' is uncountable.", legacy: A1("I need some ______.") }),
  d.mcq({ b: "countability", t: "partitive", L: "A1", diff: 2, focus: "Counting an uncountable noun with a partitive (loaves of)", pre: ["countable-uncountable"],
    prompt: "She bought two ______.", options: ["bread", "breads", "loaves of bread", "breades"], key: 2, why: "'bread' is counted via 'loaf'.", legacy: A1("She bought two ______.") }),
  d.mcq({ b: "quantifiers", t: "some-any", L: "A1", diff: 1, focus: "any in a question", pre: ["some-any"],
    prompt: "Do you have ______ brothers?", options: ["some", "a", "any", "an"], key: 2, why: "Question → any.", legacy: A1("Do you have ______ brothers?") }),
  d.mcq({ b: "quantifiers", t: "some-any", L: "A1", diff: 1, focus: "any in a negative", pre: ["some-any"],
    prompt: "There isn't ______ milk.", options: ["some", "any", "a", "many"], key: 1, why: "Negative → any.", legacy: A1("There isn't ______ milk.") }),
  d.mcq({ b: "quantifiers", t: "some-offer", L: "A1", diff: 2, focus: "some in an offer/request question", pre: ["some-any"],
    prompt: "Would you like ______ tea?", options: ["any", "some", "a", "an"], key: 1, why: "Offers use some.", legacy: A1("Would you like ______ tea?") }),
  d.gap({ b: "plurals-agreement", t: "irregular-plural", L: "A1", diff: 2, focus: "Producing an irregular plural", pre: ["plural-formation"],
    source: "There are a lot of ______ (person) in the square.", key: "people", why: "person → people." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "quantifiers", t: "much-many", L: "A2", diff: 1, focus: "many with plural countable nouns", pre: ["much-many", "countable-uncountable"],
    prompt: "There aren't ______ eggs in the fridge.", options: ["much", "many", "a little", "any of"], key: 1, why: "eggs = countable plural → many.", legacy: A2("There aren't ______ eggs in the fridge.") }),
  d.mcq({ b: "quantifiers", t: "much-many", L: "A2", diff: 1, focus: "much with uncountable nouns", pre: ["much-many", "countable-uncountable"],
    prompt: "I don't have ______ money with me.", options: ["many", "much", "a few", "several"], key: 1, why: "money = uncountable → much.", legacy: A2("I don't have ______ money with me.") }),
  d.mcq({ b: "quantifiers", t: "few-little", L: "A2", diff: 2, focus: "a few with countable plural", pre: ["few-little", "countable-uncountable"],
    prompt: "We have ______ apples, so we can make a pie.", options: ["a few", "a little", "much", "any"], key: 0, why: "apples countable → a few.", legacy: A2("We have ______ apples, so we can make a pie.") }),
  d.mcq({ b: "quantifiers", t: "few-little", L: "A2", diff: 2, focus: "a little with uncountable", pre: ["few-little", "countable-uncountable"],
    prompt: "There is ______ milk left. We need to buy more.", options: ["a few", "many", "a little", "several"], key: 2, why: "milk uncountable → a little.", legacy: A2("There is ______ milk left. We need to buy more.") }),
  d.mcq({ b: "quantifiers", t: "no-vs-any", L: "A2", diff: 2, focus: "no with an affirmative verb vs any with a negative", pre: ["no-not-none", "some-any"],
    prompt: "There is ______ sugar in my coffee. I don't want any.", options: ["some", "any", "no", "many"], key: 2, why: "Affirmative 'is' + negative meaning → no.", legacy: A2("There is ______ sugar in my coffee. I don't want any.") }),
  d.mcq({ b: "countability", t: "uncountable-abstract", L: "A2", diff: 2, focus: "'information' is uncountable — takes some, not an/many", pre: ["countable-uncountable", "some-any"],
    prompt: "I need ______ information about the course.", options: ["some", "an", "many", "a few"], key: 0, why: "information is uncountable.", legacy: A2("I need ______ information about the course.") }),
  d.mcq({ b: "articles", t: "a-jobs", L: "A2", diff: 1, focus: "a/an with jobs", pre: ["indefinite-article"],
    prompt: "She wants to be ______ doctor.", options: ["a", "an", "the", "no article"], key: 0, why: "Jobs take a/an.", legacy: A2("She wants to be ______ doctor.") }),
  d.mcq({ b: "possession", t: "possessive-s", L: "A2", diff: 1, focus: "Possessive 's on a singular name", pre: ["possessive-s"],
    prompt: "This is ______ car.", options: ["James", "James's", "James is", "James' is"], key: 1, why: "Singular owner → James's.", legacy: A2("This is ______ car.") }),
  d.gap({ b: "quantifiers", t: "some-any", L: "A2", diff: 1, focus: "any (negative) then some (affirmative) in one sentence", pre: ["some-any", "countable-uncountable"],
    instr: "Complete both gaps with some or any.", source: "There isn't ______ milk left, but we have ______ eggs.", key: ["any", "some"], why: "Negative → any; affirmative → some." }),
  d.correct({ b: "countability", t: "uncountable-no-plural", L: "A2", diff: 2, focus: "'advice' has no plural form", pre: ["countable-uncountable"],
    source: "My teacher gave me some good advices.", key: "My teacher gave me some good advice.", why: "advice is uncountable." }),
  d.gap({ b: "possession", t: "plural-possessive", L: "A2", diff: 2, focus: "Plural possessive: apostrophe after the -s", pre: ["possessive-s", "plural-formation"],
    instr: "Complete the gap with the correct possessive form of the word in brackets.", source: "The ______ (teachers) room is on the second floor.", key: "teachers'", why: "Regular plural owner → s'." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "quantifiers", t: "both-either-neither", L: "B1", diff: 2, focus: "both (two, positive) vs neither/either/none", pre: ["both-either-neither"],
    prompt: "My mother works from home, and my father does too — ______ of my parents work from home.", options: ["Neither", "Both", "Either", "None"], key: 1, why: "Both facts are confirmed in the setup, so only 'Both' is true; the plural verb 'work' also agrees with it.",
    legacy: B1("______ of my parents work from home.", "original prompt let a student read 'Neither/Either/None ... work' as informally acceptable (colloquial plural agreement with singular quantifiers is common), making more than one option defensible; added a setup clause that fixes the meaning so only Both is true regardless of that register debate") }),
  d.gap({ b: "plurals-agreement", t: "each-every-singular", L: "B1", diff: 2, focus: "each/every + singular noun + singular verb", pre: ["each-every", "subject-verb-agreement"],
    source: "Every student in the class ______ (have) a laptop.", key: "has", why: "every + singular → has." }),
  d.mcq({ b: "articles", t: "zero-article-general", L: "B1", diff: 2, focus: "Zero article with plural nouns used generally", pre: ["zero-article"],
    prompt: "______ cats are more independent than dogs.", options: ["The", "A", "(no article)", "Some of"], key: 2, why: "General statement about a class → no article." }),
  d.mcq({ b: "articles", t: "the-second-mention", L: "B1", diff: 1, focus: "a on first mention, the on second mention", pre: ["indefinite-article", "definite-article"],
    prompt: "I saw a man and a woman at the door. ______ man was carrying a large box.", options: ["A", "The", "(no article)", "One"], key: 1, why: "Second mention → the." }),
  d.correct({ b: "articles", t: "zero-article-general", L: "B1", diff: 2, focus: "Zero article with uncountable abstract nouns used generally", pre: ["zero-article"],
    source: "The money can't buy the happiness.", key: "Money can't buy happiness.", why: "General abstract nouns → no article." }),
  d.mcq({ b: "plurals-agreement", t: "there-agreement", L: "B1", diff: 2, focus: "Agreement with the first noun in a list after 'there'", pre: ["subject-verb-agreement", "there-existential"],
    prompt: "There ______ a table and four chairs in the kitchen.", options: ["is", "are", "be", "have"], key: 0, why: "Agrees with the nearest noun 'a table' → is.", overlaps: ["sentence-structure"] }),
  d.guided({ b: "quantifiers", t: "both-either-neither", L: "B1", diff: 2, focus: "Productive use of both/either/neither/all/none with correct agreement", pre: ["both-either-neither", "subject-verb-agreement"],
    prompt: "Write one sentence using both, either, neither, all, or none.", required: "both/either/neither/all/none used correctly with the right verb agreement",
    legacy: B1O("Write one sentence using both, either, neither, all, or none.") }),
  d.guided({ b: "plurals-agreement", t: "each-every-singular", L: "B1", diff: 1, focus: "Productive each/every with singular agreement", pre: ["each-every", "subject-verb-agreement"],
    prompt: "Write one sentence using each or every correctly.", required: "each or every used correctly (singular verb agreement)",
    legacy: B1O("Write one sentence using each or every correctly.") }),

  // ---------------- B2 ----------------
  d.errorId({ b: "plurals-agreement", t: "collective-nouns", L: "B2", diff: 2, focus: "'police' is plural-only and takes a plural verb", pre: ["subject-verb-agreement", "collective-nouns"],
    options: ["The police", "is investigating", "the case.", "No error"], key: 1, why: "'The police' is always plural → are investigating." }),
  d.mcq({ b: "plurals-agreement", t: "neither-nor-agreement", L: "B2", diff: 3, focus: "neither ... nor: verb agrees with the nearer subject", pre: ["both-either-neither", "subject-verb-agreement"],
    prompt: "Neither the manager nor the employees ______ happy with the decision.", options: ["was", "were", "is", "has been"], key: 1, why: "Nearer subject 'employees' → were." }),
  d.mcq({ b: "countability", t: "uncountable-as-countable", L: "B2", diff: 2, focus: "Uncountable nouns that are countable in a specific sense (a coffee = a cup)", pre: ["countable-uncountable", "indefinite-article"],
    prompt: "Could I have ______, please? Black, no sugar.", options: ["a coffee", "coffee", "some coffees", "the coffee"], key: 0, why: "Ordering a serving → 'a coffee'." }),
  d.mcq({ b: "articles", t: "the-with-superlative-ordinal", L: "B2", diff: 1, focus: "the before superlatives and ordinals", pre: ["definite-article", "superlative-form"],
    prompt: "This is ______ first time I have visited Bukhara.", options: ["a", "the", "(no article)", "an"], key: 1, why: "Ordinal → the.", overlaps: ["comparison"] }),
  d.gap({ b: "quantifiers", t: "amount-agreement", L: "B2", diff: 3, focus: "An amount of money/time as a single unit takes a singular verb", pre: ["subject-verb-agreement"],
    source: "Two hundred dollars ______ (be) too much to pay for a pair of shoes.", key: "is", why: "A sum treated as one amount → singular." }),
  d.correct({ b: "plurals-agreement", t: "singular-plural-form", L: "B2", diff: 2, focus: "'news' is singular despite its -s", pre: ["subject-verb-agreement", "countable-uncountable"],
    source: "The news about the election were surprising.", key: "The news about the election was surprising.", why: "'news' takes a singular verb." }),
  d.rewrite({ b: "countability", t: "partitive", L: "B2", diff: 2, focus: "Counting an uncountable noun with 'piece of'", pre: ["countable-uncountable"],
    instr: "Rewrite the sentence so that it is grammatical, keeping 'two'.", source: "She gave me two very useful advices.", hint: "She gave me two ______.", key: "very useful pieces of advice", alt: ["useful pieces of advice"], why: "advice → pieces of advice." }),

  // ---------------- C1 ----------------
  d.mcq({ b: "articles", t: "abstract-definite", L: "C1", diff: 2, focus: "Abstract noun takes 'the' when post-modified by a defining clause", pre: ["definite-article", "zero-article", "relative-pronouns"],
    prompt: "______ happiness she felt when she saw them again was hard to put into words.", options: ["A", "The", "(no article)", "An"], key: 1, why: "Defining clause makes the abstract noun specific → the.", overlaps: ["sentence-structure"] }),
  d.mcq({ b: "articles", t: "generic-singular", L: "C1", diff: 3, focus: "Generic 'the' + singular noun for a class (inventions, species)", pre: ["definite-article", "zero-article"],
    prompt: "______ smartphone has changed the way people communicate more than any other device.", options: ["A", "The", "(no article)", "Some"], key: 1, why: "The class as a whole → generic 'the'." }),
  d.mcq({ b: "plurals-agreement", t: "collective-nouns", L: "C1", diff: 2, focus: "Collective noun with plural verb when members act individually (British usage)", pre: ["collective-nouns", "subject-verb-agreement"],
    prompt: "The jury ______ still arguing among themselves about the verdict.", options: ["are", "is", "has", "was"], key: 0, why: "'among themselves' → individuals → plural agreement." }),
  d.mcq({ b: "countability", t: "nominalisation", L: "C1", diff: 1, focus: "Choosing the noun form after an adjective in a nominalised phrase", pre: ["countable-uncountable"],
    prompt: "The rapid ______ of the policy created unexpected administrative difficulties.", options: ["implement", "implementation", "implementing", "implemented"], key: 1, why: "Adjective 'rapid' + 'of' requires a noun.", legacy: C1("The rapid ______ of the policy created unexpected administrative difficulties.") }),
  d.gap({ b: "plurals-agreement", t: "a-number-of", L: "C1", diff: 2, focus: "'a number of' + plural verb vs 'the number of' + singular verb", pre: ["subject-verb-agreement"],
    source: "A number of students ______ (have) complained, but the number of complaints ______ (be) still small.", key: ["have", "is"], why: "a number of → plural; the number of → singular." }),

  // ---------------- C2 ----------------
  d.mcq({ b: "articles", t: "article-with-proper-noun", L: "C2", diff: 2, focus: "Indefinite article with a proper noun to mean 'a person like / a work by'", pre: ["indefinite-article", "zero-article"],
    prompt: "He plays with such confidence that critics are already calling him ______ Mozart of the electric guitar.", options: ["a", "the", "(no article)", "one"], key: 1, why: "'the X of Y' = the counterpart of X in domain Y; 'a Mozart' would mean 'someone like Mozart' without 'of'.",
    flags: ["c2-check: article choice with proper nouns is a genuine syntactic-semantic distinction (not lexical). C2 provisional."] }),
  d.gap({ b: "plurals-agreement", t: "notional-agreement", L: "C2", diff: 3, focus: "Notional agreement with 'one of those who' (plural verb inside the relative clause)", pre: ["subject-verb-agreement", "relative-pronouns"],
    source: "She is one of those managers who ______ (believe) that meetings should never last more than twenty minutes.", key: "believe", why: "The relative clause refers to 'managers', so the verb is plural.", overlaps: ["sentence-structure"],
    flags: ["c2-check: distinguishes surface (one → singular) from structural antecedent (managers → plural); grammatical, not lexical."] }),
];