import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("passive-causative");
const A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), C1 = leg("C1_MCQ"), B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR"), C1O = leg("C1_OPEN_GRAMMAR");

export default [
  // ---------------- A2 ---------------- (domain introduced at A2)
  d.mcq({ b: "simple-passive", t: "present-passive", L: "A2", diff: 1, focus: "Present simple passive: is + pp", pre: ["passive-be-participle", "past-participle"],
    prompt: "English ______ in many countries.", options: ["speaks", "is spoken", "spoke", "is speaking"], key: 1, why: "English receives the action → is spoken.", legacy: A2("English ______ in many countries.") }),
  d.mcq({ b: "simple-passive", t: "past-passive", L: "A2", diff: 2, focus: "Past simple passive: was + pp", pre: ["passive-be-participle", "past-simple"],
    prompt: "The house ______ last year.", options: ["built", "was built", "is built", "builds"], key: 1, why: "Past + receives action → was built.", legacy: A2("The house ______ last year.") }),
  d.mcq({ b: "simple-passive", t: "present-passive", L: "A2", diff: 1, focus: "Plural present passive: are + pp", pre: ["passive-be-participle"],
    prompt: "The letters ______ every morning.", options: ["deliver", "are delivered", "delivered", "are delivering"], key: 1, why: "Letters are delivered.", legacy: A2("The letters ______ every morning.") }),
  d.gap({ b: "simple-passive", t: "past-passive", L: "A2", diff: 2, focus: "Producing was/were + pp", pre: ["passive-be-participle", "past-participle"],
    source: "These photos ______ (take) in Khiva last spring.", key: "were taken", why: "Plural past passive." }),
  d.rewrite({ b: "simple-passive", t: "active-to-passive", L: "A2", diff: 2, focus: "Simple active → passive with 'by'", pre: ["passive-be-participle", "agent-by"],
    instr: "Rewrite in the passive, starting with the words given.", source: "Shakespeare wrote Hamlet.", hint: "Hamlet ______.", key: "was written by Shakespeare", why: "Object → subject; was + pp + by agent." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "simple-passive", t: "past-passive", L: "B1", diff: 1, focus: "Past passive in a longer stem", pre: ["passive-be-participle"],
    prompt: "The new hospital ______ last year.", options: ["built", "was built", "has built", "was building"], key: 1, why: "was + pp.", legacy: B1("The new hospital ______ last year.") }),
  d.gap({ b: "perfect-progressive-passive", t: "present-perfect-passive", L: "B1", diff: 2, focus: "Present perfect passive with 'already'", pre: ["perfect-passive", "present-perfect"],
    source: "The documents ______ already ______ (send) to the manager.", key: ["have", "been sent"], why: "have + already + been + pp.",
    legacy: B1("The documents ______ already ______ to the manager.", "Two-gap paired-option MCQ converted to a two-gap fill so the auxiliary and 'been + participle' are produced separately.") }),
  d.rewrite({ b: "perfect-progressive-passive", t: "present-perfect-passive", L: "B1", diff: 2, focus: "Active present perfect → passive, agent omitted", pre: ["perfect-passive", "present-perfect"],
    instr: "Rewrite the sentence in the passive, starting with the words given. Do not mention who did it.", source: "Someone has stolen my bike.", hint: "My bike ______.", key: "has been stolen", why: "has been + pp." }),
  d.mcq({ b: "modal-passive", t: "modal-be-pp", L: "B1", diff: 2, focus: "Modal + be + pp", pre: ["modal-passive", "modal-base-form"],
    prompt: "This form ______ in black ink.", options: ["must complete", "must be completed", "must completed", "must be complete"], key: 1, why: "The form receives the action → must be completed.", overlaps: ["modals"] }),
  d.mcq({ b: "simple-passive", t: "agent-by", L: "B1", diff: 1, focus: "by introduces the agent; with introduces an instrument", pre: ["agent-by"],
    prompt: "The lock was forced ______ a screwdriver by one of the thieves.", options: ["by", "with", "from", "of"], key: 1, why: "The agent slot is already filled by 'by one of the thieves', so the instrument must take 'with'." }),
  d.correct({ b: "simple-passive", t: "no-passive-intransitive", L: "B1", diff: 3, focus: "Intransitive verbs (happen, arrive) have no passive", pre: ["passive-be-participle"],
    source: "The accident was happened at six o'clock.", key: "The accident happened at six o'clock.", why: "'happen' is intransitive." }),
  d.guided({ b: "simple-passive", t: "past-passive", L: "B1", diff: 1, focus: "Productive past passive", pre: ["passive-be-participle"],
    prompt: "Write one sentence about something that was built, made, discovered, or invented. Use the past passive.", required: "past passive (was/were + past participle) for something built/made/discovered/invented",
    legacy: B1O("Write one sentence about something that was built, made, discovered, or invented. Use the past passive.") }),
  d.guided({ b: "modal-passive", t: "modal-be-pp", L: "B1", diff: 2, focus: "Productive modal passive", pre: ["modal-passive"],
    prompt: "Write one sentence explaining something that must or must not be done. Use a modal passive.", required: "modal + be + past participle (modal passive) correctly formed",
    legacy: B1O("Write one sentence explaining something that must or must not be done. Use a modal passive."), overlaps: ["modals"] }),

  // ---------------- B2 ----------------
  d.mcq({ b: "perfect-progressive-passive", t: "past-perfect-passive", L: "B2", diff: 2, focus: "Past perfect passive: had been + pp", pre: ["perfect-passive", "past-perfect"],
    prompt: "The documents ______ before the meeting began.", options: ["had been prepared", "had prepared", "were preparing", "have prepared"], key: 0, why: "Earlier + receives action → had been prepared.", legacy: B2("The documents ______ before the meeting began.") }),
  d.mcq({ b: "perfect-progressive-passive", t: "past-progressive-passive", L: "B2", diff: 2, focus: "Past progressive passive: was being + pp", pre: ["progressive-passive", "past-continuous"],
    prompt: "At the time of the inspection, the building ______.", options: ["was being repaired", "was repaired", "repaired", "has been repairing"], key: 0, why: "In progress + receives action → was being repaired.", legacy: B2("At the time of the inspection, the building ______.") }),
  d.mcq({ b: "causative", t: "have-something-done", L: "B2", diff: 2, focus: "Causative have + object + pp", pre: ["causative-have-get", "past-participle"],
    prompt: "I didn't repair my car myself. I ______ yesterday.", options: ["had it repaired", "had repaired it", "repaired it", "got repairing"], key: 0, why: "Service arranged → had it repaired.", legacy: B2("I didn't repair my car myself. I ______ yesterday.") }),
  d.mcq({ b: "reporting-passive", t: "is-believed-to", L: "B2", diff: 2, focus: "Impersonal passive reporting: is believed to + infinitive", pre: ["passive-reporting", "to-infinitive"],
    prompt: "The company ______ to have lost millions of dollars.", options: ["believes", "is believed", "is believing", "has believed"], key: 1, why: "Reported belief → is believed to.", legacy: B2("The company ______ to have lost millions of dollars."),
    flags: ["cefr-note: recognition of the passive reporting form kept at B2; PRODUCTION of it sits at C1 (see guided item). Consistent with the provisional ruling that productive passive reporting is C1."] }),
  d.rewrite({ b: "causative", t: "have-something-done", L: "B2", diff: 2, focus: "Producing have + object + pp", pre: ["causative-have-get"],
    source: "A mechanic is going to check my brakes tomorrow.", hint: "I'm going to ______ tomorrow.", key: "have my brakes checked", alt: ["get my brakes checked"], why: "have/get + object + pp." }),
  d.mcq({ b: "get-passive", t: "get-passive-informal", L: "B2", diff: 2, focus: "get + pp as an informal passive for events", pre: ["get-passive"],
    prompt: "Be careful with that vase — it ______ last time we moved house.", options: ["got broken", "got break", "was breaking", "broke itself"], key: 0, why: "Informal event passive → got broken." }),
  d.mcq({ b: "simple-passive", t: "two-object-passive", L: "B2", diff: 3, focus: "Passive with the indirect object as subject (I was given ...)", pre: ["two-object-passive"],
    prompt: "Which passive sentence corresponds to 'They offered Maria the job'?", options: ["Maria was offered the job.", "The job was offered Maria.", "Maria was offered to the job.", "The job offered Maria."], key: 0, why: "Indirect object promoted to subject." }),
  d.gap({ b: "modal-passive", t: "modal-perfect-passive", L: "B2", diff: 3, focus: "Modal + have been + pp", pre: ["modal-passive", "modal-perfect", "perfect-passive"],
    source: "The letter ______ (should / send) last week, but nobody posted it.", key: "should have been sent", why: "should + have been + pp.", overlaps: ["modals"] }),
  d.guided({ b: "causative", t: "have-something-done", L: "B2", diff: 2, focus: "Productive causative", pre: ["causative-have-get"],
    prompt: "Write one sentence explaining that you arranged for someone else to repair, clean, cut, or check something for you.", required: "causative structure (have/get + object + past participle) correctly formed",
    legacy: B2O("Write one sentence explaining that you arranged for someone else to repair, clean, cut, or check something for you.") }),
  d.guided({ b: "perfect-progressive-passive", t: "past-progressive-passive", L: "B2", diff: 3, focus: "Productive past progressive passive", pre: ["progressive-passive"],
    prompt: "Write one sentence describing an action that was in progress and being performed on something at a particular past time.", required: "past progressive passive (was/were being + past participle) for an action in progress and done to something",
    legacy: B2O("Write one sentence describing an action that was in progress and being performed on something at a particular past time.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "perfect-progressive-passive", t: "present-perfect-passive", L: "C1", diff: 1, focus: "Present perfect passive for an ongoing process in academic register", pre: ["perfect-passive"],
    prompt: "The study is based on data that ______ continuously since 2018.", options: ["has been collected", "has collected", "was collecting", "had collected"], key: 0, why: "Data receives the action; unfinished → has been collected.", legacy: C1("The study is based on data that ______ continuously since 2018.") }),
  d.rewrite({ b: "reporting-passive", t: "it-is-said-that", L: "C1", diff: 2, focus: "Transforming 'People say that X ...' into both passive reporting forms", pre: ["passive-reporting"],
    instr: "Rewrite the sentence starting with the words given.", source: "People say that the bridge is unsafe.", hint: "The bridge ______.", key: "is said to be unsafe", why: "Subject-raising passive report." }),
  d.rewrite({ b: "reporting-passive", t: "perfect-infinitive-report", L: "C1", diff: 3, focus: "Passive report of an earlier event: is thought to have + pp", pre: ["passive-reporting", "perfect-infinitive"],
    source: "Experts think that the painting was stolen in the 1980s.", hint: "The painting ______ in the 1980s.", key: "is thought to have been stolen", why: "Earlier + passive → to have been + pp." }),
  d.mcq({ b: "causative", t: "get-someone-to", L: "C1", diff: 2, focus: "get + person + to-infinitive vs have + person + bare infinitive", pre: ["causative-get-to", "verb-object-infinitive"],
    prompt: "Which sentence is grammatical?", options: ["I got my brother to help me move.", "I got my brother help me move.", "I had my brother to help me move.", "I made my brother to help me move."], key: 0, why: "get + object + to-infinitive; have/make + bare.", overlaps: ["verb-patterns"] }),
  d.gap({ b: "passive-infinitive", t: "need-doing", L: "C1", diff: 2, focus: "need + -ing / need to be + pp with passive meaning", pre: ["passive-infinitive-gerund", "gerund"],
    source: "These figures need ______ (check) before we publish them.", key: "checking", alt: ["to be checked"], why: "need + -ing = passive meaning.", overlaps: ["verb-patterns"] }),
  d.guided({ b: "reporting-passive", t: "is-believed-to", L: "C1", diff: 1, focus: "Productive passive reporting structure", pre: ["passive-reporting", "to-infinitive"],
    prompt: "Write a sentence reporting a belief about another person or situation. Use a passive reporting structure such as is believed to...", required: "a passive reporting structure (e.g. is believed to / is thought to) used correctly",
    legacy: B2O("Write a sentence reporting a belief about another person or situation. Use a passive reporting structure such as is believed to..."),
    flags: ["cefr-conflict: legacy pool B2; placed at C1 per provisional ruling (productive passive reporting)."], overlaps: ["reported-speech"] }),
  d.guided({ b: "perfect-progressive-passive", t: "present-perfect-passive", L: "C1", diff: 2, focus: "Productive present perfect passive with present relevance", pre: ["perfect-passive"],
    prompt: "Write a sentence using the present perfect passive to describe a process that began in the past and remains relevant now.", required: "present perfect passive (has been + past participle) for a process begun in the past and still relevant",
    legacy: C1O("Write a sentence using the present perfect passive to describe a process that began in the past and remains relevant now.") }),

  // ---------------- C2 ----------------
  d.mcq({ b: "get-passive", t: "have-something-happen-to", L: "C2", diff: 3, focus: "have + object + pp for an experience suffered (not arranged) — the 'victim' causative", pre: ["causative-have-get"],
    prompt: "In 'We had our passports stolen in the station', the speaker:", options: ["suffered the theft; they did not arrange it", "arranged for someone to take the passports", "stole the passports themselves", "asked the police to take the passports"], key: 0, why: "Same form as causative 'have sth done' but experiential meaning.",
    flags: ["c2-check: form–meaning mismatch (identical structure, opposite agency) is a genuine late distinction. C2 provisional."] }),
  d.rewrite({ b: "modal-passive", t: "modal-perfect-progressive-passive", L: "C2", diff: 3, focus: "Modal + perfect + progressive + passive stacking", pre: ["modal-passive", "progressive-passive", "modal-perfect"],
    instr: "Rewrite in the passive, starting with the words given.", source: "They must have been questioning the suspect for hours when the lawyer arrived.", hint: "The suspect ______ for hours when the lawyer arrived.", key: "must have been being questioned", why: "Full auxiliary stack: modal + have been + being + pp.",
    flags: ["c2-check: 'been being' stacking is grammatical but extremely rare and often avoided by native speakers; diagnostic mainly of formal-system control. C2 provisional; may be too marginal for placement — engine should treat as optional probe."] }),
];