import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("prep-phrasal");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ");

export default [
  // ---------------- A1 ----------------
  d.mcq({ b: "place", t: "on-surface", L: "A1", diff: 1, focus: "on for a surface", pre: ["prepositions-place"],
    prompt: "The keys are ______ the table.", options: ["in", "on", "at", "to"], key: 1, why: "Surface → on.", legacy: A1("The keys are ______ the table.") }),
  d.mcq({ b: "place", t: "in-container", L: "A1", diff: 1, focus: "in for a container", pre: ["prepositions-place"],
    prompt: "The cat is ______ the box.", options: ["in", "on", "at", "from"], key: 0, why: "Inside → in.", legacy: A1("The cat is ______ the box.") }),
  d.mcq({ b: "place", t: "between", L: "A1", diff: 2, focus: "between two named places", pre: ["prepositions-place"],
    prompt: "The bank is ______ the supermarket and the café.", options: ["under", "between", "in", "on"], key: 1, why: "Two reference points → between.", legacy: A1("The bank is ______ the supermarket and the café.") }),
  d.mcq({ b: "place", t: "on-surface", L: "A1", diff: 1, focus: "on the wall (vertical surface)", pre: ["prepositions-place"],
    prompt: "The picture is ______ the wall.", options: ["on", "in", "at", "between"], key: 0, why: "Attached to a surface → on.", legacy: A1("The picture is ______ the wall.") }),
  d.mcq({ b: "time", t: "at-clock", L: "A1", diff: 1, focus: "at with clock times", pre: ["prepositions-time"],
    prompt: "I get up ______ 7 o'clock.", options: ["on", "in", "at", "by"], key: 2, why: "Clock time → at.", legacy: A1("I get up ______ 7 o'clock.") }),
  d.mcq({ b: "time", t: "on-days", L: "A1", diff: 1, focus: "on with days", pre: ["prepositions-time"],
    prompt: "We have English ______ Monday.", options: ["at", "on", "in", "from"], key: 1, why: "Day → on.", legacy: A1("We have English ______ Monday.") }),
  d.mcq({ b: "time", t: "in-months", L: "A1", diff: 1, focus: "in with months", pre: ["prepositions-time"],
    prompt: "My birthday is ______ July.", options: ["on", "at", "in", "by"], key: 2, why: "Month → in.", legacy: A1("My birthday is ______ July.") }),
  d.mcq({ b: "time", t: "at-night", L: "A1", diff: 2, focus: "at night (fixed expression vs in the morning)", pre: ["prepositions-time"],
    prompt: "I usually sleep ______ night.", options: ["on", "at", "in", "to"], key: 1, why: "Fixed: at night.", legacy: A1("I usually sleep ______ night.") }),
  d.gap({ b: "time", t: "in-on-at-contrast", L: "A1", diff: 2, focus: "in / on / at contrast across three time expressions", pre: ["prepositions-time"],
    instr: "Complete each gap with in, on or at.", source: "The lesson is ______ Tuesday ______ 10 o'clock ______ the morning.", key: ["on", "at", "in"], why: "Day → on; clock → at; part of day → in." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "place", t: "in-area", L: "A2", diff: 1, focus: "in for an enclosed area (garden)", pre: ["prepositions-place"],
    prompt: "The children are playing ______ the garden.", options: ["at", "on", "in", "to"], key: 2, why: "Enclosed area → in.", legacy: A2("The children are playing ______ the garden.") }),
  d.mcq({ b: "movement", t: "arrive-at-in", L: "A2", diff: 2, focus: "arrive at (a point) — never 'arrive to'", pre: ["prepositions-movement", "dependent-prepositions"],
    prompt: "We arrived ______ the airport at 6 a.m.", options: ["at", "on", "to", "by"], key: 0, why: "arrive at + building/point.", legacy: A2("We arrived ______ the airport at 6 a.m.") }),
  d.mcq({ b: "time", t: "since-for", L: "A2", diff: 1, focus: "since with a start point", pre: ["prepositions-time", "time-adverbials"],
    prompt: "I have lived here ______ 2020.", options: ["for", "since", "during", "from"], key: 1, why: "Start point → since.", legacy: A2("I have lived here ______ 2020."), overlaps: ["tenses"] }),
  d.mcq({ b: "dependent-prepositions", t: "interested-in", L: "A2", diff: 1, focus: "interested in", pre: ["dependent-prepositions"],
    prompt: "She is interested ______ photography.", options: ["on", "at", "in", "for"], key: 2, why: "Fixed: interested in.", legacy: A2("She is interested ______ photography.") }),
  d.gap({ b: "dependent-prepositions", t: "adjective-preposition", L: "A2", diff: 2, focus: "good at / afraid of", pre: ["dependent-prepositions"],
    instr: "Complete each gap with ONE preposition.", source: "My brother is very good ______ maths, but he is afraid ______ exams.", key: ["at", "of"], why: "good at; afraid of." }),
  d.mcq({ b: "movement", t: "to-vs-in", L: "A2", diff: 2, focus: "to for movement towards, in for location", pre: ["prepositions-movement", "prepositions-place"],
    prompt: "Every summer we go ______ the mountains and stay ______ a small hotel.", options: ["to / in", "in / to", "at / to", "to / to"], key: 0, why: "Movement → to; location → in." }),
  d.mcq({ b: "phrasal-verbs", t: "common-phrasal", L: "A2", diff: 2, focus: "Particle choice in a common phrasal verb (get up)", pre: ["phrasal-verb-separability"],
    prompt: "I usually get ______ at seven and have breakfast.", options: ["up", "on", "out", "in"], key: 0, why: "get up = leave bed." }),
  d.correct({ b: "movement", t: "go-home", L: "A2", diff: 2, focus: "No preposition before 'home' after go/come", pre: ["prepositions-movement"],
    source: "After the concert we went to home by taxi.", key: "After the concert we went home by taxi.", why: "go home (no 'to')." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "phrasal-verbs", t: "pronoun-separation", L: "B1", diff: 2, focus: "Object PRONOUN must split a separable phrasal verb", pre: ["phrasal-verb-separability", "object-pronouns"],
    prompt: "The music is too loud. Please ______.", options: ["turn it down", "turn down it", "turn it off down", "turn down"], key: 0, why: "Pronoun goes between verb and particle." }),
  d.order({ b: "phrasal-verbs", t: "pronoun-separation", L: "B1", diff: 2, focus: "Producing the split order with a pronoun object", pre: ["phrasal-verb-separability", "object-pronouns"],
    tokens: ["them", "pick", "I'll", "at six", "up"], key: ["I'll", "pick", "them", "up", "at six"], why: "verb + pronoun + particle." }),
  d.mcq({ b: "phrasal-verbs", t: "inseparable", L: "B1", diff: 2, focus: "Inseparable phrasal verb: object cannot split it (look after)", pre: ["phrasal-verb-separability"],
    prompt: "Who ______ while you were away?", options: ["looked after your cat", "looked your cat after", "looked after it your cat", "your cat looked after"], key: 0, why: "look after is inseparable." }),
  d.mcq({ b: "dependent-prepositions", t: "verb-preposition", L: "B1", diff: 2, focus: "depend on (verb + dependent preposition)", pre: ["dependent-prepositions", "prepositional-verbs"],
    prompt: "Whether we go or not depends ______ the weather.", options: ["of", "on", "from", "at"], key: 1, why: "depend on." }),
  d.gap({ b: "dependent-prepositions", t: "preposition-gerund", L: "B1", diff: 2, focus: "Preposition + -ing after an adjective (worried about doing)", pre: ["dependent-prepositions", "preposition-gerund"],
    source: "I'm worried ______ ______ (fail) the exam.", key: ["about", "failing"], why: "worried about + -ing.", overlaps: ["verb-patterns"] }),
  d.mcq({ b: "time", t: "by-until", L: "B1", diff: 2, focus: "by (deadline) vs until (continuing up to)", pre: ["prepositions-time"],
    prompt: "Please send me the report ______ Friday at the latest.", options: ["until", "by", "till", "since"], key: 1, why: "Deadline → by." }),
  d.mcq({ b: "time", t: "during-while", L: "B1", diff: 2, focus: "during + noun vs while + clause", pre: ["prepositions-time", "subordinating-conjunctions"],
    prompt: "My phone rang twice ______ the meeting.", options: ["during", "while", "for", "along"], key: 0, why: "Followed by a noun → during.", overlaps: ["sentence-structure"] }),
  d.correct({ b: "dependent-prepositions", t: "verb-preposition", L: "B1", diff: 2, focus: "No preposition after 'discuss'", pre: ["prepositional-verbs"],
    source: "We need to discuss about the new timetable.", key: "We need to discuss the new timetable.", why: "discuss takes a direct object." }),
  d.mcq({ b: "movement", t: "across-through-along", L: "B1", diff: 2, focus: "through (enclosed space) vs across (surface) vs along (line)", pre: ["prepositions-movement"],
    prompt: "We walked ______ the forest until we reached the river.", options: ["through", "across", "along", "over"], key: 0, why: "Enclosed 3-D space → through." }),

  // ---------------- B2 ----------------
  d.gap({ b: "dependent-prepositions", t: "accused-of", L: "B2", diff: 2, focus: "accuse (someone) of + -ing", pre: ["dependent-prepositions", "gerund"],
    instr: "Complete the gap with ONE word.", source: "He was accused ______ taking money from the till.", key: "of", why: "accuse of.", overlaps: ["passive-causative"] }),
  d.mcq({ b: "dependent-prepositions", t: "noun-preposition", L: "B2", diff: 2, focus: "Noun + dependent preposition (reason for / solution to)", pre: ["dependent-prepositions"],
    prompt: "There is no simple solution ______ this problem.", options: ["for", "to", "of", "about"], key: 1, why: "solution to." }),
  d.mcq({ b: "phrasal-verbs", t: "three-part-phrasal", L: "B2", diff: 2, focus: "Three-part phrasal verb is inseparable (put up with)", pre: ["three-part-phrasal"],
    prompt: "I don't know how she ______ that noise every day.", options: ["puts up with", "puts with up", "puts it up with", "puts up"], key: 0, why: "Three-part phrasal verbs keep their order." }),
  d.mcq({ b: "stranding", t: "relative-preposition", L: "B2", diff: 2, focus: "Stranded preposition at the end of a relative clause (informal)", pre: ["preposition-stranding", "relative-pronouns"],
    prompt: "This is the colleague ______.", options: ["I told you about", "about I told you", "whom I told you", "I told about you"], key: 0, why: "Relative clause with stranded 'about'.", overlaps: ["sentence-structure"] }),
  d.rewrite({ b: "stranding", t: "fronted-preposition", L: "B2", diff: 3, focus: "Formal fronting: preposition + which/whom", pre: ["preposition-stranding", "relative-pronouns"],
    instr: "Rewrite the relative clause in a more formal style, starting with the words given.", source: "The company I work for is expanding.", hint: "The company ______ is expanding.", key: "for which I work", why: "Fronted preposition + which.", overlaps: ["sentence-structure"] }),
  d.mcq({ b: "phrasal-verbs", t: "phrasal-noun-position", L: "B2", diff: 2, focus: "Long noun object goes after the particle, pronoun before it", pre: ["phrasal-verb-separability"],
    prompt: "Which sentence is NOT correct?", options: ["She gave back the money she owed.", "She gave the money back.", "She gave it back.", "She gave back it."], key: 3, why: "Pronoun cannot follow the particle." }),
  d.gap({ b: "time", t: "in-time-on-time", L: "B2", diff: 2, focus: "on time (punctual) vs in time (before it's too late)", pre: ["prepositions-time"],
    instr: "Complete each gap with in or on.", source: "The train left exactly ______ time, so we arrived ______ time to see the opening.", key: ["on", "in"], why: "on time = punctual; in time = early enough." }),
  d.correct({ b: "dependent-prepositions", t: "verb-preposition", L: "B2", diff: 3, focus: "'consist of' (not 'from')", pre: ["prepositional-verbs"],
    source: "The course consists from three modules and a final exam.", key: "The course consists of three modules and a final exam.", why: "consist of." }),

  // ---------------- C1 ----------------
  d.guided({ b: "phrasal-verbs", t: "three-part-phrasal", L: "C1", diff: 2, focus: "Productive control of a three-part phrasal verb with its object", pre: ["three-part-phrasal"],
    prompt: "Write one natural sentence using a THREE-part phrasal verb (for example: put up with, look forward to, get away with, run out of) with an object.",
    required: "a genuine three-part phrasal verb used inseparably with a following object, e.g. 'I can't put up with the noise'", constraints: ["exactly one sentence", "object must follow the full three-part verb, not split it"] }),
  d.mcq({ b: "dependent-prepositions", t: "preposition-meaning-shift", L: "C1", diff: 3, focus: "Dependent preposition changes meaning (agree with sb / agree to sth / agree on a plan)", pre: ["dependent-prepositions", "prepositional-verbs"],
    prompt: "After hours of negotiation, both sides finally agreed ______ a compromise.", options: ["on", "with", "to", "about"], key: 0, why: "agree on + the thing decided together." }),
  d.mcq({ b: "stranding", t: "relative-preposition", L: "C1", diff: 2, focus: "Formal 'to which' relative after an abstract noun (the extent to which)", pre: ["preposition-stranding", "relative-pronouns"],
    prompt: "The extent to ______ these findings apply to other populations remains uncertain.", options: ["which", "that", "what", "whom"], key: 0, why: "Preposition + which (never 'that').", legacy: leg("C1_MCQ")("The extent to ______ these findings apply to other populations remains uncertain."), overlaps: ["sentence-structure"] }),
  d.rewrite({ b: "phrasal-verbs", t: "phrasal-passive", L: "C1", diff: 3, focus: "Passive of a prepositional/phrasal verb keeps the particle", pre: ["prepositional-passive", "phrasal-verb-separability"],
    instr: "Rewrite in the passive, starting with the words given.", source: "Somebody broke into our office last night.", hint: "Our office ______ last night.", key: "was broken into", why: "The particle stays: was broken into.", overlaps: ["passive-causative"] }),
  d.gap({ b: "dependent-prepositions", t: "noun-preposition", L: "C1", diff: 2, focus: "Academic noun + preposition collocation (insight into / emphasis on)", pre: ["dependent-prepositions"],
    instr: "Complete each gap with ONE preposition.", source: "The study offers fresh insight ______ the causes of the decline, with particular emphasis ______ rural areas.", key: ["into", "on"], why: "insight into; emphasis on." }),

  // ---------------- C2 ----------------
  d.mcq({ b: "stranding", t: "pied-piping-whose", L: "C2", diff: 3, focus: "Fronted preposition with 'whose' phrase (pied-piping of a whole noun phrase)", pre: ["preposition-stranding", "relative-pronouns"],
    prompt: "Which sentence is the correct formal version of 'the author — I reviewed his book'?", options: ["the author whose book I reviewed", "the author, the book of whom I reviewed", "the author whose I reviewed book", "the author of whose book reviewed I"], key: 0, why: "'whose book' moves as a unit; the marked 'of whom' variant is stilted and misplaced here.", overlaps: ["sentence-structure"],
    flags: ["c2-check: possessive-relative pied-piping is structurally complex but the correct answer here is arguably C1. Kept as C2 difficulty-1 candidate only if the engine needs a C2 probe in this domain; otherwise demote to C1 diff 3."] }),
];