import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("pronouns");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ");

export default [
  // ---------------- A1 ----------------
  d.mcq({ b: "personal", t: "subject-pronouns", L: "A1", diff: 1, focus: "Subject pronoun I (not me/my) as sentence subject", pre: ["subject-pronouns"],
    prompt: "______ am from Samarkand.", options: ["Me", "I", "My", "Mine"], key: 1, why: "Subject → I.", legacy: A1("______ am from Samarkand.") }),
  d.mcq({ b: "personal", t: "subject-pronouns", L: "A1", diff: 1, focus: "Subject pronoun he referring back to a named male", pre: ["subject-pronouns"],
    prompt: "Tom is here. ______ is waiting outside.", options: ["Him", "His", "He", "Her"], key: 2, why: "Subject position → He.", legacy: A1("Tom is here. ______ is waiting outside.") }),
  d.mcq({ b: "personal", t: "object-pronouns", L: "A1", diff: 1, focus: "Object pronoun her after a verb", pre: ["subject-pronouns", "object-pronouns"],
    prompt: "Anna is my friend. I see ______ every day.", options: ["she", "her", "hers", "he"], key: 1, why: "Object of 'see' → her.", legacy: A1("Anna is my friend. I see ______ every day.") }),
  d.mcq({ b: "personal", t: "object-pronouns", L: "A1", diff: 1, focus: "Object pronoun me", pre: ["object-pronouns"],
    prompt: "Can you help ______, please?", options: ["I", "me", "my", "mine"], key: 1, why: "Object → me.", legacy: A1("Can you help ______, please?") }),
  d.mcq({ b: "personal", t: "object-pronouns", L: "A1", diff: 2, focus: "Object pronoun us (vs we/our)", pre: ["object-pronouns"],
    prompt: "We like this teacher. She helps ______ a lot.", options: ["we", "our", "us", "ours"], key: 2, why: "Object → us.", legacy: A1("We like this teacher. She helps ______ a lot.") }),
  d.mcq({ b: "possessive", t: "possessive-determiners", L: "A1", diff: 1, focus: "Possessive determiner my before a noun", pre: ["possessive-determiners"],
    prompt: "This is ______ book.", options: ["I", "me", "my", "mine"], key: 2, why: "Before a noun → my.", legacy: A1("This is ______ book.") }),
  d.mcq({ b: "possessive", t: "possessive-determiners", L: "A1", diff: 2, focus: "his (not he/him) before a noun", pre: ["possessive-determiners"],
    prompt: "This is my brother. ______ name is Ali.", options: ["He", "Him", "His", "Her"], key: 2, why: "Determiner before 'name' → His.", legacy: A1("This is my brother. ______ name is Ali.") }),
  d.mcq({ b: "possessive", t: "possessive-pronouns", L: "A1", diff: 2, focus: "Possessive pronoun theirs standing alone", pre: ["possessive-pronouns"],
    prompt: "These bags are ______.", options: ["their", "theirs", "them", "they"], key: 1, why: "No noun follows → theirs.", legacy: A1("These bags are ______.") }),
  d.mcq({ b: "demonstrative", t: "this-these-near", L: "A1", diff: 1, focus: "this for a single near object", pre: ["demonstratives"],
    prompt: "______ is my phone here in my hand.", options: ["Those", "These", "This", "They"], key: 2, why: "Singular + near → This.", legacy: A1("______ is my phone here in my hand.") }),
  d.mcq({ b: "demonstrative", t: "that-those-far", L: "A1", diff: 1, focus: "those for plural far objects", pre: ["demonstratives"],
    prompt: "______ are my shoes over there.", options: ["This", "That", "These", "Those"], key: 3, why: "Plural + far → Those.", legacy: A1("______ are my shoes over there.") }),
  d.mcq({ b: "demonstrative", t: "this-these-near", L: "A1", diff: 2, focus: "these for plural near objects", pre: ["demonstratives"],
    prompt: "______ books here are mine.", options: ["This", "That", "These", "Those"], key: 2, why: "Plural + here → These.", legacy: A1("______ books here are mine.") }),
  d.gap({ b: "personal", t: "object-pronouns", L: "A1", diff: 2, focus: "Producing the object pronoun for a plural referent", pre: ["object-pronouns"],
    instr: "Complete the gap with ONE pronoun.", source: "My grandparents live far away, so I only see ______ in summer.", key: "them", why: "Object referring to grandparents → them." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "possessive", t: "possessive-pronouns", L: "A2", diff: 1, focus: "mine (pronoun) vs my (determiner)", pre: ["possessive-pronouns", "possessive-determiners"],
    prompt: "This phone is ______.", options: ["my", "mine", "me", "I"], key: 1, why: "Stands alone → mine.", legacy: A2("This phone is ______.") }),
  d.mcq({ b: "possessive", t: "possessive-determiners", L: "A2", diff: 1, focus: "their (determiner) vs theirs", pre: ["possessive-determiners"],
    prompt: "That is ______ house. They bought it last year.", options: ["their", "theirs", "them", "they"], key: 0, why: "Before 'house' → their.", legacy: A2("That is ______ house. They bought it last year.") }),
  d.mcq({ b: "substitution", t: "one-ones", L: "A2", diff: 1, focus: "one replacing a singular countable noun", pre: ["one-ones-another"],
    prompt: "Which jacket do you want? The black ______.", options: ["one", "ones", "it", "that"], key: 0, why: "Replaces singular 'jacket' → one.", legacy: A2("Which jacket do you want? The black ______.") }),
  d.mcq({ b: "substitution", t: "one-ones", L: "A2", diff: 1, focus: "ones replacing a plural noun", pre: ["one-ones-another"],
    prompt: "These apples are expensive. The green ______ are cheaper.", options: ["one", "ones", "it", "that"], key: 1, why: "Plural 'apples' → ones.", legacy: A2("These apples are expensive. The green ______ are cheaper.") }),
  d.mcq({ b: "indefinite", t: "someone-anyone", L: "A2", diff: 1, focus: "someone in an affirmative statement", pre: ["indefinite-pronouns", "some-any"],
    prompt: "There is ______ at the door.", options: ["someone", "anyone", "nothing", "everywhere"], key: 0, why: "Affirmative → someone.", legacy: A2("There is ______ at the door.") }),
  d.mcq({ b: "indefinite", t: "someone-anyone", L: "A2", diff: 1, focus: "anyone in a negative statement", pre: ["indefinite-pronouns", "some-any"],
    prompt: "I didn't see ______ in the room.", options: ["someone", "anyone", "something", "everyone"], key: 1, why: "Negative → anyone.", legacy: A2("I didn't see ______ in the room.") }),
  d.mcq({ b: "indefinite", t: "nothing-anything", L: "A2", diff: 2, focus: "nothing with an affirmative verb (no double negative)", pre: ["indefinite-pronouns", "no-not-none"],
    prompt: "There is ______ in my bag. I can't find my keys.", options: ["something", "anything", "nothing", "anyone"], key: 2, why: "Affirmative verb + negative meaning → nothing.", legacy: A2("There is ______ in my bag. I can't find my keys.") }),
  d.mcq({ b: "indefinite", t: "something-offer", L: "A2", diff: 2, focus: "something in an offer question", pre: ["indefinite-pronouns", "some-any"],
    prompt: "Would you like ______ to eat?", options: ["nothing", "anyone", "something", "no one"], key: 2, why: "Offer → something.", legacy: A2("Would you like ______ to eat?") }),
  d.mcq({ b: "demonstrative", t: "that-those-far", L: "A2", diff: 1, focus: "those as a pronoun for plural far items", pre: ["demonstratives"],
    prompt: "I don't like these shoes. I prefer ______ over there.", options: ["this", "that", "those", "one"], key: 2, why: "Plural + over there → those.", legacy: A2("I don't like these shoes. I prefer ______ over there.") }),
  d.correct({ b: "personal", t: "subject-object-contrast", L: "A2", diff: 2, focus: "Object pronoun after a preposition in a coordinated phrase", pre: ["object-pronouns"],
    source: "This present is for my sister and I.", key: "This present is for my sister and me.", why: "Object of 'for' → me." }),
  d.gap({ b: "indefinite", t: "indefinite-agreement", L: "A2", diff: 2, focus: "everyone takes a singular verb", pre: ["indefinite-pronouns", "subject-verb-agreement"],
    source: "Everyone in my family ______ (like) football.", key: "likes", why: "everyone → singular verb." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "substitution", t: "another-other", L: "B1", diff: 1, focus: "another (a different single one) vs other/others", pre: ["one-ones-another"],
    prompt: "I don't like this jacket. Can I try ______?", options: ["another", "other", "others", "the another"], key: 0, why: "A different single item → another." }),
  d.mcq({ b: "substitution", t: "the-other-others", L: "B1", diff: 2, focus: "the other (the remaining one of two) vs another/others", pre: ["one-ones-another"],
    prompt: "I have two brothers. One lives in Tashkent and ______ lives in Bukhara.", options: ["another", "the other", "other", "the others"], key: 1, why: "Second of exactly two → the other." }),
  d.gap({ b: "reflexive", t: "reflexive-object", L: "B1", diff: 2, focus: "Reflexive pronoun when subject and object are the same", pre: ["object-pronouns", "reflexive-pronouns"],
    instr: "Complete the gap with one word.", source: "Be careful with that knife — you might cut ______.", key: "yourself", alt: ["yourselves"], why: "Subject = object → reflexive." }),
  d.mcq({ b: "reflexive", t: "reciprocal", L: "B1", diff: 2, focus: "each other (reciprocal) vs themselves (reflexive)", pre: ["reciprocal-pronouns", "reflexive-pronouns"],
    prompt: "The two sisters often send ______ long messages.", options: ["themselves", "each other", "herself", "them"], key: 1, why: "A sends to B and B to A → each other." }),
  d.mcq({ b: "indefinite", t: "indefinite-agreement", L: "B1", diff: 2, focus: "Singular verb after 'nobody' despite plural meaning", pre: ["indefinite-pronouns", "subject-verb-agreement"],
    prompt: "Nobody ______ what happened to the missing files.", options: ["know", "knows", "are knowing", "have known"], key: 1, why: "nobody → singular." }),
  d.mcq({ b: "personal", t: "dummy-it", L: "B1", diff: 2, focus: "Dummy 'it' as subject for weather/time/distance", pre: ["dummy-it"],
    prompt: "______ is about ten kilometres from here to the airport.", options: ["There", "It", "That", "This"], key: 1, why: "Distance statements use dummy 'it'.", overlaps: ["sentence-structure"] }),
  d.correct({ b: "reflexive", t: "no-reflexive-after-feel", L: "B1", diff: 3, focus: "Some verbs (relax, feel, concentrate) take no reflexive in English", pre: ["reflexive-pronouns"],
    source: "After the exam I sat down and relaxed myself for an hour.", key: "After the exam I sat down and relaxed for an hour.", why: "'relax' is not reflexive in English." }),

  // ---------------- B2 ----------------
  d.mcq({ b: "personal", t: "generic-you-one", L: "B2", diff: 2, focus: "Generic 'one' as a formal impersonal pronoun", pre: ["generic-pronouns"],
    prompt: "In such situations, ______ should always remain calm and ask for clarification.", options: ["one", "he", "they", "somebody"], key: 0, why: "Formal generic reference → one." }),
  d.mcq({ b: "indefinite", t: "singular-they", L: "B2", diff: 2, focus: "'they/their' referring back to an unspecified singular person", pre: ["indefinite-pronouns", "possessive-determiners"],
    prompt: "If anyone calls while I'm out, please take ______ number.", options: ["their", "his", "its", "your"], key: 0, why: "Unspecified singular referent → their." }),
  d.mcq({ b: "substitution", t: "so-not-substitution", L: "B2", diff: 2, focus: "'so' substituting for a whole clause after think/hope/suppose", pre: ["ellipsis-substitution"],
    prompt: "'Will the shops still be open?'  'I think ______.'", options: ["so", "it", "that", "yes it"], key: 0, why: "'so' replaces 'that they will be open'.", overlaps: ["sentence-structure"] }),
  d.gap({ b: "reflexive", t: "emphatic-reflexive", L: "B2", diff: 2, focus: "Emphatic reflexive meaning 'personally / without help'", pre: ["reflexive-pronouns"],
    instr: "Complete the gap with one word.", source: "Nobody helped her — she painted the whole flat ______.", key: "herself", why: "Emphasis on doing it personally → herself." }),
  d.mcq({ b: "possessive", t: "possessive-before-gerund", L: "B2", diff: 3, focus: "Possessive determiner before a gerund (formal)", pre: ["possessive-determiners", "gerund"],
    prompt: "I hope you don't mind ______ asking, but how old are you?", options: ["my", "me", "I", "mine"], key: 0, why: "Formal gerund subject → possessive 'my' (object 'me' is informal but the question targets the formal form).", overlaps: ["verb-patterns"],
    flags: ["'me asking' is acceptable in informal English; the stem's 'I hope you don't mind' formal frame supports 'my' but this is register-sensitive. Review before mass use."] }),
  d.correct({ b: "personal", t: "whom-object", L: "B2", diff: 3, focus: "Object pronoun (not subject) after 'than' in comparative clauses in formal writing", pre: ["object-pronouns", "subject-pronouns"],
    instr: "Make the sentence formally correct. Write the whole sentence.", source: "The manager is much more experienced than me am.", key: "The manager is much more experienced than I am.", why: "With a following verb 'am', the subject form 'I' is required." }),

  // ---------------- C1 ----------------
  d.guided({ b: "reflexive", t: "emphatic-reflexive", L: "C1", diff: 2, focus: "Reflexive used emphatically, not as an object", pre: ["reflexive-pronouns"],
    prompt: "Write one sentence in which a reflexive pronoun is used for EMPHASIS (for example, to stress that a person did something personally), not as the object of the verb.",
    required: "an emphatic/intensive reflexive pronoun (e.g. 'The director herself signed it') where removing the pronoun leaves a grammatical sentence", constraints: ["exactly one sentence", "the reflexive must not be the direct object"] }),
  d.mcq({ b: "personal", t: "it-anticipatory", L: "C1", diff: 2, focus: "Anticipatory 'it' with an extraposed that-clause", pre: ["dummy-it", "verb-that-clause"],
    prompt: "______ is widely accepted that early intervention improves outcomes.", options: ["It", "There", "That", "This"], key: 0, why: "Anticipatory 'it' introduces the extraposed clause.", overlaps: ["sentence-structure"] }),
  d.rewrite({ b: "personal", t: "it-anticipatory", L: "C1", diff: 3, focus: "Extraposing a clausal subject with anticipatory 'it'", pre: ["dummy-it"],
    source: "That he resigned so suddenly surprised everyone.", hint: "It ______.", key: "surprised everyone that he resigned so suddenly", why: "Heavy clausal subject moved to the end; 'it' fills the subject slot." }),
  d.mcq({ b: "substitution", t: "one-ones", L: "C1", diff: 2, focus: "'those' as a formal substitute for 'the ones' before a post-modifier", pre: ["one-ones-another", "demonstratives"],
    prompt: "The results of the second trial were far more reliable than ______ of the first.", options: ["those", "these", "the ones which", "that"], key: 0, why: "Plural 'results' + post-modifier → those." }),

  // ---------------- C2 ----------------
  d.mcq({ b: "reflexive", t: "reflexive-after-preposition", L: "C2", diff: 3, focus: "Object vs reflexive after a preposition of place with a co-referential subject", pre: ["reflexive-pronouns", "object-pronouns"],
    prompt: "She closed the door quietly behind ______ and put the bag down beside ______.", options: ["her / her", "herself / herself", "her / herself", "herself / her"], key: 0, why: "After prepositions of place, English uses the object form even when co-referential (behind her, beside her).",
    flags: ["c2-check: place-preposition exception to reflexive marking is a purely grammatical distinction most learners never acquire. C2 provisional."] }),
];