import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("questions-negation");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ"), B1O = leg("B1_OPEN_GRAMMAR"), B2 = leg("B2_MCQ"), C1 = leg("C1_MCQ"), B2O = leg("B2_OPEN_GRAMMAR"), C1O = leg("C1_OPEN_GRAMMAR");

export default [
  // ---------------- A1 ----------------
  d.mcq({ b: "yes-no", t: "do-does", L: "A1", diff: 1, focus: "Do with you in present simple questions", pre: ["auxiliary-do", "present-simple"],
    prompt: "______ you like coffee?", options: ["Are", "Does", "Do", "Is"], key: 2, why: "Main verb 'like' + you → Do.", legacy: A1("______ you like coffee?") }),
  d.mcq({ b: "yes-no", t: "do-does", L: "A1", diff: 1, focus: "Does with third person singular", pre: ["auxiliary-do", "present-simple"],
    prompt: "______ your sister work here?", options: ["Do", "Is", "Does", "Are"], key: 2, why: "Third person singular → Does.", legacy: A1("______ your sister work here?") }),
  d.mcq({ b: "yes-no", t: "be-vs-do", L: "A1", diff: 2, focus: "be-questions invert directly; no 'do'", pre: ["subject-auxiliary-inversion", "be-copula"],
    prompt: "______ she from Canada?", options: ["Does", "Is", "Do", "Are"], key: 1, why: "No main verb → Is she.", legacy: A1("______ she from Canada?") }),
  d.mcq({ b: "yes-no", t: "be-vs-do", L: "A1", diff: 2, focus: "Does + have (have is a main verb here)", pre: ["auxiliary-do"],
    prompt: "______ he have a car?", options: ["Do", "Is", "Does", "Has"], key: 2, why: "'have' as main verb → Does he have.", legacy: A1("______ he have a car?") }),
  d.mcq({ b: "yes-no", t: "progressive-question", L: "A1", diff: 2, focus: "Are + subject + -ing", pre: ["subject-auxiliary-inversion", "be-auxiliary"],
    prompt: "______ you watching TV?", options: ["Do", "Are", "Does", "Is"], key: 1, why: "-ing → be auxiliary; you → Are.", legacy: A1("______ you watching TV?") }),
  d.mcq({ b: "wh-questions", t: "wh-word-choice", L: "A1", diff: 1, focus: "Where for place", pre: ["wh-words"],
    prompt: "______ do you live?", options: ["Who", "Where", "What", "How"], key: 1, why: "Place → Where.", legacy: A1("______ do you live?") }),
  d.mcq({ b: "wh-questions", t: "wh-word-choice", L: "A1", diff: 1, focus: "When for time", pre: ["wh-words"],
    prompt: "______ is your birthday?", options: ["Where", "Who", "When", "What"], key: 2, why: "Time → When.", legacy: A1("______ is your birthday?") }),
  d.mcq({ b: "wh-questions", t: "wh-word-choice", L: "A1", diff: 1, focus: "Who for a person", pre: ["wh-words"],
    prompt: "______ is that man?", options: ["Who", "Where", "When", "How"], key: 0, why: "Person → Who.", legacy: A1("______ is that man?") }),
  d.mcq({ b: "wh-questions", t: "progressive-wh", L: "A1", diff: 2, focus: "What + are + you + doing", pre: ["wh-words", "be-auxiliary"],
    prompt: "What ______ you doing?", options: ["do", "is", "are", "does"], key: 2, why: "-ing + you → are.", legacy: A1("What ______ you doing?") }),
  d.mcq({ b: "negation", t: "dont-doesnt", L: "A1", diff: 1, focus: "don't with I", pre: ["auxiliary-do"],
    prompt: "I ______ like cold weather.", options: ["doesn't", "don't", "am not", "not"], key: 1, why: "I + main verb → don't.", legacy: A1("I ______ like cold weather.") }),
  d.order({ b: "yes-no", t: "do-does", L: "A1", diff: 2, focus: "Auxiliary + subject + base verb order", pre: ["auxiliary-do", "subject-auxiliary-inversion"],
    tokens: ["speak", "does", "English", "he", "?"], key: ["does", "he", "speak", "English", "?"], why: "Aux + S + V + O." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "wh-questions", t: "how-often", L: "A2", diff: 1, focus: "does after 'How often' with a singular subject", pre: ["auxiliary-do", "wh-words"],
    prompt: "How often ______ your brother play football?", options: ["is", "does", "has", "do"], key: 1, why: "Third person + main verb → does.", legacy: A2("How often ______ your brother play football?") }),
  d.mcq({ b: "yes-no", t: "past-did", L: "A2", diff: 1, focus: "Did for past simple questions", pre: ["auxiliary-do", "past-simple"],
    prompt: "______ you see Tom at the party?", options: ["Did", "Have", "Were", "Do"], key: 0, why: "Past + main verb → Did.", legacy: A2("______ you see Tom at the party?") }),
  d.mcq({ b: "wh-questions", t: "past-wh", L: "A2", diff: 2, focus: "did in a past wh-question", pre: ["auxiliary-do", "wh-words", "past-simple"],
    prompt: "Where ______ you go on holiday last year?", options: ["did", "have", "were", "do"], key: 0, why: "'last year' + main verb → did.", legacy: A2("Where ______ you go on holiday last year?") }),
  d.mcq({ b: "wh-questions", t: "wh-word-choice", L: "A2", diff: 1, focus: "Why for reason", pre: ["wh-words"],
    prompt: "______ did you buy that jacket?", options: ["Why", "What", "Which", "Who"], key: 0, why: "Reason → Why.", legacy: A2("______ did you buy that jacket?") }),
  d.mcq({ b: "wh-questions", t: "how-long-perfect", L: "A2", diff: 2, focus: "have in a How long ... present perfect question", pre: ["present-perfect", "subject-auxiliary-inversion"],
    prompt: "How long ______ you lived here?", options: ["do", "are", "have", "did"], key: 2, why: "'lived' + duration → have.", legacy: A2("How long ______ you lived here?") }),
  d.order({ b: "wh-questions", t: "past-wh", L: "A2", diff: 2, focus: "Wh + did + subject + base verb + time", pre: ["wh-words", "auxiliary-do", "subject-auxiliary-inversion", "past-simple"],
    instr: "Put the words in the correct order to make a question.", tokens: ["did", "where", "go", "you", "summer", "last", "?"], key: ["where", "did", "you", "go", "last", "summer", "?"], why: "Wh + aux + S + V + time." }),
  d.mcq({ b: "subject-questions", t: "who-subject", L: "A2", diff: 2, focus: "Subject question: no 'did', verb in past form", pre: ["subject-questions", "wh-words"],
    prompt: "______ the window?", options: ["Who broke", "Who did break", "Who did broke", "Who breaks did"], key: 0, why: "'Who' is the subject → no auxiliary." }),
  d.correct({ b: "negation", t: "dont-doesnt", L: "A2", diff: 2, focus: "doesn't + base form (no -s on main verb)", pre: ["auxiliary-do", "third-person-s"],
    source: "My sister doesn't likes spicy food.", key: "My sister doesn't like spicy food.", why: "After doesn't, base form." }),
  d.mcq({ b: "negation", t: "wasnt-werent", L: "A2", diff: 1, focus: "Negative of past 'be' — no 'didn't'", pre: ["be-copula", "past-simple"],
    prompt: "The shops ______ open yesterday because it was a holiday.", options: ["didn't", "weren't", "wasn't", "don't"], key: 1, why: "'be' negates directly; plural past → weren't." }),

  // ---------------- B1 ----------------
  d.rewrite({ b: "indirect-questions", t: "embedded-order", L: "B1", diff: 2, focus: "Statement order and no 'does' inside an indirect question", pre: ["indirect-question-order", "present-simple"],
    instr: "Make the question more polite by completing the indirect question.", source: "Where does she live?", hint: "Could you tell me where ______?", key: "she lives", why: "Embedded → statement order.", overlaps: ["reported-speech"] }),
  d.mcq({ b: "indirect-questions", t: "embedded-if-whether", L: "B1", diff: 2, focus: "if/whether for embedded yes/no questions with statement order", pre: ["indirect-question-order"],
    prompt: "Do you know ______ open on Sundays?", options: ["if the bank is", "is the bank", "if is the bank", "does the bank"], key: 0, why: "Yes/no → if + statement order." }),
  d.mcq({ b: "tag-questions", t: "basic-tag", L: "B1", diff: 1, focus: "Negative tag after a positive statement, matching auxiliary", pre: ["tag-questions", "auxiliary-do"],
    prompt: "You live near the station, ______?", options: ["don't you", "do you", "aren't you", "isn't it"], key: 0, why: "Positive present simple → don't you." }),
  d.mcq({ b: "tag-questions", t: "basic-tag", L: "B1", diff: 2, focus: "Positive tag after a negative statement with 'be'", pre: ["tag-questions", "be-copula"],
    prompt: "She isn't coming tonight, ______?", options: ["is she", "isn't she", "does she", "is not she"], key: 0, why: "Negative statement → positive tag with the same auxiliary." }),
  d.mcq({ b: "wh-questions", t: "question-preposition", L: "B1", diff: 2, focus: "Preposition stranded at the end of a wh-question", pre: ["question-prepositions", "preposition-stranding"],
    prompt: "Which question is correct?", options: ["Who are you waiting for?", "For who are you waiting?", "Who for are you waiting?", "Whom are you waiting?"], key: 0, why: "Informal English strands the preposition at the end.", overlaps: ["prep-phrasal"] }),
  d.order({ b: "wh-questions", t: "question-preposition", L: "B1", diff: 2, focus: "Stranded preposition in a wh-question", pre: ["question-prepositions", "preposition-stranding"],
    instr: "Put the words in the correct order to make a question.", tokens: ["talking", "who", "you", "about", "are", "?"], key: ["who", "are", "you", "talking", "about", "?"], why: "Wh + aux + S + V + preposition.", overlaps: ["prep-phrasal"] }),
  d.mcq({ b: "negation", t: "no-vs-not", L: "B1", diff: 2, focus: "no + noun vs not + any", pre: ["no-not-none"],
    prompt: "I'm sorry, there are ______ tickets left for tonight.", options: ["no", "not", "none", "any"], key: 0, why: "Before a noun → no." }),
  // short-responses (so/neither) moved to pronouns/substitution (2026-09-09 taxonomy correction C2).
  d.guided({ b: "indirect-questions", t: "embedded-order", L: "B1", diff: 2, focus: "Productive indirect question with statement order", pre: ["indirect-question-order"],
    prompt: "Write one indirect question beginning with 'Do you know...' or 'Could you tell me...'", required: "an indirect question with correct statement word order (no inversion) after 'Do you know...' or 'Could you tell me...'",
    legacy: B1O("Write one indirect question beginning with 'Do you know...' or 'Could you tell me...'") }),

  // ---------------- B2 ----------------
  d.mcq({ b: "tag-questions", t: "negative-subject-tag", L: "B2", diff: 2, focus: "Negative subject → positive tag with 'they'", pre: ["negative-subjects", "tag-questions"],
    prompt: "Nobody called while I was out, ______?", options: ["didn't they", "did they", "did he", "didn't he"], key: 1, why: "'Nobody' makes the clause negative → positive tag; nobody → they." }),
  d.mcq({ b: "tag-questions", t: "imperative-tag", L: "B2", diff: 2, focus: "Tag after an imperative: will you / won't you", pre: ["tag-questions", "imperatives"],
    prompt: "Close the window, ______?", options: ["will you", "do you", "don't you", "shall you"], key: 0, why: "Imperative → will you.", overlaps: ["sentence-structure"] }),
  d.mcq({ b: "tag-questions", t: "lets-tag", L: "B2", diff: 1, focus: "Let's → shall we", pre: ["tag-questions"],
    prompt: "Let's start the meeting, ______?", options: ["shall we", "will we", "don't we", "do we"], key: 0, why: "Let's → shall we." }),
  d.mcq({ b: "negation", t: "negative-question", L: "B2", diff: 2, focus: "Negative question expecting agreement / expressing surprise", pre: ["negative-questions", "subject-auxiliary-inversion"],
    prompt: "Which question expresses surprise that she has NOT finished?", options: ["Hasn't she finished yet?", "Has she finished yet?", "She hasn't finished, has she?", "Did she finish?"], key: 0, why: "Negative question form marks surprise/expectation." }),
  d.correct({ b: "negation", t: "double-negative", L: "B2", diff: 1, focus: "Avoiding a double negative with 'anything'", pre: ["no-not-none", "indefinite-pronouns"],
    source: "I didn't see nothing unusual that night.", key: "I didn't see anything unusual that night.", alt: ["I saw nothing unusual that night."], why: "One negative per clause." }),
  d.rewrite({ b: "indirect-questions", t: "embedded-past", L: "B2", diff: 2, focus: "Embedded past question: statement order, no 'did'", pre: ["indirect-question-order", "past-simple"],
    source: "Why did they cancel the flight?", hint: "I have no idea why ______.", key: "they cancelled the flight", alt: ["they canceled the flight"], why: "No auxiliary in the embedded clause." }),
  d.mcq({ b: "wh-questions", t: "whom-formal", L: "B2", diff: 3, focus: "Formal 'whom' after a fronted preposition", pre: ["question-prepositions", "wh-words"],
    prompt: "______ should I address the complaint?", options: ["To whom", "To who", "Who to", "Whom"], key: 0, why: "Fronted preposition requires whom.", overlaps: ["prep-phrasal"] }),
  // emphasis-inversion: moved here from sentence-structure (2026-09-09, correction C1). Fronted-negative
  // inversion is the same subject-auxiliary inversion mechanic as question formation; the tool is taught
  // once and applied to two communicative purposes. Do not move back without recording a reason.
  d.mcq({ b: "emphasis-inversion", t: "never-inversion", L: "B2", diff: 3, focus: "Inversion after fronted 'Never'", pre: ["negative-adverbial-inversion", "subject-auxiliary-inversion", "present-perfect"],
    prompt: "Never ______ such a difficult exam.", options: ["I have taken", "have I taken", "I took", "did I have taken"], key: 1, why: "Fronted negative → aux + subject.", legacy: B2("Never ______ such a difficult exam."), overlaps: ["sentence-structure"] }),
  d.mcq({ b: "emphasis-inversion", t: "not-only-inversion", L: "B2", diff: 3, focus: "Inversion after 'Not only'", pre: ["negative-adverbial-inversion", "auxiliary-do"],
    prompt: "Not only ______ late, but he also forgot the documents.", options: ["he arrived", "did he arrive", "he did arrive", "arrived he"], key: 1, why: "Not only + did + subject + base verb.", legacy: B2("Not only ______ late, but he also forgot the documents.") }),
  d.guided({ b: "emphasis-inversion", t: "not-only-inversion", L: "B2", diff: 3, focus: "Productive Not only inversion", pre: ["negative-adverbial-inversion"],
    prompt: "Write a sentence beginning with Not only and use subject-auxiliary inversion.", required: "correct subject-auxiliary inversion after a fronted 'Not only'",
    legacy: B2O("Write a sentence beginning with Not only and use subject-auxiliary inversion.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "negation", t: "negative-scope", L: "C1", diff: 3, focus: "Scope of negation with 'not' before a to-infinitive vs after the main verb", pre: ["no-not-none"],
    prompt: "Which sentence means the speaker made a deliberate choice to stay silent?", options: ["I decided not to say anything.", "I didn't decide to say anything.", "I decided to say nothing about not it.", "I not decided to say anything."], key: 0, why: "'decided not to' = deliberate negative decision; 'didn't decide to' = no decision made." }),
  d.rewrite({ b: "negation", t: "negative-transfer", L: "C1", diff: 3, focus: "Transferred negation with think/suppose/believe ('I don't think ... will')", pre: ["no-not-none", "verb-that-clause"],
    instr: "Rewrite the sentence in the more natural English form, beginning with the words given.", source: "I think she won't accept the offer.", hint: "I don't ______.", key: "think she will accept the offer", alt: ["think she'll accept the offer"], why: "English prefers negating the reporting verb." }),
  d.mcq({ b: "tag-questions", t: "same-polarity-tag", L: "C1", diff: 3, focus: "Same-polarity (positive–positive) tag to express inference or sarcasm", pre: ["tag-questions"],
    prompt: "'So you've decided to leave, ______?' (said on realising the fact)", options: ["have you", "haven't you", "did you", "do you"], key: 0, why: "Positive–positive tag draws a conclusion from what has just been learned." }),
  d.mcq({ b: "emphasis-inversion", t: "only-after-inversion", L: "C1", diff: 2, focus: "Inversion in the main clause after fronted 'Only after ...'", pre: ["negative-adverbial-inversion", "auxiliary-do"],
    prompt: "Only after the results had been independently replicated ______ the researchers accept the hypothesis.", options: ["the researchers did", "did the researchers", "the researchers had", "had the researchers"], key: 1, why: "Only + adverbial → did + subject.", legacy: C1("Only after the results had been independently replicated ______ the researchers accept the hypothesis.") }),
  d.mcq({ b: "emphasis-inversion", t: "under-no-circumstances", L: "C1", diff: 2, focus: "Inversion after 'Under no circumstances'", pre: ["negative-adverbial-inversion"],
    prompt: "Under no circumstances ______ be released before the investigation is complete.", options: ["should the data", "the data should", "the data", "should"], key: 0, why: "Negative adverbial → modal + subject.",
    legacy: C1("Under no circumstances ______ the data be released before the investigation is complete.", "Legacy stem kept 'the data' outside the gap while the key was 'should', making the inverted option unattainable. Gap widened so the inversion itself is the choice.") }),
  d.rewrite({ b: "emphasis-inversion", t: "so-adj-inversion", L: "C1", diff: 3, focus: "Fronted 'So + adjective' with inversion", pre: ["negative-adverbial-inversion", "result-clauses"],
    source: "The lecture was so boring that several students fell asleep.", hint: "So ______ that several students fell asleep.", key: "boring was the lecture", why: "So + adj + be + subject." }),
  d.guided({ b: "emphasis-inversion", t: "only-after-inversion", L: "C1", diff: 3, focus: "Productive Only after inversion", pre: ["negative-adverbial-inversion"],
    prompt: "Rewrite a sentence beginning with 'Only after...' and use subject-auxiliary inversion.", required: "correct subject-auxiliary inversion after a fronted \"Only after...\"",
    legacy: C1O("Rewrite a sentence beginning with 'Only after...' and use subject-auxiliary inversion.") }),

  // ---------------- C2 ----------------
  d.rewrite({ b: "emphasis-inversion", t: "barely-when", L: "C2", diff: 1, focus: "Inversion with barely/hardly/scarcely ... when", pre: ["negative-adverbial-inversion", "past-perfect"],
    instr: "Rewrite the sentence beginning with the word given.", source: "She had barely sat down when the phone rang.", hint: "Barely ______.", key: "had she sat down when the phone rang", why: "Fronted 'Barely' → had + subject + pp ... when.",
    flags: ["c2-check: literary inversion with correlative 'when'; grammatical, not lexical. C2 provisional (upper C1 possible)."] }),
  d.mcq({ b: "negation", t: "negative-raising-modal", L: "C2", diff: 3, focus: "Litotes / negative scope with 'not un-' and quantifier interaction ('not everyone', 'not any')", pre: ["no-not-none"],
    prompt: "Which sentence means that SOME (but not all) of the members voted?", options: ["Not all the members voted.", "All the members did not vote.", "None of the members voted.", "Not any member voted."], key: 0, why: "'Not all' negates the quantifier (partial); 'All ... did not' is ambiguous/total in standard reading.",
    flags: ["c2-check: quantifier–negation scope is a genuinely syntactic-semantic phenomenon; option 2's ambiguity is the diagnostic. C2 provisional."] }),
];