import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("reported-speech");
const B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR");

// Domain introduced at B1 — no A1/A2 items by design.
export default [
  // ---------------- B1 ----------------
  d.mcq({ b: "statements", t: "backshift-present", L: "B1", diff: 1, focus: "Present → past backshift with pronoun shift", pre: ["tense-backshift", "pronoun-time-shift", "past-simple"],
    prompt: "Anna said, 'I am tired.' Which sentence is correct?", options: ["Anna said that I am tired.", "Anna said that she was tired.", "Anna said that she is tired.", "Anna said that she tired."], key: 1, why: "am → was; I → she.", legacy: B1("Anna said, 'I am tired.' Which sentence is correct?") }),
  d.mcq({ b: "statements", t: "backshift-will", L: "B1", diff: 2, focus: "will → would; tomorrow → the next day; you → me", pre: ["tense-backshift", "pronoun-time-shift"],
    prompt: "Tom said, 'I will call you tomorrow.'", options: ["Tom said he would call me the next day.", "Tom said he will call me tomorrow.", "Tom said he would call you tomorrow.", "Tom said he called me the next day."], key: 0, why: "Full backshift + deictic shift.", legacy: B1("Tom said, 'I will call you tomorrow.'") }),
  d.mcq({ b: "questions", t: "reported-wh-question", L: "B1", diff: 2, focus: "Statement order in a reported wh-question", pre: ["reported-question-order", "tense-backshift"],
    prompt: "She asked me where ______.", options: ["did I live", "I lived", "do I live", "lived I"], key: 1, why: "No inversion, no 'did'.", legacy: B1("She asked me where ______."), overlaps: ["questions-negation"] }),
  d.rewrite({ b: "questions", t: "reported-wh-question", L: "B1", diff: 2, focus: "Producing a reported wh-question", pre: ["reported-question-order", "tense-backshift", "pronoun-time-shift"],
    instr: "Report the question, starting with the words given.", source: "'Where do you live?' she asked me.", hint: "She asked me where ______.", key: "I lived", why: "Statement order + backshift + pronoun shift.", overlaps: ["questions-negation"] }),
  d.rewrite({ b: "questions", t: "reported-yes-no", L: "B1", diff: 2, focus: "if/whether in a reported yes/no question", pre: ["reported-question-order", "tense-backshift"],
    instr: "Report the question, starting with the words given.", source: "'Are you hungry?' my mother asked.", hint: "My mother asked ______.", key: "if I was hungry", alt: ["whether I was hungry", "me if I was hungry", "me whether I was hungry"], why: "Yes/no → if/whether + statement order." }),
  d.gap({ b: "statements", t: "backshift-past", L: "B1", diff: 2, focus: "Past simple → past perfect backshift", pre: ["tense-backshift", "past-perfect"],
    instr: "Complete the reported sentence.", source: "'I lost my keys,' he said.  →  He said he ______ (lose) his keys.", key: "had lost", alt: ["lost"], why: "Past simple backshifts to past perfect (past simple also accepted in informal reporting)." }),
  d.mcq({ b: "commands-requests", t: "tell-sb-to", L: "B1", diff: 1, focus: "Reported command: tell + object + to-infinitive", pre: ["reported-commands", "verb-object-infinitive"],
    prompt: "'Close the window,' the teacher said to us. → The teacher ______.", options: ["told us to close the window", "told us close the window", "said us to close the window", "told to us closing the window"], key: 0, why: "tell + object + to-infinitive.", overlaps: ["verb-patterns"] }),
  d.mcq({ b: "statements", t: "say-tell", L: "B1", diff: 1, focus: "tell requires an object; say does not", pre: ["say-tell"],
    prompt: "She ______ that the meeting had been cancelled.", options: ["said me", "told", "said", "told to me"], key: 2, why: "say + that-clause (no object)." }),
  d.guided({ b: "statements", t: "backshift-present", L: "B1", diff: 1, focus: "Productive reported statement with backshift", pre: ["tense-backshift"],
    prompt: "Write one sentence reporting something another person said. Use reported speech.", required: "reported speech with correct tense backshift from the original statement",
    legacy: B1O("Write one sentence reporting something another person said. Use reported speech.") }),
  d.guided({ b: "statements", t: "backshift-will", L: "B1", diff: 2, focus: "Productive reported promise/prediction", pre: ["tense-backshift"],
    prompt: "Write one sentence reporting a promise, prediction, or future statement made by another person.", required: "reported speech correctly reporting a promise/prediction (would/will backshifted appropriately)",
    legacy: B1O("Write one sentence reporting a promise, prediction, or future statement made by another person.") }),

  // ---------------- B2 ----------------
  d.mcq({ b: "modals-reported", t: "can-could", L: "B2", diff: 1, focus: "can → could with pronoun shift", pre: ["reported-modals", "pronoun-time-shift"],
    prompt: "He said, 'I can't attend the meeting.'", options: ["He said he couldn't attend the meeting.", "He said he can't attended the meeting.", "He said I couldn't attend the meeting.", "He said he didn't attend the meeting."], key: 0, why: "can't → couldn't; I → he.", legacy: B2("He said, 'I can't attend the meeting.'") }),
  d.mcq({ b: "reporting-verbs", t: "deny-gerund", L: "B2", diff: 2, focus: "deny + (perfect) gerund", pre: ["reporting-verb-patterns", "perfect-gerund"],
    prompt: "She ______ having taken the documents.", options: ["denied", "suggested", "insisted", "warned"], key: 0, why: "Only deny takes a direct gerund here.", legacy: B2("She ______ having taken the documents.") }),
  d.rewrite({ b: "reporting-verbs", t: "advise-object-infinitive", L: "B2", diff: 2, focus: "advise + object + to-infinitive", pre: ["reporting-verb-patterns", "verb-object-infinitive"],
    instr: "Report the advice, starting with the words given.", source: "'You should see a doctor,' he said to me.", hint: "He advised me ______.", key: "to see a doctor", why: "advise + object + to-infinitive.", overlaps: ["verb-patterns"] }),
  d.rewrite({ b: "reporting-verbs", t: "suggest-pattern", L: "B2", diff: 2, focus: "suggest + -ing / that-clause (no object + infinitive)", pre: ["reporting-verb-patterns", "gerund"],
    instr: "Report the suggestion, starting with the words given.", source: "'Let's take a break,' said Ali.", hint: "Ali suggested ______.", key: "taking a break", alt: ["that we take a break", "that we took a break", "we take a break"], why: "suggest + -ing or that-clause.", overlaps: ["verb-patterns"] }),
  d.mcq({ b: "modals-reported", t: "must-had-to", L: "B2", diff: 2, focus: "must (obligation) → had to when reported", pre: ["reported-modals", "semi-modals"],
    prompt: "'You must finish the report today,' my boss said. → My boss said I ______ the report that day.", options: ["had to finish", "must finished", "have to finish", "must have finished"], key: 0, why: "Obligation must → had to.", overlaps: ["modals"] }),
  d.gap({ b: "statements", t: "time-place-shift", L: "B2", diff: 2, focus: "Deictic shifts: here → there, now → then, this → that", pre: ["pronoun-time-shift"],
    instr: "Complete the reported version with the correct shifted words.", source: "'I'll meet you here tomorrow,' she said.  →  She said she would meet me ______ the ______ day.", key: ["there", "next"], alt: [["there", "following"]], why: "here → there; tomorrow → the next/following day." }),
  d.mcq({ b: "commands-requests", t: "ask-request", L: "B2", diff: 2, focus: "Reported polite request: ask + object + to-infinitive (not 'ask that')", pre: ["reported-commands"],
    prompt: "'Could you open the window, please?' → She ______.", options: ["asked me to open the window", "asked me that I open the window", "asked me could I open the window", "asked to me opening the window"], key: 0, why: "Request → ask + object + to-infinitive." }),
  d.mcq({ b: "commands-requests", t: "negative-command", L: "B2", diff: 2, focus: "Reported negative command: tell + object + not to", pre: ["reported-commands"],
    prompt: "'Don't touch the wires,' the electrician warned us. → The electrician warned us ______ the wires.", options: ["not to touch", "to not touching", "don't touch", "that not touch"], key: 0, why: "warn + object + not + to-infinitive." }),
  d.guided({ b: "reporting-verbs", t: "reporting-verb-choice", L: "B2", diff: 2, focus: "Productive reporting verb with correct complementation", pre: ["reporting-verb-patterns"],
    prompt: "Write a sentence using deny, admit, insist, recommend, warn, or suggest to report someone's words.", required: "a reporting verb (deny/admit/insist/recommend/warn/suggest) used with the correct following structure",
    legacy: B2O("Write a sentence using deny, admit, insist, recommend, warn, or suggest to report someone's words.") }),
  d.guided({ b: "modals-reported", t: "can-could", L: "B2", diff: 2, focus: "Productive reporting of a modal statement", pre: ["reported-modals"],
    prompt: "Report something another person said about an ability, possibility, or obligation. Use appropriate tense and pronoun changes.", required: "reported speech with correct tense/modal backshift for ability, possibility, or obligation",
    legacy: B2O("Report something another person said about an ability, possibility, or obligation. Use appropriate tense and pronoun changes.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "backshift-exceptions", t: "general-truth-no-backshift", L: "C1", diff: 2, focus: "No backshift for a general truth", pre: ["backshift-exceptions", "present-simple"],
    prompt: "My doctor told me that I ______ allergic to penicillin, and I still am.", options: ["am", "was", "had been", "would be"], key: 0, why: "'and I still am' asserts present validity, so the backshifted forms create a false implication that the fact no longer holds; only the unshifted present is defensible." }),
  d.mcq({ b: "backshift-exceptions", t: "still-true-no-backshift", L: "C1", diff: 2, focus: "Choice of no-backshift signals the statement is still true", pre: ["backshift-exceptions"],
    prompt: "Which reported sentence most clearly implies that Sara STILL lives in Bukhara?", options: ["Sara told me she lives in Bukhara.", "Sara told me she lived in Bukhara.", "Sara told me she had lived in Bukhara.", "Sara told me she would live in Bukhara."], key: 0, why: "Present tense in the reported clause = still true." }),
  d.mcq({ b: "modals-reported", t: "modals-no-backshift", L: "C1", diff: 2, focus: "would/could/might/should/ought do not backshift", pre: ["reported-modals"],
    prompt: "'You should apologise,' she said. → She said I ______ apologise.", options: ["should", "should have", "would should", "had to"], key: 0, why: "should is unchanged in reported speech.", overlaps: ["modals"] }),
  d.rewrite({ b: "reporting-verbs", t: "accuse-of", L: "C1", diff: 2, focus: "accuse + object + of + -ing", pre: ["reporting-verb-patterns", "preposition-gerund"],
    instr: "Report the words, starting with the words given.", source: "'You broke my phone!' Dilnoza said to her brother.", hint: "Dilnoza accused her brother ______.", key: "of breaking her phone", alt: ["of having broken her phone"], why: "accuse sb of + -ing.", overlaps: ["prep-phrasal"] }),
  d.rewrite({ b: "questions", t: "reported-embedded-past", L: "C1", diff: 3, focus: "Reporting a past-tense question: past → past perfect with statement order", pre: ["reported-question-order", "tense-backshift", "past-perfect"],
    instr: "Report the question, starting with the words given.", source: "'Why didn't you call me last night?' Aziz asked.", hint: "Aziz asked me why ______ the night before.", key: "I hadn't called him", alt: ["I had not called him"], why: "didn't call → hadn't called; me → him; last night → the night before." }),
  d.guided({ b: "backshift-exceptions", t: "general-truth-no-backshift", L: "C1", diff: 2, focus: "Productive no-backshift for a general truth", pre: ["backshift-exceptions", "tense-backshift"],
    prompt: "Write one sentence reporting something a teacher or scientist said that is a general truth (still true now). Use a past reporting verb (said/explained/told) but keep the reported fact in the present tense.",
    required: "past reporting verb + that-clause in present simple expressing a general/still-true fact, with no backshift", constraints: ["exactly one sentence", "reporting verb must be in the past", "reported clause must stay present"] }),

  // ---------------- C2 ----------------
  d.mcq({ b: "backshift-exceptions", t: "free-indirect-speech", L: "C2", diff: 3, focus: "Free indirect speech: backshift and pronoun shift without a reporting clause", pre: ["tense-backshift", "pronoun-time-shift"],
    prompt: "Which sentence is written in FREE indirect speech (no reporting verb, but shifted tense and pronouns)?", options: ["Was she really going to leave tomorrow? He couldn't believe it.", "He asked whether she was really going to leave the next day.", "'Are you really going to leave tomorrow?' he asked.", "He could not believe that she is leaving tomorrow."], key: 0, why: "Shifted tense/pronoun but question form and deixis retained — literary free indirect style.",
    flags: ["c2-check: free indirect discourse is a literary-register grammatical phenomenon; recognition-level only. C2 provisional."] }),
  d.rewrite({ b: "modals-reported", t: "reported-inverted-conditional", L: "C2", diff: 3, focus: "Reporting a conditional with an inverted form in formal register", pre: ["reported-modals", "inverted-conditional", "tense-backshift"],
    instr: "Report the words in formal register, starting with the words given and keeping the inversion.", source: "'Should there be any delay, we will notify you,' the airline said.", hint: "The airline said that ______ any delay, they would notify us.", key: "should there be", why: "Inverted 'should' condition is retained; will → would.", overlaps: ["conditionals-wishes"],
    flags: ["c2-check: combines retained inversion with modal backshift. C2 provisional; overlaps heavily with Conditionals & Wishes."] }),
];