import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("sentence-structure");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), C1 = leg("C1_MCQ"), B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR"), C1O = leg("C1_OPEN_GRAMMAR");

export default [
  // ---------------- A1 ---------------- (be as predication; there is/are; imperatives; basic conjunctions — locked/provisional rulings)
  d.mcq({ b: "predication", t: "be-am-is-are", L: "A1", diff: 1, focus: "am with I in an identity statement", pre: ["be-copula"],
    prompt: "I ______ a student.", options: ["am", "is", "are", "be"], key: 0, why: "I → am.", legacy: A1("I ______ a student.") }),
  d.mcq({ b: "predication", t: "be-am-is-are", L: "A1", diff: 1, focus: "is with a singular third-person subject", pre: ["be-copula"],
    prompt: "She ______ my sister.", options: ["am", "are", "is", "be"], key: 2, why: "She → is.", legacy: A1("She ______ my sister.") }),
  d.mcq({ b: "predication", t: "be-am-is-are", L: "A1", diff: 1, focus: "are with plural subject (location predicate)", pre: ["be-copula"],
    prompt: "They ______ at home now.", options: ["is", "are", "am", "be"], key: 1, why: "They → are.", legacy: A1("They ______ at home now.") }),
  d.mcq({ b: "predication", t: "be-am-is-are", L: "A1", diff: 2, focus: "are with a compound subject (my brother and I)", pre: ["be-copula", "subject-verb-agreement"],
    prompt: "My brother and I ______ students.", options: ["am", "is", "are", "be"], key: 2, why: "Two people → are.", legacy: A1("My brother and I ______ students.") }),
  d.mcq({ b: "predication", t: "be-question", L: "A1", diff: 2, focus: "Are + you inverted question with be", pre: ["be-copula", "subject-auxiliary-inversion"],
    prompt: "______ you tired?", options: ["Is", "Are", "Am", "Be"], key: 1, why: "you → Are.", legacy: A1("______ you tired?") }),
  d.mcq({ b: "existential", t: "there-is-are", L: "A1", diff: 1, focus: "There is + singular", pre: ["there-existential"],
    prompt: "______ a book on the desk.", options: ["There are", "There is", "They are", "It are"], key: 1, why: "Singular → There is.", legacy: A1("______ a book on the desk.") }),
  d.mcq({ b: "existential", t: "there-is-are", L: "A1", diff: 1, focus: "There are + plural", pre: ["there-existential"],
    prompt: "______ two chairs in the room.", options: ["There is", "There are", "It is", "They is"], key: 1, why: "Plural → There are.", legacy: A1("______ two chairs in the room.") }),
  d.mcq({ b: "existential", t: "there-question", L: "A1", diff: 2, focus: "Is there ...? with an uncountable noun", pre: ["there-existential", "countable-uncountable"],
    prompt: "______ any milk in the fridge?", options: ["Is there", "Are there", "There is", "There are"], key: 0, why: "milk uncountable + question → Is there.", legacy: A1("______ any milk in the fridge?") }),
  d.mcq({ b: "imperatives", t: "affirmative-imperative", L: "A1", diff: 1, focus: "Base form for an imperative", pre: ["imperatives"],
    prompt: "______ the door, please.", options: ["Opens", "Opening", "Open", "To open"], key: 2, why: "Imperative = base form.", legacy: A1("______ the door, please.") }),
  d.mcq({ b: "imperatives", t: "negative-imperative", L: "A1", diff: 1, focus: "Don't + base form for a negative imperative", pre: ["imperatives", "auxiliary-do"],
    prompt: "______ touch that. It is hot.", options: ["Don't", "Doesn't", "Not", "No"], key: 0, why: "Negative imperative → Don't.", legacy: A1("______ touch that. It is hot.") }),
  d.mcq({ b: "conjunctions", t: "and-but-or", L: "A1", diff: 1, focus: "and for addition", pre: ["coordinating-conjunctions"],
    prompt: "I like tea ______ coffee.", options: ["but", "and", "because", "or"], key: 1, why: "Adding two liked items → and.", legacy: A1("I like tea ______ coffee.") }),
  d.mcq({ b: "conjunctions", t: "so-result", L: "A1", diff: 2, focus: "so for a result", pre: ["coordinating-conjunctions"],
    prompt: "I am tired, ______ I am going to bed.", options: ["so", "but", "because", "or"], key: 0, why: "Result → so.", legacy: A1("I am tired, ______ I am going to bed.") }),
  d.mcq({ b: "conjunctions", t: "and-but-or", L: "A1", diff: 2, focus: "but for contrast", pre: ["coordinating-conjunctions"],
    prompt: "She is young ______ she is very responsible.", options: ["and", "because", "but", "so"], key: 2, why: "Contrast → but.", legacy: A1("She is young ______ she is very responsible.") }),
  d.order({ b: "word-order", t: "svo-basic", L: "A1", diff: 1, focus: "Subject + verb + object", pre: ["svo-order"],
    tokens: ["apples", "likes", "my sister"], key: ["my sister", "likes", "apples"], why: "S + V + O." }),
  d.order({ b: "word-order", t: "place-time-order", L: "A1", diff: 2, focus: "Place before time at the end of a sentence", pre: ["svo-order"],
    tokens: ["at the weekend", "we", "football", "play", "in the park"], key: ["we", "play", "football", "in the park", "at the weekend"], why: "S + V + O + place + time." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "conjunctions", t: "because", L: "A2", diff: 1, focus: "because for a reason", pre: ["subordinating-conjunctions"],
    prompt: "I stayed at home ______ I was feeling sick.", options: ["but", "because", "so", "although"], key: 1, why: "Reason → because.", legacy: A2("I stayed at home ______ I was feeling sick.") }),
  d.mcq({ b: "relative-clauses", t: "who-people", L: "A2", diff: 1, focus: "who for a person in a defining relative clause", pre: ["relative-pronouns", "defining-relative"],
    prompt: "The woman ______ lives next door is a teacher.", options: ["which", "who", "where", "whose"], key: 1, why: "Person → who.", legacy: A2("The woman ______ lives next door is a teacher.") }),
  d.mcq({ b: "relative-clauses", t: "that-which-things", L: "A2", diff: 1, focus: "that/which for a thing", pre: ["relative-pronouns", "defining-relative"],
    prompt: "This is the book ______ I told you about.", options: ["who", "where", "that", "whose"], key: 2, why: "Thing → that.", legacy: A2("This is the book ______ I told you about.") }),
  d.mcq({ b: "relative-clauses", t: "where-place", L: "A2", diff: 2, focus: "where for a place (no object gap)", pre: ["relative-pronouns", "defining-relative"],
    prompt: "That is the restaurant ______ we had dinner.", options: ["who", "where", "which", "whose"], key: 1, why: "Place + complete clause → where.", legacy: A2("That is the restaurant ______ we had dinner.") }),
  d.order({ b: "word-order", t: "double-object", L: "A2", diff: 2, focus: "S + V + indirect object + direct object", pre: ["svo-order"],
    tokens: ["a", "gave", "sister", "I", "present", "my"], key: ["I", "gave", "my", "sister", "a", "present"], why: "S + V + IO + DO." }),
  d.gap({ b: "existential", t: "there-was-were", L: "A2", diff: 2, focus: "there was/were agreement in the past", pre: ["there-existential", "subject-verb-agreement"],
    instr: "Complete each gap with was or were.", source: "There ______ a lot of people at the party, but there ______ nobody I knew.", key: ["were", "was"], why: "people → were; nobody → was." }),
  d.mcq({ b: "conjunctions", t: "when-time-clause", L: "A2", diff: 2, focus: "Present simple (not will) in a future time clause after when", pre: ["subordinating-conjunctions", "present-simple", "future-will"],
    prompt: "I'll call you when I ______ home.", options: ["get", "will get", "am getting", "got"], key: 0, why: "Time clause → present simple.", overlaps: ["tenses"] }),
  d.correct({ b: "imperatives", t: "lets", L: "A2", diff: 2, focus: "Let's + base form", pre: ["imperatives"],
    source: "Let's to go to the cinema tonight.", key: "Let's go to the cinema tonight.", why: "Let's + bare infinitive." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "relative-clauses", t: "object-relative-omission", L: "B1", diff: 2, focus: "Object relative pronoun optional; 'where' impossible for a thing", pre: ["relative-pronouns", "defining-relative"],
    prompt: "Which option is NOT possible in this sentence?  The book ______ I bought yesterday is excellent.", options: ["that", "which", "(nothing)", "where"], key: 3, why: "where is for places; that/which/omission all work.",
    legacy: B1("The book ______ I bought yesterday is excellent.", "Legacy key 'no relative pronoun is necessary' was one of two valid answers ('that' also fits). Reframed as 'which option is NOT possible' so exactly one option is correct."), overlaps: ["pronouns"] }),
  // Legacy B1 'The woman ______ lives next door is a doctor.' and 'This is the restaurant ______ we had
  // dinner last night.' are near-duplicates of the A2 items above and were NOT reused.
  d.mcq({ b: "relative-clauses", t: "which-vs-what", L: "B1", diff: 2, focus: "which (relative) vs what (not a relative pronoun) after a noun", pre: ["relative-pronouns", "defining-relative"],
    prompt: "I couldn't find the file ______ you sent me.", options: ["which", "what", "who", "whose"], key: 0, why: "'what' cannot follow a noun as a relative pronoun." }),
  d.mcq({ b: "conjunctions", t: "although-despite", L: "B1", diff: 2, focus: "although + clause for concession", pre: ["concession-linkers", "subordinating-conjunctions"],
    prompt: "______ it was raining, we went for a walk.", options: ["Although", "Despite", "Because", "However"], key: 0, why: "Followed by a clause → Although." }),
  d.mcq({ b: "clause-linkers", t: "purpose-so-that", L: "B1", diff: 2, focus: "so that + clause for purpose (vs so + result)", pre: ["purpose-clauses"],
    prompt: "I wrote the address down ______ I wouldn't forget it.", options: ["so that", "in order to", "for", "because of"], key: 0, why: "Purpose + clause → so that." }),
  d.gap({ b: "relative-clauses", t: "whose", L: "B1", diff: 2, focus: "whose for possession in a relative clause", pre: ["relative-pronouns"],
    instr: "Complete the gap with ONE relative word.", source: "That's the girl ______ brother plays for the national team.", key: "whose", why: "Possession → whose." }),
  d.order({ b: "word-order", t: "indirect-object-to", L: "B1", diff: 2, focus: "Direct object + to + indirect object order", pre: ["svo-order"],
    tokens: ["to", "sent", "the manager", "she", "the report"], key: ["she", "sent", "the report", "to", "the manager"], why: "S + V + DO + to + IO." }),
  d.correct({ b: "conjunctions", t: "although-despite", L: "B1", diff: 3, focus: "despite + noun/-ing, not + clause", pre: ["concession-linkers"],
    source: "Despite it was late, we kept working.", key: "Although it was late, we kept working.", alt: ["Despite the late hour, we kept working.", "Despite its being late, we kept working."], why: "despite cannot take a finite clause." }),
  d.guided({ b: "relative-clauses", t: "who-people", L: "B1", diff: 2, focus: "Productive defining relative clause", pre: ["defining-relative", "relative-pronouns"],
    prompt: "Write one sentence containing a defining relative clause with who, which, that, or where.", required: "a defining relative clause using who/which/that/where correctly",
    legacy: B1O("Write one sentence containing a defining relative clause with who, which, that, or where.") }),
  d.guided({ b: "relative-clauses", t: "object-relative-omission", L: "B1", diff: 3, focus: "Productive omitted object relative", pre: ["defining-relative"],
    prompt: "Write one sentence where the relative pronoun is the object and can be omitted.", required: "an object relative clause with the relative pronoun correctly omitted",
    legacy: B1O("Write one sentence where the relative pronoun is the object and can be omitted.") }),

  // ---------------- B2 ----------------
  d.mcq({ b: "relative-clauses", t: "non-defining-whose", L: "B2", diff: 2, focus: "whose in a non-defining clause", pre: ["non-defining-relative", "relative-pronouns"],
    prompt: "The researcher, ______ work has influenced the field, received an award.", options: ["who", "whom", "whose", "which"], key: 2, why: "Possession → whose.", legacy: B2("The researcher, ______ work has influenced the field, received an award.") }),
  d.mcq({ b: "relative-clauses", t: "preposition-which", L: "B2", diff: 2, focus: "Preposition + which (never 'that') in formal relatives", pre: ["relative-pronouns", "preposition-stranding"],
    prompt: "The company for ______ I work is expanding.", options: ["who", "which", "where", "what"], key: 1, why: "Fronted preposition → which.", legacy: B2("The company for ______ I work is expanding."), overlaps: ["prep-phrasal"] }),
  d.mcq({ b: "participle-clauses", t: "reduced-relative-passive", L: "B2", diff: 2, focus: "Past participle reducing a passive relative clause", pre: ["reduced-relative", "past-participle"],
    prompt: "The documents ______ yesterday need to be signed.", options: ["sending", "sent", "were sent", "which sent"], key: 1, why: "'which were sent' → sent.", legacy: B2("The documents ______ yesterday need to be signed."), overlaps: ["passive-causative"] }),
  d.mcq({ b: "participle-clauses", t: "having-done", L: "B2", diff: 2, focus: "Perfect participle clause for a completed prior action", pre: ["participle-clauses", "past-participle"],
    prompt: "______ the report, she left the office.", options: ["Having finished", "Finished", "To finish", "Has finished"], key: 0, why: "Prior completed action → Having + pp.", legacy: B2("______ the report, she left the office.") }),
  d.mcq({ b: "participle-clauses", t: "passive-participle-clause", L: "B2", diff: 2, focus: "Past participle clause with passive meaning", pre: ["participle-clauses", "past-participle"],
    prompt: "______ by thousands of tourists every year, the city has developed a large tourism industry.", options: ["Visiting", "Visited", "Having visit", "To visiting"], key: 1, why: "The city is visited → past participle.", legacy: B2("______ by thousands of tourists every year, the city has developed a large tourism industry."), overlaps: ["passive-causative"] }),
  d.mcq({ b: "emphasis-inversion", t: "never-inversion", L: "B2", diff: 3, focus: "Inversion after fronted 'Never'", pre: ["negative-adverbial-inversion", "subject-auxiliary-inversion", "present-perfect"],
    prompt: "Never ______ such a difficult exam.", options: ["I have taken", "have I taken", "I took", "did I have taken"], key: 1, why: "Fronted negative → aux + subject.", legacy: B2("Never ______ such a difficult exam."), overlaps: ["questions-negation"] }),
  d.mcq({ b: "emphasis-inversion", t: "not-only-inversion", L: "B2", diff: 3, focus: "Inversion after 'Not only'", pre: ["negative-adverbial-inversion", "auxiliary-do"],
    prompt: "Not only ______ late, but he also forgot the documents.", options: ["he arrived", "did he arrive", "he did arrive", "arrived he"], key: 1, why: "Not only + did + subject + base verb.", legacy: B2("Not only ______ late, but he also forgot the documents.") }),
  d.mcq({ b: "cleft", t: "what-cleft", L: "B2", diff: 2, focus: "What-cleft subject", pre: ["cleft-what"],
    prompt: "______ I need is a little more time.", options: ["That", "What", "Which", "It"], key: 1, why: "What + clause as subject.", legacy: B2("______ I need is a little more time.") }),
  d.mcq({ b: "clause-linkers", t: "despite-ing", L: "B2", diff: 1, focus: "Despite + -ing (no clause)", pre: ["concession-linkers"],
    prompt: "______ being exhausted, she continued working.", options: ["Although", "Despite", "However", "Even"], key: 1, why: "Followed by -ing → Despite.", legacy: B2("______ being exhausted, she continued working.") }),
  d.rewrite({ b: "participle-clauses", t: "reduced-relative-active", L: "B2", diff: 2, focus: "Reducing an active relative clause to a present participle phrase", pre: ["reduced-relative", "participle-clauses"],
    instr: "Rewrite the sentence, replacing the relative clause with a participle phrase.", source: "The man who is standing by the door is my uncle.", hint: "The man ______ is my uncle.", key: "standing by the door", why: "who is standing → standing." }),
  d.gap({ b: "clause-linkers", t: "result-so-that", L: "B2", diff: 2, focus: "such + a + adj + noun + that (result)", pre: ["result-clauses", "so-such"],
    instr: "Complete the gap with ONE word.", source: "It was ______ a boring film that we left halfway through.", key: "such", why: "such + a + adj + noun.", overlaps: ["adj-adv"] }),
  d.guided({ b: "participle-clauses", t: "having-done", L: "B2", diff: 2, focus: "Productive perfect participle clause", pre: ["participle-clauses"],
    prompt: "Write a sentence beginning with Having + past participle to show that one action happened before another.", required: "a participle clause beginning with Having + past participle, showing correct sequencing",
    legacy: B2O("Write a sentence beginning with Having + past participle to show that one action happened before another.") }),
  d.guided({ b: "emphasis-inversion", t: "not-only-inversion", L: "B2", diff: 3, focus: "Productive Not only inversion", pre: ["negative-adverbial-inversion"],
    prompt: "Write a sentence beginning with Not only and use subject-auxiliary inversion.", required: "correct subject-auxiliary inversion after a fronted 'Not only'",
    legacy: B2O("Write a sentence beginning with Not only and use subject-auxiliary inversion.") }),
  d.guided({ b: "relative-clauses", t: "non-defining-whose", L: "B2", diff: 2, focus: "Productive non-defining relative with commas", pre: ["non-defining-relative"],
    prompt: "Write a non-defining relative clause containing whose.", required: "a non-defining relative clause with whose, correctly set off by commas",
    legacy: B2O("Write a non-defining relative clause containing whose.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "participle-clauses", t: "present-participle-cause", L: "C1", diff: 2, focus: "Present participle clause (simultaneous/causal) vs perfect participle", pre: ["participle-clauses"],
    prompt: "______ that the funding was limited, the team designed a smaller study.", options: ["Knowing", "Having known", "Known", "To know"], key: 0, why: "A stative verb in a causal participle clause takes the present participle; 'Having known' forces a completed prior event reading that a continuing state cannot carry.",
    legacy: C1("______ the limitations of the sample, the authors avoided making broad conclusions.", "With 'acknowledge' (a dynamic verb) both the present and the perfect participle were defensible. Verb changed to the stative 'know', which blocks the perfect participle while keeping the causal present-participle clause as the target. Same branch, topic, level and difficulty.") }),
  d.mcq({ b: "participle-clauses", t: "reduced-relative-passive", L: "C1", diff: 1, focus: "Reduced passive relative in academic prose", pre: ["reduced-relative"],
    prompt: "The measures ______ to reduce energy consumption were implemented across all departments.", options: ["designed", "designing", "were designing", "which designing"], key: 0, why: "'which were designed' → designed.", legacy: C1("The measures ______ to reduce energy consumption were implemented across all departments.") }),
  d.mcq({ b: "emphasis-inversion", t: "only-after-inversion", L: "C1", diff: 2, focus: "Inversion in the main clause after fronted 'Only after ...'", pre: ["negative-adverbial-inversion", "auxiliary-do"],
    prompt: "Only after the results had been independently replicated ______ the researchers accept the hypothesis.", options: ["the researchers did", "did the researchers", "the researchers had", "had the researchers"], key: 1, why: "Only + adverbial → did + subject.", legacy: C1("Only after the results had been independently replicated ______ the researchers accept the hypothesis.") }),
  d.mcq({ b: "emphasis-inversion", t: "under-no-circumstances", L: "C1", diff: 2, focus: "Inversion after 'Under no circumstances'", pre: ["negative-adverbial-inversion"],
    prompt: "Under no circumstances ______ be released before the investigation is complete.", options: ["should the data", "the data should", "the data", "should"], key: 0, why: "Negative adverbial → modal + subject.",
    legacy: C1("Under no circumstances ______ the data be released before the investigation is complete.", "Legacy stem kept 'the data' outside the gap while the key was 'should', making the inverted option unattainable. Gap widened so the inversion itself is the choice.") }),
  d.mcq({ b: "subjunctive", t: "mandative-be", L: "C1", diff: 2, focus: "Mandative subjunctive base form after 'It is essential that'", pre: ["mandative-subjunctive"],
    prompt: "It is essential that every participant ______ informed of the revised procedure.", options: ["is", "be", "will be", "has been"], key: 1, why: "Mandative → base form 'be'.", legacy: C1("It is essential that every participant ______ informed of the revised procedure.") }),
  d.rewrite({ b: "cleft", t: "what-cleft", L: "C1", diff: 2, focus: "What-cleft to focus the object", pre: ["cleft-what"],
    instr: "Rewrite the sentence to emphasise what is needed, starting with the words given.", source: "We need more time, not more money.", hint: "What ______.", key: "we need is more time, not more money", why: "What + clause + is + focus." }),
  d.rewrite({ b: "cleft", t: "it-cleft", L: "C1", diff: 2, focus: "It-cleft focusing an adverbial", pre: ["cleft-it"],
    instr: "Rewrite the sentence to emphasise WHEN, starting with the words given.", source: "The problems started after the merger.", hint: "It was ______.", key: "after the merger that the problems started", why: "It + be + focus + that-clause." }),
  d.gap({ b: "subjunctive", t: "mandative-verb", L: "C1", diff: 2, focus: "Mandative subjunctive after recommend/insist (no -s)", pre: ["mandative-subjunctive", "verb-that-clause"],
    source: "The committee insisted that the chairman ______ (resign) immediately.", key: "resign", alt: ["should resign"], why: "Mandative → base form (or should + base)." }),
  d.rewrite({ b: "emphasis-inversion", t: "so-adj-inversion", L: "C1", diff: 3, focus: "Fronted 'So + adjective' with inversion", pre: ["negative-adverbial-inversion", "result-clauses"],
    source: "The lecture was so boring that several students fell asleep.", hint: "So ______ that several students fell asleep.", key: "boring was the lecture", why: "So + adj + be + subject." }),
  d.guided({ b: "subjunctive", t: "mandative-be", L: "C1", diff: 2, focus: "Productive mandative subjunctive", pre: ["mandative-subjunctive"],
    prompt: "Write a formal or academic sentence using the mandative subjunctive, for example after 'It is essential that...'", required: "the mandative subjunctive (base form, no -s or tense marking) correctly used after an expression like \"It is essential that...\"",
    legacy: C1O("Write a formal or academic sentence using the mandative subjunctive, for example after 'It is essential that...'") }),
  d.guided({ b: "emphasis-inversion", t: "only-after-inversion", L: "C1", diff: 3, focus: "Productive Only after inversion", pre: ["negative-adverbial-inversion"],
    prompt: "Rewrite a sentence beginning with 'Only after...' and use subject-auxiliary inversion.", required: "correct subject-auxiliary inversion after a fronted \"Only after...\"",
    legacy: C1O("Rewrite a sentence beginning with 'Only after...' and use subject-auxiliary inversion.") }),

  // ---------------- C2 ----------------
  d.rewrite({ b: "emphasis-inversion", t: "barely-when", L: "C2", diff: 1, focus: "Inversion with barely/hardly/scarcely ... when", pre: ["negative-adverbial-inversion", "past-perfect"],
    instr: "Rewrite the sentence beginning with the word given.", source: "She had barely sat down when the phone rang.", hint: "Barely ______.", key: "had she sat down when the phone rang", why: "Fronted 'Barely' → had + subject + pp ... when.",
    flags: ["c2-check: literary inversion with correlative 'when'; grammatical, not lexical. C2 provisional (upper C1 possible)."] }),
  d.mcq({ b: "word-order", t: "fronting-complement", L: "C2", diff: 3, focus: "Fronted complement with be-inversion for discourse linking ('Equally important is ...')", pre: ["fronting", "be-copula"],
    prompt: "Cost is one consideration. ______ the environmental impact.", options: ["Equally important is", "Equally important it is", "Is equally important", "Equally it is important"], key: 0, why: "Fronted adjective phrase + be + subject.",
    flags: ["c2-check: complement fronting with copular inversion is a discourse-level syntactic device. C2 provisional."] }),
  d.gap({ b: "clause-linkers", t: "ellipsis-reduced-adverbial", L: "C2", diff: 3, focus: "Reduced adverbial clause with 'if/when/though + past participle'", pre: ["ellipsis-substitution", "participle-clauses"],
    instr: "Complete the reduced clause with ONE word (a past participle).", source: "The device, though ______ (design) for hospitals, is now widely used in homes.", key: "designed", why: "though (it was) designed → though designed.",
    flags: ["c2-check: subject + auxiliary ellipsis after a subordinator. C2 provisional."] }),
];