import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("sentence-structure");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), C1 = leg("C1_MCQ");
const B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR"), C1O = leg("C1_OPEN_GRAMMAR");

// Owns (per rulings §5/§6): relative clauses, there is/are, imperatives,
// be-as-predication, negative inversion, cleft, participle clauses, linkers.

export default [
  // ---------------- A1 ----------------
  d.mcq({ b: "predication", t: "be-agreement", L: "A1", diff: 1, focus: "am with the first-person subject in a predication", pre: ["be-copula"],
    prompt: "I ______ a student.", options: ["am", "is", "are", "be"], key: 0, why: "I → am.", legacy: A1("I ______ a student.") }),
  d.mcq({ b: "predication", t: "be-agreement", L: "A1", diff: 1, focus: "is with a third-person singular subject", pre: ["be-copula"],
    prompt: "She ______ my sister.", options: ["am", "are", "is", "be"], key: 2, why: "She → is.", legacy: A1("She ______ my sister.") }),
  d.mcq({ b: "predication", t: "be-agreement-plural", L: "A1", diff: 1, focus: "are with a plural subject", pre: ["be-copula", "subject-verb-agreement"],
    prompt: "My parents ______ teachers.", options: ["are", "is", "am", "be"], key: 0, why: "Plural → are.", legacy: A1("My parents ______ teachers.") }),
  d.mcq({ b: "predication", t: "be-question", L: "A1", diff: 2, focus: "Inverted be in a yes/no question", pre: ["be-copula", "subject-auxiliary-inversion"],
    prompt: "______ you tired?", options: ["Is", "Are", "Am", "Be"], key: 1, why: "you → Are.", legacy: A1("______ you tired?"), overlaps: ["questions-negation"] }),
  d.mcq({ b: "predication", t: "compound-subject-agreement", L: "A1", diff: 2, focus: "Compound subject with 'and' takes a plural verb", pre: ["be-copula", "subject-verb-agreement"],
    prompt: "My brother and I ______ students.", options: ["am", "is", "are", "be"], key: 2, why: "Two people → are.", legacy: A1("My brother and I ______ students.") }),
  d.mcq({ b: "existential", t: "there-is-singular", L: "A1", diff: 1, focus: "There is + singular noun", pre: ["there-existential"],
    prompt: "______ a book on the desk.", options: ["There are", "There is", "They are", "It are"], key: 1, why: "Singular → There is.", legacy: A1("______ a book on the desk.") }),
  d.mcq({ b: "existential", t: "there-are-plural", L: "A1", diff: 1, focus: "There are + plural noun", pre: ["there-existential", "subject-verb-agreement"],
    prompt: "______ two chairs in the room.", options: ["There is", "There are", "It is", "They is"], key: 1, why: "Plural → There are.", legacy: A1("______ two chairs in the room.") }),
  d.mcq({ b: "existential", t: "there-question", L: "A1", diff: 2, focus: "Inverted existential question form", pre: ["there-existential", "subject-auxiliary-inversion"],
    prompt: "______ any milk in the fridge?", options: ["Is there", "Are there", "There is", "There are"], key: 0, why: "Uncountable 'milk' → Is there.", legacy: A1("______ any milk in the fridge?") }),
  d.mcq({ b: "imperatives", t: "affirmative-imperative", L: "A1", diff: 1, focus: "Base form for an affirmative imperative", pre: ["imperatives"],
    prompt: "______ the door, please.", options: ["Opens", "Opening", "Open", "To open"], key: 2, why: "Imperative → base form.", legacy: A1("______ the door, please.") }),
  d.mcq({ b: "imperatives", t: "negative-imperative", L: "A1", diff: 2, focus: "Don't + base form for a negative imperative", pre: ["imperatives"],
    prompt: "______ touch that. It is hot.", options: ["Don't", "Doesn't", "Not", "No"], key: 0, why: "Negative imperative → Don't.", legacy: A1("______ touch that. It is hot.") }),
  d.mcq({ b: "conjunctions", t: "and", L: "A1", diff: 1, focus: "and to add", pre: ["coordinating-conjunctions"],
    prompt: "I like tea ______ coffee.", options: ["but", "and", "because", "or"], key: 1, why: "Addition → and.", legacy: A1("I like tea ______ coffee.") }),
  d.mcq({ b: "conjunctions", t: "so", L: "A1", diff: 2, focus: "so for a result", pre: ["coordinating-conjunctions"],
    prompt: "I am tired, ______ I am going to bed.", options: ["so", "but", "because", "or"], key: 0, why: "Result → so.", legacy: A1("I am tired, ______ I am going to bed.") }),
  d.mcq({ b: "conjunctions", t: "but", L: "A1", diff: 2, focus: "but for contrast", pre: ["coordinating-conjunctions"],
    prompt: "She is young ______ she is very responsible.", options: ["and", "because", "but", "so"], key: 2, why: "Contrast → but.", legacy: A1("She is young ______ she is very responsible.") }),
  d.order({ b: "word-order", t: "svo", L: "A1", diff: 1, focus: "Basic subject-verb-object order", pre: ["svo-order"],
    tokens: ["a", "letter", "wrote", "he"], key: ["he", "wrote", "a", "letter"], why: "S + V + O." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "conjunctions", t: "because", L: "A2", diff: 1, focus: "because introducing a reason clause", pre: ["subordinating-conjunctions"],
    prompt: "I stayed at home ______ I was feeling sick.", options: ["but", "because", "so", "although"], key: 1, why: "Reason → because.", legacy: A2("I stayed at home ______ I was feeling sick.") }),
  d.mcq({ b: "relative-clauses", t: "who-person", L: "A2", diff: 1, focus: "who for a person in a defining relative clause", pre: ["relative-pronouns", "defining-relative"],
    prompt: "The woman ______ lives next door is a teacher.", options: ["which", "who", "where", "whose"], key: 1, why: "Person → who.", legacy: A2("The woman ______ lives next door is a teacher.") }),
  d.mcq({ b: "relative-clauses", t: "that-thing", L: "A2", diff: 1, focus: "that for a thing in a defining relative clause", pre: ["relative-pronouns", "defining-relative"],
    prompt: "This is the book ______ I told you about.", options: ["who", "where", "that", "whose"], key: 2, why: "Thing → that.", legacy: A2("This is the book ______ I told you about.") }),
  d.mcq({ b: "relative-clauses", t: "where-place", L: "A2", diff: 2, focus: "where for a place", pre: ["relative-pronouns", "defining-relative"],
    prompt: "That is the restaurant ______ we had dinner.", options: ["who", "where", "which", "whose"], key: 1, why: "Place → where.", legacy: A2("That is the restaurant ______ we had dinner.") }),
  d.gap({ b: "existential", t: "there-agreement", L: "A2", diff: 2, focus: "Existential agreement with countable and uncountable nouns", pre: ["there-existential", "subject-verb-agreement"],
    instr: "Complete each gap with is or are.", source: "There ______ some bread on the table and there ______ two apples in the bowl.", key: ["is", "are"], why: "Uncountable → is; plural → are." }),
  d.order({ b: "word-order", t: "indirect-object", L: "A2", diff: 2, focus: "Verb + indirect object + direct object order", pre: ["svo-order"],
    tokens: ["me", "a", "she", "present", "gave"], key: ["she", "gave", "me", "a", "present"], why: "V + IO + DO without 'to'." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "relative-clauses", t: "who-vs-which", L: "B1", diff: 1, focus: "who (person) rather than which/where", pre: ["relative-pronouns", "defining-relative"],
    prompt: "The woman ______ lives next door is a doctor.", options: ["which", "where", "who", "whose"], key: 2, why: "Person subject → who.", legacy: B1("The woman ______ lives next door is a doctor.") }),
  d.mcq({ b: "relative-clauses", t: "where-place", L: "B1", diff: 1, focus: "where for a place in a defining clause", pre: ["defining-relative"],
    prompt: "This is the restaurant ______ we had dinner last night.", options: ["who", "where", "whose", "what"], key: 1, why: "Place → where.", legacy: B1("This is the restaurant ______ we had dinner last night.") }),
  d.mcq({ b: "relative-clauses", t: "omissible-object-pronoun", L: "B1", diff: 3, focus: "An object relative pronoun may be omitted — a subject one may not", pre: ["defining-relative", "relative-pronouns"],
    prompt: "Which option is NOT possible in 'The book ______ I bought yesterday is excellent.'?",
    options: ["that", "which", "no relative pronoun", "who"], key: 3, why: "'who' cannot refer to a book; 'that', 'which' and omission are all possible because the pronoun is the object.",
    legacy: B1("The book ______ I bought yesterday is excellent.", "The legacy item keyed 'no relative pronoun is necessary' as the single correct answer, but 'that' and 'which' are equally correct, so it had multiple valid keys. Recast as a 'which option is NOT possible' item, which tests the same omission knowledge with one defensible answer.") }),
  d.mcq({ b: "relative-clauses", t: "whose-possession", L: "B1", diff: 2, focus: "whose for possession in a relative clause", pre: ["relative-pronouns"],
    prompt: "That's the student ______ project won the prize.", options: ["who", "whose", "who's", "which"], key: 1, why: "Possession → whose." }),
  d.mcq({ b: "clause-linkers", t: "although", L: "B1", diff: 2, focus: "although + clause for concession", pre: ["subordinating-conjunctions", "concession-linkers"],
    prompt: "______ it was raining heavily, they continued the match.", options: ["Despite", "Although", "However", "In spite"], key: 1, why: "Full clause → although." }),
  d.gap({ b: "clause-linkers", t: "so-that-purpose", L: "B1", diff: 2, focus: "so that + clause for purpose", pre: ["purpose-clauses"],
    instr: "Complete the gap with TWO words.", source: "She wrote the address down ______ she wouldn't forget it.", key: "so that", why: "Purpose clause → so that." }),
  d.order({ b: "relative-clauses", t: "defining-relative", L: "B1", diff: 2, focus: "Relative clause placed immediately after its noun", pre: ["defining-relative"],
    tokens: ["I", "the", "who", "man", "met", "yesterday", "teacher", "a", "is"], key: ["the", "man", "who", "I", "met", "yesterday", "is", "a", "teacher"], why: "Relative clause follows the head noun." }),
  d.guided({ b: "relative-clauses", t: "defining-relative", L: "B1", diff: 2, focus: "Productive defining relative clause", pre: ["defining-relative"],
    prompt: "Write one sentence containing a defining relative clause with who, which, that, or where.", required: "a defining relative clause using who/which/that/where correctly",
    legacy: B1O("Write one sentence containing a defining relative clause with who, which, that, or where.") }),
  d.guided({ b: "relative-clauses", t: "whose-possession", L: "B1", diff: 2, focus: "Productive whose-clause", pre: ["relative-pronouns"],
    prompt: "Write one sentence using whose in a relative clause.", required: "a relative clause using whose to show possession",
    legacy: B1O("Write one sentence using whose in a relative clause.") }),

  // ---------------- B2 ----------------
  d.mcq({ b: "relative-clauses", t: "non-defining-whose", L: "B2", diff: 2, focus: "whose in a non-defining relative clause", pre: ["non-defining-relative", "relative-pronouns"],
    prompt: "The researcher, ______ work has influenced the field, received an award.", options: ["who", "whom", "whose", "which"], key: 2, why: "Possession → whose.", legacy: B2("The researcher, ______ work has influenced the field, received an award.") }),
  d.mcq({ b: "relative-clauses", t: "reduced-relative-past", L: "B2", diff: 2, focus: "Reduced relative clause with a past participle", pre: ["reduced-relative", "participle-clauses"],
    prompt: "The documents ______ yesterday need to be signed.", options: ["sending", "sent", "were sent", "which sent"], key: 1, why: "Passive reduced relative → past participle.", legacy: B2("The documents ______ yesterday need to be signed.") }),
  d.mcq({ b: "participle-clauses", t: "having-participle", L: "B2", diff: 3, focus: "Having + past participle for a prior action", pre: ["participle-clauses"],
    prompt: "______ the report, she left the office.", options: ["Having finished", "Finished", "To finish", "Has finished"], key: 0, why: "Earlier action → Having + pp.", legacy: B2("______ the report, she left the office.") }),
  d.mcq({ b: "participle-clauses", t: "past-participle-clause", L: "B2", diff: 3, focus: "Past participle clause with a passive meaning", pre: ["participle-clauses"],
    prompt: "______ by thousands of tourists every year, the city has developed a large tourism industry.", options: ["Visiting", "Visited", "Having visit", "To visiting"], key: 1, why: "Passive meaning → past participle.", legacy: B2("______ by thousands of tourists every year, the city has developed a large tourism industry.") }),
  d.mcq({ b: "emphasis-inversion", t: "never-inversion", L: "B2", diff: 3, focus: "Subject-auxiliary inversion after a fronted negative adverbial", pre: ["negative-adverbial-inversion", "subject-auxiliary-inversion"],
    prompt: "Never ______ such a difficult exam.", options: ["I have taken", "have I taken", "I took", "did I have taken"], key: 1, why: "Fronted 'Never' → inversion.", legacy: B2("Never ______ such a difficult exam.") }),
  d.mcq({ b: "emphasis-inversion", t: "not-only-inversion", L: "B2", diff: 3, focus: "Inversion after fronted 'Not only'", pre: ["negative-adverbial-inversion"],
    prompt: "Not only ______ late, but he also forgot the documents.", options: ["he arrived", "did he arrive", "he did arrive", "arrived he"], key: 1, why: "Fronted 'Not only' → did + subject + base.", legacy: B2("Not only ______ late, but he also forgot the documents.") }),
  d.mcq({ b: "cleft", t: "what-cleft", L: "B2", diff: 2, focus: "What-cleft for emphasis", pre: ["cleft-what"],
    prompt: "______ I need is a little more time.", options: ["That", "What", "Which", "It"], key: 1, why: "Cleft subject → What.", legacy: B2("______ I need is a little more time.") }),
  d.mcq({ b: "clause-linkers", t: "despite-noun", L: "B2", diff: 2, focus: "despite + noun/-ing (not a clause)", pre: ["concession-linkers"],
    prompt: "______ being exhausted, she continued working.", options: ["Although", "Despite", "However", "Even"], key: 1, why: "-ing form → Despite.", legacy: B2("______ being exhausted, she continued working.") }),
  d.rewrite({ b: "relative-clauses", t: "reduced-relative-past", L: "B2", diff: 2, focus: "Reducing a relative clause to a participle phrase", pre: ["reduced-relative"],
    instr: "Rewrite the sentence by reducing the relative clause. Write the whole sentence.", source: "The man who was standing near the exit looked nervous.",
    key: "The man standing near the exit looked nervous.", why: "who was + -ing → -ing." }),
  d.guided({ b: "emphasis-inversion", t: "not-only-inversion", L: "B2", diff: 3, focus: "Productive negative inversion", pre: ["negative-adverbial-inversion"],
    prompt: "Write a sentence beginning with Not only and use subject-auxiliary inversion.", required: "correct subject-auxiliary inversion after a fronted 'Not only'",
    legacy: B2O("Write a sentence beginning with Not only and use subject-auxiliary inversion.") }),
  d.guided({ b: "cleft", t: "what-cleft", L: "B2", diff: 2, focus: "Productive what-cleft", pre: ["cleft-what"],
    prompt: "Write a cleft sentence beginning with What... to emphasize what you need, want, or like.", required: "a cleft sentence beginning with 'What...' correctly emphasizing the intended element",
    legacy: B2O("Write a cleft sentence beginning with What... to emphasize what you need, want, or like.") }),
  d.guided({ b: "participle-clauses", t: "having-participle", L: "B2", diff: 3, focus: "Productive perfect participle clause", pre: ["participle-clauses"],
    prompt: "Write a sentence beginning with Having + past participle to show that one action happened before another.", required: "a participle clause beginning with Having + past participle, showing correct sequencing",
    legacy: B2O("Write a sentence beginning with Having + past participle to show that one action happened before another.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "participle-clauses", t: "present-participle-simultaneous", L: "C1", diff: 2, focus: "-ing participle clause for a simultaneous/attendant action", pre: ["participle-clauses"],
    prompt: "______ the limitations of the sample, the authors avoided making broad conclusions.", options: ["Acknowledging", "Having acknowledged", "Acknowledged", "To acknowledge"], key: 0, why: "Same-time action → -ing participle.", legacy: C1("______ the limitations of the sample, the authors avoided making broad conclusions.") }),
  d.mcq({ b: "participle-clauses", t: "having-participle", L: "C1", diff: 2, focus: "Perfect participle clause for a completed prior action", pre: ["participle-clauses"],
    prompt: "______ the analysis, the researchers submitted the report to the committee.", options: ["Having completed", "Completing had", "Completed having", "To have completing"], key: 0, why: "Prior completed action → Having + pp.", legacy: C1("______ the analysis, the researchers submitted the report to the committee.") }),
  d.mcq({ b: "relative-clauses", t: "reduced-relative-past", L: "C1", diff: 2, focus: "Past participle reduced relative in formal writing", pre: ["reduced-relative"],
    prompt: "The measures ______ to reduce energy consumption were implemented across all departments.", options: ["designed", "designing", "were designing", "which designing"], key: 0, why: "Passive reduced relative → designed.", legacy: C1("The measures ______ to reduce energy consumption were implemented across all departments.") }),
  d.mcq({ b: "emphasis-inversion", t: "only-after-inversion", L: "C1", diff: 3, focus: "Inversion after a fronted 'Only after' adverbial clause", pre: ["negative-adverbial-inversion"],
    prompt: "Only after the results had been independently replicated ______ the hypothesis.", options: ["the researchers accepted", "did the researchers accept", "the researchers had accepted", "had the researchers accept"], key: 1, why: "Restrictive fronted adverbial → inversion in the main clause.",
    legacy: C1("Only after the results had been independently replicated ______ the researchers accept the hypothesis.", "The legacy stem placed 'the researchers accept' after the gap while the keyed option also contained the subject, producing 'did the researchers the researchers accept'. Stem shortened and options rebuilt as full verb phrases.") }),
  d.mcq({ b: "emphasis-inversion", t: "under-no-circumstances", L: "C1", diff: 3, focus: "Inversion after 'Under no circumstances'", pre: ["negative-adverbial-inversion"],
    prompt: "Under no circumstances ______ released before the investigation is complete.", options: ["should the data be", "the data should be", "should be the data", "the data be should"], key: 0, why: "Negative adverbial → modal + subject + base.",
    legacy: C1("Under no circumstances ______ the data be released before the investigation is complete.", "The legacy stem already contained 'the data be', so the keyed option 'should' was the only workable choice and the distractors were unusable. The gap now spans the whole inverted sequence.") }),
  d.mcq({ b: "emphasis-inversion", t: "not-only-inversion", L: "C1", diff: 2, focus: "Inversion after 'Not only' in academic register", pre: ["negative-adverbial-inversion"],
    prompt: "Not only ______ the initial assumption, but it also revealed a previously unknown variable.", options: ["the study challenged", "did the study challenge", "challenged the study", "the study did challenge"], key: 1, why: "Fronted 'Not only' → did + subject + base.", legacy: C1("Not only ______ the initial assumption, but it also revealed a previously unknown variable.") }),
  d.mcq({ b: "subjunctive", t: "mandative-subjunctive", L: "C1", diff: 3, focus: "Mandative subjunctive: base form after 'It is essential that'", pre: ["mandative-subjunctive"],
    prompt: "It is essential that every participant ______ informed of the revised procedure.", options: ["is", "be", "will be", "has been"], key: 1, why: "Mandative subjunctive → base form 'be'.", legacy: C1("It is essential that every participant ______ informed of the revised procedure.") }),
  d.mcq({ b: "relative-clauses", t: "preposition-which-formal", L: "C1", diff: 2, focus: "'the extent to which' — preposition + which in a formal noun phrase", pre: ["relative-pronouns", "preposition-stranding"],
    prompt: "The extent to ______ these findings apply to other populations remains uncertain.", options: ["which", "that", "what", "whom"], key: 0, why: "Preposition + which; 'that' cannot follow a preposition.", legacy: C1("The extent to ______ these findings apply to other populations remains uncertain."), overlaps: ["prep-phrasal"] }),
  d.rewrite({ b: "emphasis-inversion", t: "only-after-inversion", L: "C1", diff: 3, focus: "Producing inversion after a fronted restrictive adverbial", pre: ["negative-adverbial-inversion"],
    instr: "Rewrite the sentence beginning with the words given.", source: "She only realised the mistake after she had sent the email.", hint: "Only after she had sent the email ______",
    key: "did she realise the mistake", why: "Fronted 'Only after' clause → auxiliary + subject + base." }),
  d.rewrite({ b: "cleft", t: "it-cleft", L: "C1", diff: 2, focus: "It-cleft to focus one element of a clause", pre: ["cleft-it"],
    instr: "Rewrite the sentence beginning with the words given so that 'the manager' is emphasised.", source: "The manager approved the change, not the director.", hint: "It ______",
    key: "was the manager who approved the change, not the director", why: "It + be + focus + who/that clause." }),
  d.guided({ b: "subjunctive", t: "mandative-subjunctive", L: "C1", diff: 3, focus: "Productive mandative subjunctive", pre: ["mandative-subjunctive"],
    prompt: "Write a formal or academic sentence using the mandative subjunctive, for example after 'It is essential that...'", required: "the mandative subjunctive (base form, no -s or tense marking) correctly used after an expression like \"It is essential that...\"",
    legacy: C1O("Write a formal or academic sentence using the mandative subjunctive, for example after 'It is essential that...'") }),
  d.guided({ b: "relative-clauses", t: "reduced-relative-past", L: "C1", diff: 2, focus: "Productive reduction of a relative clause to a participle phrase", pre: ["reduced-relative"],
    prompt: "Reduce a relative clause to a participle phrase without changing the meaning. Write one sentence containing the reduced clause.", required: "a relative clause correctly reduced to a participle phrase with the meaning preserved",
    legacy: C1O("Reduce a relative clause to a participle phrase without changing the meaning.") }),

  // ---------------- C2 ----------------
  d.mcq({ b: "emphasis-inversion", t: "so-such-inversion", L: "C2", diff: 3, focus: "Inversion after a fronted 'So + adjective' result construction", pre: ["negative-adverbial-inversion", "result-clauses"],
    prompt: "So convincing ______ that the committee approved it without further discussion.", options: ["was her argument", "her argument was", "was she argued", "her argument had"], key: 0, why: "Fronted 'So + adjective' forces inversion of be and subject.",
    flags: ["c2-check: 'So + adj + be + subject + that' is a distinct inversion trigger from negative adverbials and is not vocabulary-driven. C2 provisional."] }),
  d.mcq({ b: "participle-clauses", t: "absolute-participle", L: "C2", diff: 3, focus: "Absolute (nominative) participle clause with its own subject", pre: ["participle-clauses"],
    prompt: "______, the committee moved on to the final item on the agenda.", options: ["The main objections having been withdrawn", "Having withdrawn the main objections", "The main objections were withdrawn", "Withdrawing the main objections"], key: 0, why: "An absolute participle clause carries its own subject, distinct from the main clause subject.",
    flags: ["c2-check: absolute participle clauses (own subject, no conjunction) are structurally distinct from the B2/C1 participle clauses whose subject must match the main clause. C2 provisional."] }),
  d.rewrite({ b: "subjunctive", t: "were-subjunctive-formal", L: "C2", diff: 3, focus: "Formal 'were it not for' as a fossilised subjunctive inversion", pre: ["mandative-subjunctive", "inverted-conditional"],
    instr: "Rewrite the sentence beginning with the words given, keeping the meaning.", source: "If it weren't for her support, the project would have collapsed.", hint: "Were ______",
    key: "it not for her support, the project would have collapsed", why: "Fossilised subjunctive inversion 'Were it not for'.", overlaps: ["conditionals-wishes"],
    flags: ["c2-check: 'Were it not for' combines subjunctive 'were' with inversion and negative placement — grammatical, not lexical. C2 provisional."] }),
];