import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("tenses");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), C1 = leg("C1_MCQ");
const B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR"), C1O = leg("C1_OPEN_GRAMMAR");

export default [
  // ---------------- A1 ----------------
  d.mcq({ b: "present", t: "simple-routine", L: "A1", diff: 1, focus: "Present simple base form for a routine with a first-person subject", pre: ["present-simple"],
    prompt: "I ______ coffee every morning.", options: ["drink", "drinks", "am drinking", "drinking"], key: 0, why: "'every morning' = routine; I + base form.", legacy: A1("I ______ coffee every morning.") }),
  d.mcq({ b: "present", t: "third-person-s", L: "A1", diff: 1, focus: "Third-person -s in present simple", pre: ["present-simple", "third-person-s"],
    prompt: "She ______ to school by bus.", options: ["go", "going", "goes", "is go"], key: 2, why: "She → goes.", legacy: A1("She ______ to school by bus.") }),
  d.mcq({ b: "present", t: "third-person-s", L: "A1", diff: 2, focus: "Present simple for a scheduled routine, third person", pre: ["present-simple", "third-person-s"],
    prompt: "The shop ______ at 9 a.m. every day.", options: ["open", "opens", "opening", "is open"], key: 1, why: "'every day' → present simple; the shop → opens.", legacy: A1("The shop ______ at 9 a.m. every day.") }),
  d.mcq({ b: "present", t: "simple-negative", L: "A1", diff: 2, focus: "doesn't + base form (no double -s) in the present simple negative", pre: ["present-simple", "auxiliary-do"],
    prompt: "He ______ meat.", options: ["don't eat", "doesn't eats", "doesn't eat", "not eat"], key: 2, why: "Third person → doesn't; main verb stays base.", legacy: A1("He ______ meat.") }),
  d.mcq({ b: "present", t: "continuous-now", L: "A1", diff: 1, focus: "Present continuous for an action visible right now", pre: ["be-auxiliary", "present-continuous"],
    prompt: "Look! The baby ______.", options: ["sleeps", "is sleeping", "sleep", "sleeping"], key: 1, why: "'Look!' → action in progress → is sleeping.", legacy: A1("Look! The baby ______.") }),
  d.mcq({ b: "present", t: "continuous-now", L: "A1", diff: 1, focus: "am + -ing with 'right now'", pre: ["be-auxiliary", "present-continuous"],
    prompt: "I ______ dinner right now.", options: ["cook", "cooks", "am cooking", "cooking"], key: 2, why: "'right now' → present continuous.", legacy: A1("I ______ dinner right now.") }),
  d.mcq({ b: "present", t: "continuous-negative", L: "A1", diff: 2, focus: "Negative of the progressive auxiliary: aren't (not don't) before -ing", pre: ["be-auxiliary", "present-continuous"],
    prompt: "We ______ studying today.", options: ["isn't", "aren't", "don't", "not"], key: 1, why: "-ing needs be; we → aren't.", legacy: A1("We ______ studying today.") }),
  d.gap({ b: "present", t: "third-person-s", L: "A1", diff: 1, focus: "Producing the third-person -s form", pre: ["present-simple", "third-person-s"],
    source: "My mother ______ (work) in a hospital.", key: "works", why: "Third-person singular present simple." }),
  d.order({ b: "present", t: "simple-routine", L: "A1", diff: 2, focus: "Subject + verb + object + frequency phrase order in a present simple statement", pre: ["present-simple", "svo-order"],
    tokens: ["every", "day", "she", "English", "studies"], key: ["she", "studies", "English", "every", "day"], why: "S + V + O + time." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "present", t: "stative-verbs", L: "A2", diff: 2, focus: "Stative verb (like) takes present simple even for a present situation", pre: ["present-simple", "stative-verbs"],
    prompt: "I ______ this restaurant. The food is excellent.", options: ["am liking", "like", "likes", "have liked"], key: 1, why: "'like' is a state verb — no continuous.", legacy: A2("I ______ this restaurant. The food is excellent.") }),
  d.mcq({ b: "present", t: "general-truth", L: "A2", diff: 1, focus: "Present simple for a scientific/general truth", pre: ["present-simple"],
    prompt: "Water ______ at 100°C.", options: ["boils", "is boiling", "boil", "has boiled"], key: 0, why: "Permanent fact → present simple.", legacy: A2("Water ______ at 100°C.") }),
  d.mcq({ b: "present", t: "temporary-situation", L: "A2", diff: 2, focus: "Present continuous for a temporary situation around now (not at this second)", pre: ["present-continuous", "time-adverbials"],
    prompt: "I ______ with my parents this month because my apartment is being repaired.", options: ["stay", "am staying", "have stayed", "stays"], key: 1, why: "'this month' + temporary → continuous.", legacy: A2("I ______ with my parents this month because my apartment is being repaired.") }),
  d.gap({ b: "present", t: "simple-vs-continuous", L: "A2", diff: 2, focus: "Routine (present simple) vs temporary change (present continuous) in one context", pre: ["present-simple", "present-continuous", "time-adverbials"],
    source: "I usually ______ (walk) to work, but this week I ______ (take) the bus because my leg hurts.", key: ["walk", "am taking"], alt: [["walk", "'m taking"]], why: "'usually' → simple; 'this week ... because' → continuous." }),
  d.mcq({ b: "past", t: "simple-finished-time", L: "A2", diff: 1, focus: "Past simple with a finished-time marker", pre: ["past-simple", "time-adverbials"],
    prompt: "We ______ to the cinema last night.", options: ["go", "went", "have gone", "are going"], key: 1, why: "'last night' → past simple.", legacy: A2("We ______ to the cinema last night.") }),
  d.mcq({ b: "past", t: "simple-negative", L: "A2", diff: 2, focus: "did + not + base form for the past simple negative", pre: ["past-simple", "auxiliary-do"],
    prompt: "They ______ not understand the question.", options: ["did", "were", "have", "do"], key: 0, why: "Past negative of a main verb → did not.", legacy: A2("They ______ not understand the question.") }),
  d.gap({ b: "past", t: "irregular-past", L: "A2", diff: 1, focus: "Producing an irregular past simple form", pre: ["past-simple"],
    source: "Yesterday I ______ (buy) a new phone.", key: "bought", why: "buy → bought." }),
  d.mcq({ b: "past", t: "continuous-at-time", L: "A2", diff: 2, focus: "Past continuous for an action in progress at a specific past time", pre: ["past-continuous", "be-auxiliary"],
    prompt: "At 9 last night, I ______ TV.", options: ["watched", "was watching", "have watched", "watch"], key: 1, why: "'At 9 last night' = point inside an activity.", legacy: A2("At 9 last night, I ______ TV.") }),
  d.mcq({ b: "past", t: "interrupted-action", L: "A2", diff: 2, focus: "Past continuous (background) interrupted by past simple", pre: ["past-continuous", "past-simple"],
    prompt: "While I ______ dinner, my phone rang.", options: ["cooked", "was cooking", "have cooked", "cook"], key: 1, why: "'While' + ongoing action → was cooking.", legacy: A2("While I ______ dinner, my phone rang.") }),
  d.mcq({ b: "perfect", t: "present-result", L: "A2", diff: 2, focus: "Present perfect for a completed action with a present result", pre: ["present-perfect", "past-participle"],
    prompt: "I ______ my homework, so I can go out now.", options: ["finished", "have finished", "am finishing", "finish"], key: 1, why: "Result 'now' → present perfect.", legacy: A2("I ______ my homework, so I can go out now.") }),
  d.mcq({ b: "perfect", t: "since-duration", L: "A2", diff: 2, focus: "Present perfect with 'since' for an unfinished period", pre: ["present-perfect", "time-adverbials"],
    prompt: "We ______ here since 2022.", options: ["live", "lived", "have lived", "are living"], key: 2, why: "'since' + unfinished → present perfect.", legacy: A2("We ______ here since 2022.") }),
  d.mcq({ b: "perfect", t: "for-since", L: "A2", diff: 1, focus: "since (start point) vs for (length)", pre: ["time-adverbials"],
    prompt: "I haven't seen Maria ______ Monday.", options: ["for", "since", "from", "during"], key: 1, why: "'Monday' is a start point → since.", legacy: A2("I haven't seen Maria ______ Monday.") }),
  d.mcq({ b: "perfect", t: "for-since", L: "A2", diff: 1, focus: "for with a length of time", pre: ["time-adverbials"],
    prompt: "They have lived here ______ five years.", options: ["since", "from", "for", "during"], key: 2, why: "'five years' is a length → for.", legacy: A2("They have lived here ______ five years.") }),
  d.gap({ b: "perfect", t: "experience-ever", L: "A2", diff: 2, focus: "Present perfect question form for life experience (Have ... ever been)", pre: ["present-perfect", "past-participle", "subject-auxiliary-inversion"],
    source: "______ you ever ______ (be) to Italy?", key: ["Have", "been"], why: "Experience question → Have + subject + ever + past participle.",
    legacy: A2("______ you ever ______ to Italy?", "Converted from a two-gap MCQ whose options were paired strings ('Have / been') into a two-gap fill so each gap is produced separately.") }),
  d.gap({ b: "perfect", t: "never-experience", L: "A2", diff: 2, focus: "Past participle after has never", pre: ["present-perfect", "past-participle"],
    source: "She has never ______ (eat) sushi before.", key: "eaten", why: "Present perfect → past participle 'eaten'.",
    legacy: A2("She ______ never ______ sushi before.", "Two-gap MCQ with paired options rewritten as a single-gap fill; the auxiliary is supplied so the item isolates the participle.") }),
  d.mcq({ b: "future", t: "going-to-evidence", L: "A2", diff: 2, focus: "be going to for a prediction based on present evidence", pre: ["future-going-to"],
    prompt: "Look at those dark clouds. It ______ rain.", options: ["is going to", "will", "does", "has"], key: 0, why: "Visible evidence → going to.", legacy: A2("Look at those dark clouds. It ______ rain.") }),
  d.mcq({ b: "future", t: "going-to-plan", L: "A2", diff: 2, focus: "be going to for a pre-made plan", pre: ["future-going-to"],
    prompt: "We ______ visit our grandparents this weekend. We have already made plans.", options: ["are going to", "will", "did", "have"], key: 0, why: "Plan already made → going to.", legacy: A2("We ______ visit our grandparents this weekend. We have already made plans.") }),
  d.mcq({ b: "future", t: "will-spontaneous", L: "A2", diff: 2, focus: "will for a spontaneous decision at the moment of speaking", pre: ["future-will"],
    prompt: "The phone is ringing. I ______ answer it.", options: ["am going to", "will", "did", "have"], key: 1, why: "Decision made now → will.", legacy: A2("The phone is ringing. I ______ answer it.") }),

  // ---------------- B1 ----------------
  d.mcq({ b: "perfect", t: "unfinished-time", L: "B1", diff: 2, focus: "Present perfect with an unfinished time period ('this morning' while still morning)", pre: ["present-perfect", "time-adverbials"],
    prompt: "I ______ three emails this morning, but I haven't finished yet.", options: ["sent", "have sent", "was sending", "had sent"], key: 1, why: "Period still open → present perfect.", legacy: B1("I ______ three emails this morning, but I haven't finished yet.") }),
  d.mcq({ b: "perfect", t: "since-clause", L: "B1", diff: 1, focus: "Present perfect in the main clause with a since-clause in past simple", pre: ["present-perfect", "past-simple"],
    prompt: "She ______ here since she finished university.", options: ["works", "worked", "has worked", "is working"], key: 2, why: "Unfinished period → has worked.", legacy: B1("She ______ here since she finished university.") }),
  d.mcq({ b: "perfect", t: "continuous-present-result", L: "B1", diff: 2, focus: "Present perfect continuous for a recent activity explaining a present state", pre: ["present-perfect-continuous"],
    prompt: "He is exhausted because he ______ all afternoon.", options: ["has studied", "studied", "has been studying", "was studying"], key: 2, why: "Duration + present result → has been studying.", legacy: B1("He is exhausted because he ______ all afternoon.") }),
  d.mcq({ b: "past", t: "past-perfect-sequence", L: "B1", diff: 2, focus: "Past perfect for the earlier of two past events", pre: ["past-perfect", "past-participle"],
    prompt: "By the time we got to the station, the train ______.", options: ["left", "had left", "has left", "was leaving"], key: 1, why: "'By the time' + earlier event → past perfect.", legacy: B1("By the time we got to the station, the train ______.") }),
  d.gap({ b: "past", t: "past-perfect-sequence", L: "B1", diff: 2, focus: "Producing past perfect with 'already'", pre: ["past-perfect", "past-participle"],
    source: "When I got to the station, the train ______ (already / leave).", key: "had already left", alt: ["had left already"], why: "Earlier event → had + past participle." }),
  d.gap({ b: "past", t: "past-perfect-experience", L: "B1", diff: 2, focus: "Past participle after had never ... before", pre: ["past-perfect", "past-participle"],
    source: "She was nervous because she had never ______ (speak) in front of such a large audience before.", key: "spoken", why: "Past perfect → spoken.",
    legacy: B1("She was nervous because she ______ never ______ in front of such a large audience before.", "Two-gap paired-option MCQ rewritten as a single-gap fill isolating the participle.") }),
  d.correct({ b: "perfect", t: "perfect-vs-past", L: "B1", diff: 2, focus: "Present perfect cannot combine with a finished-time marker", pre: ["present-perfect", "past-simple", "time-adverbials"],
    source: "I have seen that film last week.", key: "I saw that film last week.", why: "'last week' is finished → past simple." }),
  d.rewrite({ b: "perfect", t: "since-duration", L: "B1", diff: 2, focus: "Turning a past start point into a present perfect duration", pre: ["present-perfect", "present-perfect-continuous"],
    source: "Ali moved to Tashkent in 2020. He still lives there.", hint: "Ali ______ in Tashkent since 2020.", key: "has lived", alt: ["has been living"], why: "Unfinished period from a start point." }),
  d.mcq({ b: "future", t: "arrangement-continuous", L: "B1", diff: 2, focus: "Present continuous for a fixed future arrangement", pre: ["present-continuous", "future-going-to"],
    prompt: "I ______ Sarah for lunch tomorrow. We arranged it last week.", options: ["meet", "am meeting", "will meet", "have met"], key: 1, why: "Arranged with another person → present continuous.", legacy: B1("I ______ Sarah for lunch tomorrow. We arranged it last week.") }),
  d.mcq({ b: "future", t: "timetable-simple", L: "B1", diff: 2, focus: "Present simple for a timetabled future event", pre: ["present-simple", "future-will"],
    prompt: "The flight ______ at 9:15 tomorrow morning.", options: ["is leaving", "leaves", "will leave", "has left"], key: 1, why: "Timetable → present simple.", legacy: B1("The flight ______ at 9:15 tomorrow morning.") }),
  d.mcq({ b: "future", t: "future-continuous", L: "B1", diff: 3, focus: "Future continuous for an action in progress at a future time", pre: ["future-continuous", "future-will"],
    prompt: "At this time next week, we ______ on the beach.", options: ["relax", "will relax", "will be relaxing", "have relaxed"], key: 2, why: "'At this time next week' → will be + -ing.", legacy: B1("At this time next week, we ______ on the beach.") }),
  d.mcq({ b: "used-to", t: "used-to-state", L: "B1", diff: 1, focus: "used to + base form for a discontinued past state", pre: ["used-to", "past-simple"],
    prompt: "I ______ live near the sea when I was a child.", options: ["use to", "used to", "was used to", "am used to"], key: 1, why: "Past state no longer true → used to.", legacy: B1("I ______ live near the sea when I was a child.") }),
  d.mcq({ b: "used-to", t: "didnt-use-to", L: "B1", diff: 2, focus: "Negative: didn't use to (no -d after did)", pre: ["used-to", "auxiliary-do"],
    prompt: "She didn't ______ like coffee, but now she drinks it every day.", options: ["used to", "use to", "using to", "be used to"], key: 1, why: "After 'did', the base form 'use to'.", legacy: B1("She didn't ______ like coffee, but now she drinks it every day.") }),
  d.guided({ b: "past", t: "interrupted-action", L: "B1", diff: 2, focus: "Productive contrast of past continuous (background) and past simple (interruption)", pre: ["past-continuous", "past-simple"],
    prompt: "Write a sentence about an action in progress that was interrupted by another event. Use the past progressive and past simple.",
    required: "past progressive for the ongoing action, past simple for the interrupting event", legacy: B1O("Write a sentence about an action in progress that was interrupted by another event. Use the past progressive and past simple.") }),
  d.guided({ b: "perfect", t: "continuous-present-result", L: "B1", diff: 2, focus: "Productive present perfect continuous linking activity to present state", pre: ["present-perfect-continuous"],
    prompt: "Write one sentence explaining why you are tired, dirty, wet, or out of breath. Use the present perfect progressive.",
    required: "present perfect progressive explaining a present state caused by a recent continuous activity", legacy: B1O("Write one sentence explaining why you are tired, dirty, wet, or out of breath. Use the present perfect progressive.") }),
  d.guided({ b: "used-to", t: "used-to-state", L: "B1", diff: 1, focus: "Productive used to for a discontinued habit or state", pre: ["used-to"],
    prompt: "Write one sentence about a past habit or state that is no longer true. Use used to.",
    required: "used to + base verb for a discontinued past habit or state", legacy: B1O("Write one sentence about a past habit or state that is no longer true. Use used to.") }),

  // ---------------- B2 ----------------
  d.mcq({ b: "present", t: "changing-trend", L: "B2", diff: 2, focus: "Present continuous for a developing trend ('these days')", pre: ["present-continuous", "time-adverbials"],
    prompt: "More people ______ online these days than they did five years ago.", options: ["shop", "have shopped", "are shopping", "shopped"], key: 2, why: "Change in progress over a period → continuous.", legacy: B2("More people ______ online these days than they did five years ago.") }),
  d.mcq({ b: "past", t: "past-perfect-continuous", L: "B2", diff: 2, focus: "Past perfect continuous for duration before a past point", pre: ["past-perfect-continuous"],
    prompt: "He was tired because he ______ for six hours before he finally stopped.", options: ["drove", "had driven", "had been driving", "was driving"], key: 2, why: "Duration up to a past moment → had been + -ing.", legacy: B2("He was tired because he ______ for six hours before he finally stopped.") }),
  d.gap({ b: "past", t: "past-simple-vs-continuous", L: "B2", diff: 1, focus: "Sequencing: past simple event against a past continuous background (not past perfect)", pre: ["past-simple", "past-continuous", "past-perfect"],
    source: "When I ______ (get) home, my brother ______ (cook) dinner, so I joined him.", key: ["got", "was cooking"], why: "'so I joined him' → cooking was still in progress, not completed.",
    legacy: B2("When I got home, my brother ______ dinner, so I joined him.", "Recast as a two-gap fill so the student must also produce the past simple event verb, not only recognise the background form.") }),
  d.correct({ b: "past", t: "past-perfect-sequence", L: "B2", diff: 1, focus: "'By the time' requires past perfect for the completed earlier action", pre: ["past-perfect"],
    source: "By the time the guests arrived, we prepared everything.", key: "By the time the guests arrived, we had prepared everything.", why: "Earlier completed event → had prepared." }),
  d.mcq({ b: "future", t: "future-perfect", L: "B2", diff: 2, focus: "Future perfect for completion before a future point", pre: ["future-perfect", "past-participle"],
    prompt: "By the end of the month, we ______ the project.", options: ["complete", "will complete", "will have completed", "will be completing"], key: 2, why: "'By the end of' → will have + past participle.", legacy: B2("By the end of the month, we ______ the project.") }),
  d.mcq({ b: "future", t: "future-perfect-continuous", L: "B2", diff: 3, focus: "Future perfect continuous for duration up to a future point", pre: ["future-perfect-continuous"],
    prompt: "By June, she ______ at the company for ten years.", options: ["will work", "will have worked", "will have been working", "is working"], key: 2, why: "Duration reaching a future point → will have been + -ing.", legacy: B2("By June, she ______ at the company for ten years."),
    flags: ["'will have worked' is also grammatical here; the key follows the legacy pool. Consider narrowing the stem before mass use."] }),
  d.mcq({ b: "future", t: "future-in-the-past", L: "B2", diff: 2, focus: "was going to for a future seen from a past viewpoint", pre: ["future-in-the-past", "future-going-to"],
    prompt: "I knew she ______ arrive late because of the traffic.", options: ["will", "was going to", "has", "is"], key: 1, why: "Past viewpoint on a future → was going to.", legacy: B2("I knew she ______ arrive late because of the traffic.") }),
  d.mcq({ b: "future", t: "about-to", L: "B2", diff: 1, focus: "be about to for an imminent action", pre: ["be-to"],
    prompt: "Hurry up. The film ______ start.", options: ["is about to", "has been", "would", "used to"], key: 0, why: "Imminent → about to.", legacy: B2("Hurry up. The film ______ start.") }),
  d.rewrite({ b: "perfect", t: "since-duration", L: "B2", diff: 1, focus: "Present perfect (continuous) from a past start point, formal register", pre: ["present-perfect", "present-perfect-continuous"],
    source: "She started working here in 2016. She still works here.", hint: "She ______ here since 2016.", key: "has been working", alt: ["has worked"], why: "Both perfect forms fit; continuous is the natural default." }),
  d.guided({ b: "past", t: "past-perfect-continuous", L: "B2", diff: 2, focus: "Productive past perfect continuous before a past event", pre: ["past-perfect-continuous"],
    prompt: "Describe an activity that continued for some time before another past event. Use the past perfect progressive.",
    required: "past perfect progressive (had been + -ing) for an activity continuing before another past event", legacy: B2O("Describe an activity that continued for some time before another past event. Use the past perfect progressive.") }),
  d.guided({ b: "future", t: "future-in-the-past", L: "B2", diff: 2, focus: "Productive future-in-the-past", pre: ["future-in-the-past"],
    prompt: "Write one sentence describing a future plan or expectation from a past point of view.",
    required: "a future-in-the-past form (was going to / would) describing a plan viewed from a past point", legacy: B2O("Write one sentence describing a future plan or expectation from a past point of view.") }),

  // ---------------- C1 ----------------
  d.mcq({ b: "future", t: "future-perfect-continuous", L: "C1", diff: 2, focus: "Future perfect continuous with a passive time clause as reference point", pre: ["future-perfect-continuous"],
    prompt: "By the time the review is published next year, the researchers ______ the data for nearly three years.", options: ["will analyse", "will have analysed", "will have been analysing", "are analysing"], key: 2, why: "Duration to a future point → will have been + -ing.", legacy: C1("By the time the review is published next year, the researchers ______ the data for nearly three years.") }),
  d.mcq({ b: "past", t: "past-perfect-continuous", L: "C1", diff: 1, focus: "Past perfect continuous with 'before + -ing' clause", pre: ["past-perfect-continuous"],
    prompt: "The committee ______ the proposal for several months before reaching a final decision.", options: ["had considered", "had been considering", "has considered", "was considering"], key: 1, why: "Duration before a past decision → had been considering.", legacy: C1("The committee ______ the proposal for several months before reaching a final decision.") }),
  d.mcq({ b: "future", t: "unfulfilled-arrangement", L: "C1", diff: 3, focus: "be to + perfect infinitive for an arrangement that did not happen", pre: ["be-to", "perfect-infinitive"],
    prompt: "The ceremony ______ on Friday, but it was postponed because of the storm.", options: ["was to have taken place", "was taking place", "had taken place", "would take place"], key: 0, why: "Unfulfilled past arrangement → was to have + past participle." }),
  d.gap({ b: "perfect", t: "nth-time-perfect", L: "C1", diff: 1, focus: "'It's the Nth time (that)' + present perfect", pre: ["present-perfect"],
    source: "This ______ (be) the third time this week that the server ______ (crash).", key: ["is", "has crashed"], why: "'the third time that' → present perfect in the that-clause." }),
  d.mcq({ b: "used-to", t: "would-vs-used-to", L: "C1", diff: 2, focus: "would for past habits cannot describe a past state — used to can", pre: ["used-to", "stative-verbs"],
    prompt: "When we were children, we ______ a dog called Max.", options: ["would have", "used to have", "were having", "had been having"], key: 1, why: "'have a dog' is a state → used to, not would." }),
  d.rewrite({ b: "used-to", t: "would-habit", L: "C1", diff: 2, focus: "would for a repeated past action (narrative register)", pre: ["used-to"],
    source: "Every summer my grandfather used to take us fishing on the lake.", hint: "Every summer my grandfather ______ fishing on the lake.", key: "would take us", why: "Repeated past action → would + base." }),
  d.guided({ b: "future", t: "future-perfect-continuous", L: "C1", diff: 2, focus: "Productive future perfect continuous with explicit future reference", pre: ["future-perfect-continuous"],
    prompt: "Write a sentence describing an activity that will have continued for a specific length of time by a stated future point. Use the future perfect progressive.",
    required: "future perfect progressive (will have been + -ing) for a duration completed by a future point", legacy: C1O("Write a sentence describing an activity that will have continued for a specific length of time by a stated future point. Use the future perfect progressive.") }),
  d.guided({ b: "past", t: "perfect-vs-perfect-continuous", L: "C1", diff: 3, focus: "Productive contrast of past perfect and past perfect continuous", pre: ["past-perfect", "past-perfect-continuous"],
    prompt: "Write two connected sentences contrasting a completed past event with an activity that had been continuing before it. Use past perfect and past perfect progressive.",
    required: "past perfect for the completed event, past perfect progressive for the continuing activity before it, correctly contrasted", constraints: ["exactly two connected sentences"],
    legacy: C1O("Write two connected sentences contrasting a completed past event with an activity that had been continuing before it. Use past perfect and past perfect progressive.") }),

  // ---------------- C2 ----------------
  d.rewrite({ b: "future", t: "unfulfilled-arrangement", L: "C2", diff: 2, focus: "Producing 'was to have + past participle' for an arrangement that did not happen", pre: ["be-to", "perfect-infinitive"],
    source: "The minister was due to arrive at nine, but she never came.", hint: "The minister ______ at nine, but she never came.", key: "was to have arrived", why: "Formal unfulfilled arrangement → was to have + pp.",
    flags: ["c2-check: distinguishes from the C1 recognition item by requiring production of the form; grammatical (not lexical) demand. C2 placement provisional."] }),
  d.mcq({ b: "present", t: "will-characteristic", L: "C2", diff: 2, focus: "'will' expressing characteristic/habitual behaviour rather than future time", pre: ["future-will", "present-simple"],
    prompt: "Don't worry about the noise — he ______ talk to himself when he's concentrating.", options: ["will", "would", "is going to", "shall"], key: 0, why: "Present characteristic behaviour → 'will' (habitual), not future.", overlaps: ["modals"],
    flags: ["c2-check: habitual 'will' is an aspectual use of a modal form — owned by Tenses as time/aspect, flagged for Modals."] }),
];