import { domainBuilder, leg } from "@/lib/adaptiveGrammar/build";
const d = domainBuilder("verb-patterns");
const A1 = leg("A1_MCQ"), A2 = leg("A2_MCQ"), B1 = leg("B1_MCQ"), B2 = leg("B2_MCQ"), B1O = leg("B1_OPEN_GRAMMAR"), B2O = leg("B2_OPEN_GRAMMAR");

export default [
  // ---------------- A1 ---------------- (have got, provisional owner: Verb Patterns)
  d.mcq({ b: "have-got", t: "have-has", L: "A1", diff: 1, focus: "have (not has) with I", pre: ["have-got"],
    prompt: "I ______ a new phone.", options: ["has", "have", "having", "am have"], key: 1, why: "I → have.", legacy: A1("I ______ a new phone.") }),
  d.mcq({ b: "have-got", t: "have-has", L: "A1", diff: 1, focus: "has with third person singular", pre: ["have-got", "third-person-s"],
    prompt: "She ______ a small dog.", options: ["have", "having", "has", "is have"], key: 2, why: "She → has.", legacy: A1("She ______ a small dog.") }),
  d.mcq({ b: "have-got", t: "have-got-question", L: "A1", diff: 2, focus: "Has ... got question form", pre: ["have-got", "subject-auxiliary-inversion"],
    prompt: "______ he got a car?", options: ["Have", "Has", "Is", "Does"], key: 1, why: "have got → Has he got.", legacy: A1("______ he got a car?") }),
  d.mcq({ b: "have-got", t: "have-got-negative", L: "A1", diff: 2, focus: "haven't got (not haven't have)", pre: ["have-got"],
    prompt: "They haven't ______ any money.", options: ["got", "gets", "getting", "have"], key: 0, why: "haven't got.", legacy: A1("They haven't ______ any money.") }),
  d.gap({ b: "have-got", t: "have-has", L: "A1", diff: 2, focus: "Producing has got for third person", pre: ["have-got"],
    instr: "Complete with the correct form of 'have got'.", source: "My brother ______ two bicycles.", key: "has got", alt: ["'s got"], why: "Third person → has got." }),

  // ---------------- A2 ----------------
  d.mcq({ b: "gerund-infinitive", t: "enjoy-gerund", L: "A2", diff: 1, focus: "enjoy + -ing", pre: ["gerund"],
    prompt: "She enjoys ______ in her free time.", options: ["read", "reading", "to read", "reads"], key: 1, why: "'enjoy' takes a gerund.", legacy: A2("She enjoys ______ in her free time.") }),
  d.mcq({ b: "gerund-infinitive", t: "decide-infinitive", L: "A2", diff: 1, focus: "decide + to-infinitive", pre: ["to-infinitive"],
    prompt: "They decided ______ home early.", options: ["go", "going", "to go", "went"], key: 2, why: "'decide' takes to-infinitive.", legacy: A2("They decided ______ home early.") }),
  d.mcq({ b: "gerund-infinitive", t: "would-like-infinitive", L: "A2", diff: 1, focus: "would like + to-infinitive", pre: ["to-infinitive"],
    prompt: "I would like ______ more about the course.", options: ["learn", "learning", "to learn", "learned"], key: 2, why: "'would like' + to-infinitive.", legacy: A2("I would like ______ more about the course.") }),
  d.gap({ b: "gerund-infinitive", t: "want-infinitive", L: "A2", diff: 1, focus: "want + to-infinitive", pre: ["to-infinitive"],
    source: "My sister wants ______ (be) a nurse.", key: "to be", why: "want + to-infinitive." }),
  d.gap({ b: "gerund-infinitive", t: "preposition-gerund", L: "A2", diff: 2, focus: "-ing form after a preposition", pre: ["gerund", "preposition-gerund"],
    source: "I'm good at ______ (swim), but I'm bad at ______ (run).", key: ["swimming", "running"], why: "Preposition + -ing." }),
  d.correct({ b: "gerund-infinitive", t: "enjoy-gerund", L: "A2", diff: 2, focus: "like/love + -ing (or to) but never bare infinitive", pre: ["gerund", "to-infinitive"],
    source: "My father loves cook on Sundays.", key: "My father loves cooking on Sundays.", alt: ["My father loves to cook on Sundays."], why: "love + -ing / to-infinitive." }),
  d.mcq({ b: "object-infinitive", t: "let-bare", L: "A2", diff: 2, focus: "let + object + bare infinitive", pre: ["bare-infinitive", "verb-object-infinitive"],
    prompt: "My parents don't let me ______ out late.", options: ["stay", "to stay", "staying", "stayed"], key: 0, why: "let + object + bare infinitive." }),

  // ---------------- B1 ----------------
  d.mcq({ b: "meaning-change-verbs", t: "stop-gerund", L: "B1", diff: 2, focus: "stop + -ing = cease an activity", pre: ["gerund", "meaning-change-verbs"],
    prompt: "I stopped ______ because I was tired.", options: ["to work", "working", "work", "worked"], key: 1, why: "Stopped the activity of working → -ing.", legacy: B1("I stopped ______ because I was tired.") }),
  d.mcq({ b: "meaning-change-verbs", t: "stop-infinitive", L: "B1", diff: 2, focus: "stop + to-infinitive = purpose", pre: ["to-infinitive", "meaning-change-verbs"],
    prompt: "I stopped ______ some water because I was thirsty.", options: ["drinking", "drink", "to drink", "drank"], key: 2, why: "Stopped in order to drink → to-infinitive.", legacy: B1("I stopped ______ some water because I was thirsty.") }),
  d.mcq({ b: "meaning-change-verbs", t: "remember-gerund", L: "B1", diff: 2, focus: "remember + -ing for a past memory", pre: ["gerund", "meaning-change-verbs"],
    prompt: "I remember ______ him at the party last year.", options: ["meeting", "to meet", "meet", "met"], key: 0, why: "Memory of a past event → -ing.", legacy: B1("I remember ______ him at the party last year.") }),
  d.gap({ b: "meaning-change-verbs", t: "remember-infinitive", L: "B1", diff: 2, focus: "remember + to-infinitive for a task to do", pre: ["to-infinitive", "meaning-change-verbs"],
    source: "Please remember ______ (lock) the door when you leave.", key: "to lock", why: "Obligation still to do → to-infinitive." }),
  d.mcq({ b: "gerund-infinitive", t: "get-used-to", L: "B1", diff: 3, focus: "get used to + -ing/noun (distinct from used to + base)", pre: ["gerund", "used-to"],
    prompt: "It took me a few weeks to ______ waking up early.", options: ["used to", "use to", "get used to", "get use to"], key: 2, why: "Becoming accustomed → get used to + -ing.", legacy: B1("It took me a few weeks to ______ waking up early."), overlaps: ["tenses"] }),
  d.mcq({ b: "object-infinitive", t: "want-object-infinitive", L: "B1", diff: 1, focus: "want + object + to-infinitive", pre: ["verb-object-infinitive"],
    prompt: "My teacher wants ______ the essay again.", options: ["me to write", "that I write", "me writing", "me write"], key: 0, why: "want + object + to-infinitive." }),
  d.mcq({ b: "gerund-infinitive", t: "avoid-gerund", L: "B1", diff: 2, focus: "avoid + -ing", pre: ["gerund"],
    prompt: "You should avoid ______ too much coffee before bed.", options: ["to drink", "drinking", "drink", "drank"], key: 1, why: "avoid + -ing." }),
  d.correct({ b: "gerund-infinitive", t: "look-forward-to", L: "B1", diff: 3, focus: "look forward to + -ing ('to' is a preposition here)", pre: ["preposition-gerund", "gerund"],
    source: "I look forward to see you next week.", key: "I look forward to seeing you next week.", why: "'to' is a preposition → -ing." }),
  d.guided({ b: "meaning-change-verbs", t: "stop-contrast", L: "B1", diff: 3, focus: "Productive contrast of stop + -ing vs stop + to-infinitive", pre: ["meaning-change-verbs"],
    prompt: "Write two sentences showing the different meanings of stop + -ing and stop + infinitive.", required: "both stop + -ing and stop + to-infinitive used correctly to show the meaning difference", constraints: ["exactly two sentences"],
    legacy: B1O("Write two sentences showing the different meanings of stop + -ing and stop + infinitive.") }),
  d.guided({ b: "gerund-infinitive", t: "get-used-to", L: "B1", diff: 2, focus: "Productive get used to + -ing/noun", pre: ["gerund", "used-to"],
    prompt: "Write one sentence about something you are gradually becoming accustomed to. Use get used to.", required: "get used to + -ing/noun for a gradually developing habit",
    legacy: B1O("Write one sentence about something you are gradually becoming accustomed to. Use get used to."), overlaps: ["tenses"] }),

  // ---------------- B2 ----------------
  d.mcq({ b: "meaning-change-verbs", t: "regret-formal", L: "B2", diff: 2, focus: "regret + to-infinitive for announcing bad news", pre: ["to-infinitive", "meaning-change-verbs"],
    prompt: "I regret ______ you that your application was unsuccessful.", options: ["informing", "to inform", "inform", "informed"], key: 1, why: "Announcing bad news → regret to inform.", legacy: B2("I regret ______ you that your application was unsuccessful.") }),
  d.mcq({ b: "meaning-change-verbs", t: "regret-past", L: "B2", diff: 2, focus: "regret + -ing for a past action", pre: ["gerund", "meaning-change-verbs"],
    prompt: "I regret ______ so much money on that unnecessary purchase.", options: ["to spend", "spending", "spend", "spent"], key: 1, why: "Regretting a past action → -ing.", legacy: B2("I regret ______ so much money on that unnecessary purchase.") }),
  d.mcq({ b: "meaning-change-verbs", t: "go-on", L: "B2", diff: 2, focus: "go on + -ing = continue the same activity", pre: ["gerund", "meaning-change-verbs"],
    prompt: "He went on ______ about the problem for another hour.", options: ["complain", "to complain", "complaining", "complained"], key: 2, why: "Continuing the same activity → -ing.", legacy: B2("He went on ______ about the problem for another hour.") }),
  d.correct({ b: "object-infinitive", t: "make-bare", L: "B2", diff: 1, focus: "make + object + BARE infinitive", pre: ["bare-infinitive", "verb-object-infinitive"],
    source: "My parents made me to apologise to my sister.", key: "My parents made me apologise to my sister.", why: "make takes bare infinitive." }),
  d.mcq({ b: "gerund-infinitive", t: "suggest-pattern", L: "B2", diff: 2, focus: "suggest + -ing / that-clause, never + object + to-infinitive", pre: ["gerund", "verb-that-clause"],
    prompt: "She suggested ______ the meeting until Monday.", options: ["to postpone", "us to postpone", "postponing", "postpone"], key: 2, why: "suggest + -ing." }),
  d.mcq({ b: "perfect-forms", t: "perfect-infinitive", L: "B2", diff: 2, focus: "seem + perfect infinitive for an earlier event", pre: ["perfect-infinitive"],
    prompt: "The thieves seem ______ through the back window.", options: ["to enter", "to have entered", "entering", "to be entered"], key: 1, why: "Earlier completed action → to have + pp." }),
  d.rewrite({ b: "gerund-infinitive", t: "gerund-subject", L: "B2", diff: 2, focus: "Gerund phrase as the subject of a sentence", pre: ["gerund"],
    instr: "Rewrite the sentence starting with the -ing form of the verb. Keep the meaning.", source: "It is dangerous to swim in the river after heavy rain.", hint: "______ is dangerous.", key: "Swimming in the river after heavy rain", why: "Gerund phrase as subject." }),
  d.gap({ b: "object-infinitive", t: "help-pattern", L: "B2", diff: 1, focus: "help + object + (to) infinitive — both accepted", pre: ["verb-object-infinitive", "bare-infinitive"],
    source: "Could you help me ______ (carry) these boxes upstairs?", key: "carry", alt: ["to carry"], why: "help takes bare or to-infinitive." }),
  d.guided({ b: "meaning-change-verbs", t: "go-on", L: "B2", diff: 3, focus: "Productive contrast of go on + -ing vs go on + to-infinitive", pre: ["meaning-change-verbs"],
    prompt: "Write two sentences showing different meanings of go on + -ing and go on + to-infinitive.", required: "both go on + -ing and go on + to-infinitive used correctly to show the meaning contrast", constraints: ["exactly two sentences"],
    legacy: B2O("Write two sentences showing different meanings of go on + -ing and go on + to-infinitive.") }),
  d.guided({ b: "meaning-change-verbs", t: "regret-formal", L: "B2", diff: 2, focus: "Productive regret + to-infinitive for bad news", pre: ["meaning-change-verbs"],
    prompt: "Write one sentence using regret + to-infinitive to give bad news.", required: "regret + to-infinitive used to introduce bad news",
    legacy: B2O("Write one sentence using regret + to-infinitive to give bad news.") }),

  // ---------------- C1 ----------------
  d.rewrite({ b: "meaning-change-verbs", t: "regret-formal", L: "C1", diff: 2, focus: "Formal regret + to-infinitive transformation", pre: ["to-infinitive", "meaning-change-verbs"],
    instr: "Rewrite the sentence more formally, starting with the words given.", source: "We are sorry to tell you that the event has been cancelled.", hint: "We regret ______",
    key: "to inform you that the event has been cancelled", alt: ["to tell you that the event has been cancelled"], why: "regret + to-infinitive for bad news." }),
  d.mcq({ b: "perfect-forms", t: "perfect-gerund", L: "C1", diff: 2, focus: "Perfect gerund (having + pp) to mark an action earlier than the main verb", pre: ["perfect-gerund", "gerund"],
    prompt: "He denied ______ the email, although his name was on it.", options: ["to have sent", "having sent", "to send", "having been sent"], key: 1, why: "deny + gerund; earlier action → having sent.", overlaps: ["reported-speech"] }),
  d.mcq({ b: "perfect-forms", t: "passive-infinitive", L: "C1", diff: 2, focus: "Passive to-infinitive after an adjective", pre: ["to-infinitive", "passive-be-participle"],
    prompt: "These documents are too confidential ______ by email.", options: ["to send", "to be sent", "sending", "to have sent"], key: 1, why: "The documents receive the action → to be sent.", overlaps: ["passive-causative"] }),
  d.gap({ b: "gerund-infinitive", t: "need-doing", L: "C1", diff: 2, focus: "need + -ing with passive meaning", pre: ["gerund", "passive-infinitive-gerund"],
    source: "The car is filthy — it really needs ______ (wash).", key: "washing", alt: ["to be washed"], why: "need + -ing = needs to be washed.", overlaps: ["passive-causative"] }),
  d.correct({ b: "gerund-infinitive", t: "suggest-pattern", L: "C1", diff: 2, focus: "recommend/suggest + that-clause or -ing, not + object + to-infinitive", pre: ["verb-that-clause", "gerund"],
    source: "The doctor recommended me to take a week off work.", key: "The doctor recommended that I take a week off work.", alt: ["The doctor recommended taking a week off work.", "The doctor recommended that I took a week off work."], why: "recommend does not take object + to-infinitive." }),

  // ---------------- C2 ----------------
  d.mcq({ b: "perfect-forms", t: "perfect-infinitive-unreal", L: "C2", diff: 3, focus: "Perfect infinitive after 'was to / meant to / hoped to' for an unfulfilled intention", pre: ["perfect-infinitive", "be-to"],
    prompt: "I meant ______ you yesterday, but the day got away from me.", options: ["to call", "to have called", "calling", "to be calling"], key: 1, why: "Intention not carried out → meant to have + pp (perfect infinitive of unfulfilled intention).", overlaps: ["tenses"],
    flags: ["c2-check: 'meant to call' is also acceptable in everyday English; the perfect infinitive is the marked, literary form. Diagnostic value is recognition that the perfect infinitive exists here. C2 provisional."] }),
];