// AUTO-GENERATED by tools/grammar-practice/ingest.mjs — do not edit by hand.
// Pool sizes per topic and stage, counting slot expansion. Lets the node map
// render real numbers without loading a single bank.
export const PRACTICE_MANIFEST = {
 "tenses.present.continuous-now": {
  "domain": "tenses",
  "branch": "present",
  "topic": "continuous-now",
  "authored": 68,
  "stages": {
   "choose": 320,
   "build": 320,
   "transform": 240,
   "create": 8,
   "express": 5
  }
 },
 "tenses.present.simple-negative": {
  "domain": "tenses",
  "branch": "present",
  "topic": "simple-negative",
  "authored": 68,
  "stages": {
   "choose": 320,
   "build": 320,
   "transform": 240,
   "create": 8,
   "express": 5
  }
 },
 "tenses.present.simple-routine": {
  "domain": "tenses",
  "branch": "present",
  "topic": "simple-routine",
  "authored": 68,
  "stages": {
   "choose": 320,
   "build": 320,
   "transform": 72,
   "create": 8,
   "express": 5
  }
 },
 "tenses.present.third-person-s": {
  "domain": "tenses",
  "branch": "present",
  "topic": "third-person-s",
  "authored": 68,
  "stages": {
   "choose": 20,
   "build": 58,
   "transform": 15,
   "create": 8,
   "express": 5
  }
 }
};

export const topicsInBranch = (domain, branch) =>
  Object.values(PRACTICE_MANIFEST).filter((m) => m.domain === domain && m.branch === branch);

export const branchHasPractice = (domain, branch) =>
  Object.values(PRACTICE_MANIFEST).some((m) => m.domain === domain && m.branch === branch);
